//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.03 at 11:31:16 PM CDT 
//


package gov.mncourts.casetget;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AmendmentReasonJudgmentTypeCodeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AmendmentReasonJudgmentTypeCodeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="AMEND"/>
 *     &lt;enumeration value="APREVERS"/>
 *     &lt;enumeration value="CTORDER"/>
 *     &lt;enumeration value="MOTGRANT"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AmendmentReasonJudgmentTypeCodeType")
@XmlEnum
public enum AmendmentReasonJudgmentTypeCodeType {

    AMEND,
    APREVERS,
    CTORDER,
    MOTGRANT;

    public String value() {
        return name();
    }

    public static AmendmentReasonJudgmentTypeCodeType fromValue(String v) {
        return valueOf(v);
    }

}
