//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.03 at 11:31:16 PM CDT 
//


package gov.mncourts.casetget;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for AssessmentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AssessmentType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FinancialCategoryText" type="{http://www.courts.state.mn.us/CourtXML/3}FinancialCategoryCodeTextType"/>
 *         &lt;element name="CurrentBalanceAmount" type="{http://www.courts.state.mn.us/CourtXML/3}CurrencyType"/>
 *         &lt;element name="DueDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="partyKey" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AssessmentType", propOrder = {
    "financialCategoryText",
    "currentBalanceAmount",
    "dueDate"
})
public class AssessmentType {

    @XmlElement(name = "FinancialCategoryText", required = true)
    protected FinancialCategoryCodeTextType financialCategoryText;
    @XmlElement(name = "CurrentBalanceAmount")
    protected double currentBalanceAmount;
    @XmlElement(name = "DueDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dueDate;
    @XmlAttribute(name = "partyKey", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String partyKey;

    /**
     * Gets the value of the financialCategoryText property.
     * 
     * @return
     *     possible object is
     *     {@link FinancialCategoryCodeTextType }
     *     
     */
    public FinancialCategoryCodeTextType getFinancialCategoryText() {
        return financialCategoryText;
    }

    /**
     * Sets the value of the financialCategoryText property.
     * 
     * @param value
     *     allowed object is
     *     {@link FinancialCategoryCodeTextType }
     *     
     */
    public void setFinancialCategoryText(FinancialCategoryCodeTextType value) {
        this.financialCategoryText = value;
    }

    /**
     * Gets the value of the currentBalanceAmount property.
     * 
     */
    public double getCurrentBalanceAmount() {
        return currentBalanceAmount;
    }

    /**
     * Sets the value of the currentBalanceAmount property.
     * 
     */
    public void setCurrentBalanceAmount(double value) {
        this.currentBalanceAmount = value;
    }

    /**
     * Gets the value of the dueDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDueDate() {
        return dueDate;
    }

    /**
     * Sets the value of the dueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDueDate(XMLGregorianCalendar value) {
        this.dueDate = value;
    }

    /**
     * Gets the value of the partyKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartyKey() {
        return partyKey;
    }

    /**
     * Sets the value of the partyKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartyKey(String value) {
        this.partyKey = value;
    }

}
