//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.03 at 11:31:16 PM CDT 
//


package gov.mncourts.casetget;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BalanceDueTextType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="BalanceDueTextType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Inactive"/>
 *     &lt;enumeration value="Satisfied"/>
 *     &lt;enumeration value="Expired"/>
 *     &lt;enumeration value="Bankruptcy"/>
 *     &lt;enumeration value="Dismissed"/>
 *     &lt;enumeration value="Vacated"/>
 *     &lt;enumeration value="Renewed"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "BalanceDueTextType")
@XmlEnum
public enum BalanceDueTextType {

    @XmlEnumValue("Inactive")
    INACTIVE("Inactive"),
    @XmlEnumValue("Satisfied")
    SATISFIED("Satisfied"),
    @XmlEnumValue("Expired")
    EXPIRED("Expired"),
    @XmlEnumValue("Bankruptcy")
    BANKRUPTCY("Bankruptcy"),
    @XmlEnumValue("Dismissed")
    DISMISSED("Dismissed"),
    @XmlEnumValue("Vacated")
    VACATED("Vacated"),
    @XmlEnumValue("Renewed")
    RENEWED("Renewed");
    private final String value;

    BalanceDueTextType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static BalanceDueTextType fromValue(String v) {
        for (BalanceDueTextType c: BalanceDueTextType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
