//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.03 at 11:31:16 PM CDT 
//


package gov.mncourts.casetget;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for CaseGetChargeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CaseGetChargeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}ChargeSequenceID"/>
 *         &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}ChargeFiledDate" minOccurs="0"/>
 *         &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}OffenseID"/>
 *         &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}OffenseCite" minOccurs="0"/>
 *         &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}OffenseDescriptionText" minOccurs="0"/>
 *         &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}OffenseDate"/>
 *         &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}OffenseTime" minOccurs="0"/>
 *         &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}OffenseDateEnd" minOccurs="0"/>
 *         &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}OffenseTimeEnd" minOccurs="0"/>
 *         &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}OffenseDatesOnOrAbout"/>
 *         &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}OffenseTimesAtOrAbout" minOccurs="0"/>
 *         &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}OffenseLocationText" minOccurs="0"/>
 *         &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}OffenseOwnerText" minOccurs="0"/>
 *         &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}OffenseTypeText" minOccurs="0"/>
 *         &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}SeverityLevelText"/>
 *         &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}GeneralOffenseCodeText" minOccurs="0"/>
 *         &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}MinnesotaOffenseCode" minOccurs="0"/>
 *         &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}ChargeLegalDescriptionText"/>
 *         &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}PredatoryOffenderRegistrationRequiredIndicator" minOccurs="0"/>
 *         &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}TargetedMisdemeanorIndicator" minOccurs="0"/>
 *         &lt;element name="ChargeStatuteSupplemental" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}StatuteTypeText"/>
 *                   &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}OffenseID"/>
 *                   &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}OffenseCite" minOccurs="0"/>
 *                   &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}OffenseDescriptionText" minOccurs="0"/>
 *                   &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}SeverityLevelText" minOccurs="0"/>
 *                   &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}ChargeLegalDescriptionText"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Arrest" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}ArrestDate" minOccurs="0"/>
 *                   &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}ArrestTime" minOccurs="0"/>
 *                   &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}ArrestingAgencyORI" minOccurs="0"/>
 *                   &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}ArrestingAgencyControlNumber" minOccurs="0"/>
 *                   &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}ArrestingOfficial" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Report" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}ReportingAgencyORI" minOccurs="0"/>
 *                   &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}ReportingAgencyControlNumber" minOccurs="0"/>
 *                   &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}ReportingOfficial" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}ProsecutingAgencyORI" minOccurs="0"/>
 *         &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}CommunityOfOffenseText" minOccurs="0"/>
 *         &lt;element name="Vehicle" type="{http://www.courts.state.mn.us/CourtXML/3}CaseGetVehicleType" minOccurs="0"/>
 *         &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}AccidentDamageText" minOccurs="0"/>
 *         &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}Speeding" minOccurs="0"/>
 *         &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}AnimalsOverLimitCount" minOccurs="0"/>
 *         &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}VehicleOverweightMeasure" minOccurs="0"/>
 *         &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}BloodAlcoholConcentration" minOccurs="0"/>
 *         &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}ReportToDPSIndicator" minOccurs="0"/>
 *         &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}ReportToDNRIndicator" minOccurs="0"/>
 *         &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}ChargeSubjectReference"/>
 *         &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}ChargePlea" minOccurs="0"/>
 *         &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}ChargeAmended" minOccurs="0"/>
 *         &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}TrialDemand" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="chargeKey" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *       &lt;attribute name="chargeVersionKey" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CaseGetChargeType", propOrder = {
    "chargeSequenceID",
    "chargeFiledDate",
    "offenseID",
    "offenseCite",
    "offenseDescriptionText",
    "offenseDate",
    "offenseTime",
    "offenseDateEnd",
    "offenseTimeEnd",
    "offenseDatesOnOrAbout",
    "offenseTimesAtOrAbout",
    "offenseLocationText",
    "offenseOwnerText",
    "offenseTypeText",
    "severityLevelText",
    "generalOffenseCodeText",
    "minnesotaOffenseCode",
    "chargeLegalDescriptionText",
    "predatoryOffenderRegistrationRequiredIndicator",
    "targetedMisdemeanorIndicator",
    "chargeStatuteSupplemental",
    "arrest",
    "report",
    "prosecutingAgencyORI",
    "communityOfOffenseText",
    "vehicle",
    "accidentDamageText",
    "speeding",
    "animalsOverLimitCount",
    "vehicleOverweightMeasure",
    "bloodAlcoholConcentration",
    "reportToDPSIndicator",
    "reportToDNRIndicator",
    "chargeSubjectReference",
    "chargePlea",
    "chargeAmended",
    "trialDemand"
})
@XmlSeeAlso({
    gov.mncourts.casetget.CaseInformation.Charge.class
})
public class CaseGetChargeType {

    @XmlElement(name = "ChargeSequenceID", required = true)
    protected ChargeSequenceIDType chargeSequenceID;
    @XmlElement(name = "ChargeFiledDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar chargeFiledDate;
    @XmlElement(name = "OffenseID", required = true)
    protected OffenseIDType offenseID;
    @XmlElement(name = "OffenseCite")
    protected String offenseCite;
    @XmlElement(name = "OffenseDescriptionText")
    protected String offenseDescriptionText;
    @XmlElement(name = "OffenseDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar offenseDate;
    @XmlElement(name = "OffenseTime")
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar offenseTime;
    @XmlElement(name = "OffenseDateEnd")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar offenseDateEnd;
    @XmlElement(name = "OffenseTimeEnd")
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar offenseTimeEnd;
    @XmlElement(name = "OffenseDatesOnOrAbout")
    protected boolean offenseDatesOnOrAbout;
    @XmlElement(name = "OffenseTimesAtOrAbout")
    protected Boolean offenseTimesAtOrAbout;
    @XmlElement(name = "OffenseLocationText")
    protected String offenseLocationText;
    @XmlElement(name = "OffenseOwnerText")
    protected String offenseOwnerText;
    @XmlElement(name = "OffenseTypeText")
    protected String offenseTypeText;
    @XmlElement(name = "SeverityLevelText", required = true, nillable = true)
    protected OffenseSeverityLevelTypeCodeTextType severityLevelText;
    @XmlElement(name = "GeneralOffenseCodeText", nillable = true)
    protected GeneralOffenseCodeTextTypeCodeTextType generalOffenseCodeText;
    @XmlElement(name = "MinnesotaOffenseCode")
    protected String minnesotaOffenseCode;
    @XmlElement(name = "ChargeLegalDescriptionText", required = true)
    protected String chargeLegalDescriptionText;
    @XmlElement(name = "PredatoryOffenderRegistrationRequiredIndicator")
    protected Boolean predatoryOffenderRegistrationRequiredIndicator;
    @XmlElement(name = "TargetedMisdemeanorIndicator")
    protected Boolean targetedMisdemeanorIndicator;
    @XmlElement(name = "ChargeStatuteSupplemental")
    protected List<CaseGetChargeType.ChargeStatuteSupplemental> chargeStatuteSupplemental;
    @XmlElement(name = "Arrest")
    protected CaseGetChargeType.Arrest arrest;
    @XmlElement(name = "Report")
    protected CaseGetChargeType.Report report;
    @XmlElement(name = "ProsecutingAgencyORI")
    protected ProsecutingAgencyORIType prosecutingAgencyORI;
    @XmlElement(name = "CommunityOfOffenseText", nillable = true)
    protected CommunityOfOffenseCodeTextType communityOfOffenseText;
    @XmlElement(name = "Vehicle")
    protected CaseGetVehicleType vehicle;
    @XmlElement(name = "AccidentDamageText", nillable = true)
    protected CitationAccidentTypeCodeTextType accidentDamageText;
    @XmlElement(name = "Speeding")
    protected SpeedingType speeding;
    @XmlElement(name = "AnimalsOverLimitCount")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger animalsOverLimitCount;
    @XmlElement(name = "VehicleOverweightMeasure")
    protected VehicleOverweightMeasureType vehicleOverweightMeasure;
    @XmlElement(name = "BloodAlcoholConcentration")
    protected BloodAlcoholConcentrationType bloodAlcoholConcentration;
    @XmlElement(name = "ReportToDPSIndicator")
    protected Boolean reportToDPSIndicator;
    @XmlElement(name = "ReportToDNRIndicator")
    protected Boolean reportToDNRIndicator;
    @XmlElement(name = "ChargeSubjectReference", required = true)
    protected ChargeSubjectReferenceType chargeSubjectReference;
    @XmlElement(name = "ChargePlea")
    protected PleaType chargePlea;
    @XmlElement(name = "ChargeAmended")
    protected ChargeAmended chargeAmended;
    @XmlElement(name = "TrialDemand")
    protected List<TrialDemand> trialDemand;
    @XmlAttribute(name = "chargeKey", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger chargeKey;
    @XmlAttribute(name = "chargeVersionKey", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger chargeVersionKey;

    /**
     * Gets the value of the chargeSequenceID property.
     * 
     * @return
     *     possible object is
     *     {@link ChargeSequenceIDType }
     *     
     */
    public ChargeSequenceIDType getChargeSequenceID() {
        return chargeSequenceID;
    }

    /**
     * Sets the value of the chargeSequenceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChargeSequenceIDType }
     *     
     */
    public void setChargeSequenceID(ChargeSequenceIDType value) {
        this.chargeSequenceID = value;
    }

    /**
     * Gets the value of the chargeFiledDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getChargeFiledDate() {
        return chargeFiledDate;
    }

    /**
     * Sets the value of the chargeFiledDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setChargeFiledDate(XMLGregorianCalendar value) {
        this.chargeFiledDate = value;
    }

    /**
     * Gets the value of the offenseID property.
     * 
     * @return
     *     possible object is
     *     {@link OffenseIDType }
     *     
     */
    public OffenseIDType getOffenseID() {
        return offenseID;
    }

    /**
     * Sets the value of the offenseID property.
     * 
     * @param value
     *     allowed object is
     *     {@link OffenseIDType }
     *     
     */
    public void setOffenseID(OffenseIDType value) {
        this.offenseID = value;
    }

    /**
     * Gets the value of the offenseCite property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOffenseCite() {
        return offenseCite;
    }

    /**
     * Sets the value of the offenseCite property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOffenseCite(String value) {
        this.offenseCite = value;
    }

    /**
     * Gets the value of the offenseDescriptionText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOffenseDescriptionText() {
        return offenseDescriptionText;
    }

    /**
     * Sets the value of the offenseDescriptionText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOffenseDescriptionText(String value) {
        this.offenseDescriptionText = value;
    }

    /**
     * Gets the value of the offenseDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getOffenseDate() {
        return offenseDate;
    }

    /**
     * Sets the value of the offenseDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setOffenseDate(XMLGregorianCalendar value) {
        this.offenseDate = value;
    }

    /**
     * Gets the value of the offenseTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getOffenseTime() {
        return offenseTime;
    }

    /**
     * Sets the value of the offenseTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setOffenseTime(XMLGregorianCalendar value) {
        this.offenseTime = value;
    }

    /**
     * Gets the value of the offenseDateEnd property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getOffenseDateEnd() {
        return offenseDateEnd;
    }

    /**
     * Sets the value of the offenseDateEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setOffenseDateEnd(XMLGregorianCalendar value) {
        this.offenseDateEnd = value;
    }

    /**
     * Gets the value of the offenseTimeEnd property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getOffenseTimeEnd() {
        return offenseTimeEnd;
    }

    /**
     * Sets the value of the offenseTimeEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setOffenseTimeEnd(XMLGregorianCalendar value) {
        this.offenseTimeEnd = value;
    }

    /**
     * Gets the value of the offenseDatesOnOrAbout property.
     * 
     */
    public boolean isOffenseDatesOnOrAbout() {
        return offenseDatesOnOrAbout;
    }

    /**
     * Sets the value of the offenseDatesOnOrAbout property.
     * 
     */
    public void setOffenseDatesOnOrAbout(boolean value) {
        this.offenseDatesOnOrAbout = value;
    }

    /**
     * Gets the value of the offenseTimesAtOrAbout property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isOffenseTimesAtOrAbout() {
        return offenseTimesAtOrAbout;
    }

    /**
     * Sets the value of the offenseTimesAtOrAbout property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOffenseTimesAtOrAbout(Boolean value) {
        this.offenseTimesAtOrAbout = value;
    }

    /**
     * Gets the value of the offenseLocationText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOffenseLocationText() {
        return offenseLocationText;
    }

    /**
     * Sets the value of the offenseLocationText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOffenseLocationText(String value) {
        this.offenseLocationText = value;
    }

    /**
     * Gets the value of the offenseOwnerText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOffenseOwnerText() {
        return offenseOwnerText;
    }

    /**
     * Sets the value of the offenseOwnerText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOffenseOwnerText(String value) {
        this.offenseOwnerText = value;
    }

    /**
     * Gets the value of the offenseTypeText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOffenseTypeText() {
        return offenseTypeText;
    }

    /**
     * Sets the value of the offenseTypeText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOffenseTypeText(String value) {
        this.offenseTypeText = value;
    }

    /**
     * Gets the value of the severityLevelText property.
     * 
     * @return
     *     possible object is
     *     {@link OffenseSeverityLevelTypeCodeTextType }
     *     
     */
    public OffenseSeverityLevelTypeCodeTextType getSeverityLevelText() {
        return severityLevelText;
    }

    /**
     * Sets the value of the severityLevelText property.
     * 
     * @param value
     *     allowed object is
     *     {@link OffenseSeverityLevelTypeCodeTextType }
     *     
     */
    public void setSeverityLevelText(OffenseSeverityLevelTypeCodeTextType value) {
        this.severityLevelText = value;
    }

    /**
     * Gets the value of the generalOffenseCodeText property.
     * 
     * @return
     *     possible object is
     *     {@link GeneralOffenseCodeTextTypeCodeTextType }
     *     
     */
    public GeneralOffenseCodeTextTypeCodeTextType getGeneralOffenseCodeText() {
        return generalOffenseCodeText;
    }

    /**
     * Sets the value of the generalOffenseCodeText property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeneralOffenseCodeTextTypeCodeTextType }
     *     
     */
    public void setGeneralOffenseCodeText(GeneralOffenseCodeTextTypeCodeTextType value) {
        this.generalOffenseCodeText = value;
    }

    /**
     * Gets the value of the minnesotaOffenseCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinnesotaOffenseCode() {
        return minnesotaOffenseCode;
    }

    /**
     * Sets the value of the minnesotaOffenseCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinnesotaOffenseCode(String value) {
        this.minnesotaOffenseCode = value;
    }

    /**
     * Gets the value of the chargeLegalDescriptionText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChargeLegalDescriptionText() {
        return chargeLegalDescriptionText;
    }

    /**
     * Sets the value of the chargeLegalDescriptionText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChargeLegalDescriptionText(String value) {
        this.chargeLegalDescriptionText = value;
    }

    /**
     * Gets the value of the predatoryOffenderRegistrationRequiredIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPredatoryOffenderRegistrationRequiredIndicator() {
        return predatoryOffenderRegistrationRequiredIndicator;
    }

    /**
     * Sets the value of the predatoryOffenderRegistrationRequiredIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPredatoryOffenderRegistrationRequiredIndicator(Boolean value) {
        this.predatoryOffenderRegistrationRequiredIndicator = value;
    }

    /**
     * Gets the value of the targetedMisdemeanorIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isTargetedMisdemeanorIndicator() {
        return targetedMisdemeanorIndicator;
    }

    /**
     * Sets the value of the targetedMisdemeanorIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTargetedMisdemeanorIndicator(Boolean value) {
        this.targetedMisdemeanorIndicator = value;
    }

    /**
     * Gets the value of the chargeStatuteSupplemental property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the chargeStatuteSupplemental property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getChargeStatuteSupplemental().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CaseGetChargeType.ChargeStatuteSupplemental }
     * 
     * 
     */
    public List<CaseGetChargeType.ChargeStatuteSupplemental> getChargeStatuteSupplemental() {
        if (chargeStatuteSupplemental == null) {
            chargeStatuteSupplemental = new ArrayList<CaseGetChargeType.ChargeStatuteSupplemental>();
        }
        return this.chargeStatuteSupplemental;
    }

    /**
     * Gets the value of the arrest property.
     * 
     * @return
     *     possible object is
     *     {@link CaseGetChargeType.Arrest }
     *     
     */
    public CaseGetChargeType.Arrest getArrest() {
        return arrest;
    }

    /**
     * Sets the value of the arrest property.
     * 
     * @param value
     *     allowed object is
     *     {@link CaseGetChargeType.Arrest }
     *     
     */
    public void setArrest(CaseGetChargeType.Arrest value) {
        this.arrest = value;
    }

    /**
     * Gets the value of the report property.
     * 
     * @return
     *     possible object is
     *     {@link CaseGetChargeType.Report }
     *     
     */
    public CaseGetChargeType.Report getReport() {
        return report;
    }

    /**
     * Sets the value of the report property.
     * 
     * @param value
     *     allowed object is
     *     {@link CaseGetChargeType.Report }
     *     
     */
    public void setReport(CaseGetChargeType.Report value) {
        this.report = value;
    }

    /**
     * Gets the value of the prosecutingAgencyORI property.
     * 
     * @return
     *     possible object is
     *     {@link ProsecutingAgencyORIType }
     *     
     */
    public ProsecutingAgencyORIType getProsecutingAgencyORI() {
        return prosecutingAgencyORI;
    }

    /**
     * Sets the value of the prosecutingAgencyORI property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProsecutingAgencyORIType }
     *     
     */
    public void setProsecutingAgencyORI(ProsecutingAgencyORIType value) {
        this.prosecutingAgencyORI = value;
    }

    /**
     * Gets the value of the communityOfOffenseText property.
     * 
     * @return
     *     possible object is
     *     {@link CommunityOfOffenseCodeTextType }
     *     
     */
    public CommunityOfOffenseCodeTextType getCommunityOfOffenseText() {
        return communityOfOffenseText;
    }

    /**
     * Sets the value of the communityOfOffenseText property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommunityOfOffenseCodeTextType }
     *     
     */
    public void setCommunityOfOffenseText(CommunityOfOffenseCodeTextType value) {
        this.communityOfOffenseText = value;
    }

    /**
     * Gets the value of the vehicle property.
     * 
     * @return
     *     possible object is
     *     {@link CaseGetVehicleType }
     *     
     */
    public CaseGetVehicleType getVehicle() {
        return vehicle;
    }

    /**
     * Sets the value of the vehicle property.
     * 
     * @param value
     *     allowed object is
     *     {@link CaseGetVehicleType }
     *     
     */
    public void setVehicle(CaseGetVehicleType value) {
        this.vehicle = value;
    }

    /**
     * Gets the value of the accidentDamageText property.
     * 
     * @return
     *     possible object is
     *     {@link CitationAccidentTypeCodeTextType }
     *     
     */
    public CitationAccidentTypeCodeTextType getAccidentDamageText() {
        return accidentDamageText;
    }

    /**
     * Sets the value of the accidentDamageText property.
     * 
     * @param value
     *     allowed object is
     *     {@link CitationAccidentTypeCodeTextType }
     *     
     */
    public void setAccidentDamageText(CitationAccidentTypeCodeTextType value) {
        this.accidentDamageText = value;
    }

    /**
     * Gets the value of the speeding property.
     * 
     * @return
     *     possible object is
     *     {@link SpeedingType }
     *     
     */
    public SpeedingType getSpeeding() {
        return speeding;
    }

    /**
     * Sets the value of the speeding property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpeedingType }
     *     
     */
    public void setSpeeding(SpeedingType value) {
        this.speeding = value;
    }

    /**
     * Gets the value of the animalsOverLimitCount property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAnimalsOverLimitCount() {
        return animalsOverLimitCount;
    }

    /**
     * Sets the value of the animalsOverLimitCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAnimalsOverLimitCount(BigInteger value) {
        this.animalsOverLimitCount = value;
    }

    /**
     * Gets the value of the vehicleOverweightMeasure property.
     * 
     * @return
     *     possible object is
     *     {@link VehicleOverweightMeasureType }
     *     
     */
    public VehicleOverweightMeasureType getVehicleOverweightMeasure() {
        return vehicleOverweightMeasure;
    }

    /**
     * Sets the value of the vehicleOverweightMeasure property.
     * 
     * @param value
     *     allowed object is
     *     {@link VehicleOverweightMeasureType }
     *     
     */
    public void setVehicleOverweightMeasure(VehicleOverweightMeasureType value) {
        this.vehicleOverweightMeasure = value;
    }

    /**
     * Gets the value of the bloodAlcoholConcentration property.
     * 
     * @return
     *     possible object is
     *     {@link BloodAlcoholConcentrationType }
     *     
     */
    public BloodAlcoholConcentrationType getBloodAlcoholConcentration() {
        return bloodAlcoholConcentration;
    }

    /**
     * Sets the value of the bloodAlcoholConcentration property.
     * 
     * @param value
     *     allowed object is
     *     {@link BloodAlcoholConcentrationType }
     *     
     */
    public void setBloodAlcoholConcentration(BloodAlcoholConcentrationType value) {
        this.bloodAlcoholConcentration = value;
    }

    /**
     * Gets the value of the reportToDPSIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isReportToDPSIndicator() {
        return reportToDPSIndicator;
    }

    /**
     * Sets the value of the reportToDPSIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setReportToDPSIndicator(Boolean value) {
        this.reportToDPSIndicator = value;
    }

    /**
     * Gets the value of the reportToDNRIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isReportToDNRIndicator() {
        return reportToDNRIndicator;
    }

    /**
     * Sets the value of the reportToDNRIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setReportToDNRIndicator(Boolean value) {
        this.reportToDNRIndicator = value;
    }

    /**
     * Gets the value of the chargeSubjectReference property.
     * 
     * @return
     *     possible object is
     *     {@link ChargeSubjectReferenceType }
     *     
     */
    public ChargeSubjectReferenceType getChargeSubjectReference() {
        return chargeSubjectReference;
    }

    /**
     * Sets the value of the chargeSubjectReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChargeSubjectReferenceType }
     *     
     */
    public void setChargeSubjectReference(ChargeSubjectReferenceType value) {
        this.chargeSubjectReference = value;
    }

    /**
     * Gets the value of the chargePlea property.
     * 
     * @return
     *     possible object is
     *     {@link PleaType }
     *     
     */
    public PleaType getChargePlea() {
        return chargePlea;
    }

    /**
     * Sets the value of the chargePlea property.
     * 
     * @param value
     *     allowed object is
     *     {@link PleaType }
     *     
     */
    public void setChargePlea(PleaType value) {
        this.chargePlea = value;
    }

    /**
     * Gets the value of the chargeAmended property.
     * 
     * @return
     *     possible object is
     *     {@link ChargeAmended }
     *     
     */
    public ChargeAmended getChargeAmended() {
        return chargeAmended;
    }

    /**
     * Sets the value of the chargeAmended property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChargeAmended }
     *     
     */
    public void setChargeAmended(ChargeAmended value) {
        this.chargeAmended = value;
    }

    /**
     * Gets the value of the trialDemand property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the trialDemand property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTrialDemand().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TrialDemand }
     * 
     * 
     */
    public List<TrialDemand> getTrialDemand() {
        if (trialDemand == null) {
            trialDemand = new ArrayList<TrialDemand>();
        }
        return this.trialDemand;
    }

    /**
     * Gets the value of the chargeKey property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getChargeKey() {
        return chargeKey;
    }

    /**
     * Sets the value of the chargeKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setChargeKey(BigInteger value) {
        this.chargeKey = value;
    }

    /**
     * Gets the value of the chargeVersionKey property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getChargeVersionKey() {
        return chargeVersionKey;
    }

    /**
     * Sets the value of the chargeVersionKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setChargeVersionKey(BigInteger value) {
        this.chargeVersionKey = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}ArrestDate" minOccurs="0"/>
     *         &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}ArrestTime" minOccurs="0"/>
     *         &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}ArrestingAgencyORI" minOccurs="0"/>
     *         &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}ArrestingAgencyControlNumber" minOccurs="0"/>
     *         &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}ArrestingOfficial" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "arrestDate",
        "arrestTime",
        "arrestingAgencyORI",
        "arrestingAgencyControlNumber",
        "arrestingOfficial"
    })
    public static class Arrest {

        @XmlElement(name = "ArrestDate")
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar arrestDate;
        @XmlElement(name = "ArrestTime")
        @XmlSchemaType(name = "time")
        protected XMLGregorianCalendar arrestTime;
        @XmlElement(name = "ArrestingAgencyORI")
        protected ArrestingAgencyCodeType arrestingAgencyORI;
        @XmlElement(name = "ArrestingAgencyControlNumber")
        protected ControlNumberType arrestingAgencyControlNumber;
        @XmlElement(name = "ArrestingOfficial")
        protected OfficerType arrestingOfficial;

        /**
         * Gets the value of the arrestDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getArrestDate() {
            return arrestDate;
        }

        /**
         * Sets the value of the arrestDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setArrestDate(XMLGregorianCalendar value) {
            this.arrestDate = value;
        }

        /**
         * Gets the value of the arrestTime property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getArrestTime() {
            return arrestTime;
        }

        /**
         * Sets the value of the arrestTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setArrestTime(XMLGregorianCalendar value) {
            this.arrestTime = value;
        }

        /**
         * Gets the value of the arrestingAgencyORI property.
         * 
         * @return
         *     possible object is
         *     {@link ArrestingAgencyCodeType }
         *     
         */
        public ArrestingAgencyCodeType getArrestingAgencyORI() {
            return arrestingAgencyORI;
        }

        /**
         * Sets the value of the arrestingAgencyORI property.
         * 
         * @param value
         *     allowed object is
         *     {@link ArrestingAgencyCodeType }
         *     
         */
        public void setArrestingAgencyORI(ArrestingAgencyCodeType value) {
            this.arrestingAgencyORI = value;
        }

        /**
         * Gets the value of the arrestingAgencyControlNumber property.
         * 
         * @return
         *     possible object is
         *     {@link ControlNumberType }
         *     
         */
        public ControlNumberType getArrestingAgencyControlNumber() {
            return arrestingAgencyControlNumber;
        }

        /**
         * Sets the value of the arrestingAgencyControlNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link ControlNumberType }
         *     
         */
        public void setArrestingAgencyControlNumber(ControlNumberType value) {
            this.arrestingAgencyControlNumber = value;
        }

        /**
         * Gets the value of the arrestingOfficial property.
         * 
         * @return
         *     possible object is
         *     {@link OfficerType }
         *     
         */
        public OfficerType getArrestingOfficial() {
            return arrestingOfficial;
        }

        /**
         * Sets the value of the arrestingOfficial property.
         * 
         * @param value
         *     allowed object is
         *     {@link OfficerType }
         *     
         */
        public void setArrestingOfficial(OfficerType value) {
            this.arrestingOfficial = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}StatuteTypeText"/>
     *         &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}OffenseID"/>
     *         &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}OffenseCite" minOccurs="0"/>
     *         &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}OffenseDescriptionText" minOccurs="0"/>
     *         &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}SeverityLevelText" minOccurs="0"/>
     *         &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}ChargeLegalDescriptionText"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "statuteTypeText",
        "offenseID",
        "offenseCite",
        "offenseDescriptionText",
        "severityLevelText",
        "chargeLegalDescriptionText"
    })
    public static class ChargeStatuteSupplemental {

        @XmlElement(name = "StatuteTypeText", required = true, nillable = true)
        protected SupplementalStatuteTypeCodeTextType statuteTypeText;
        @XmlElement(name = "OffenseID", required = true)
        protected OffenseIDType offenseID;
        @XmlElement(name = "OffenseCite")
        protected String offenseCite;
        @XmlElement(name = "OffenseDescriptionText")
        protected String offenseDescriptionText;
        @XmlElement(name = "SeverityLevelText", nillable = true)
        protected OffenseSeverityLevelTypeCodeTextType severityLevelText;
        @XmlElement(name = "ChargeLegalDescriptionText", required = true)
        protected String chargeLegalDescriptionText;

        /**
         * Gets the value of the statuteTypeText property.
         * 
         * @return
         *     possible object is
         *     {@link SupplementalStatuteTypeCodeTextType }
         *     
         */
        public SupplementalStatuteTypeCodeTextType getStatuteTypeText() {
            return statuteTypeText;
        }

        /**
         * Sets the value of the statuteTypeText property.
         * 
         * @param value
         *     allowed object is
         *     {@link SupplementalStatuteTypeCodeTextType }
         *     
         */
        public void setStatuteTypeText(SupplementalStatuteTypeCodeTextType value) {
            this.statuteTypeText = value;
        }

        /**
         * Gets the value of the offenseID property.
         * 
         * @return
         *     possible object is
         *     {@link OffenseIDType }
         *     
         */
        public OffenseIDType getOffenseID() {
            return offenseID;
        }

        /**
         * Sets the value of the offenseID property.
         * 
         * @param value
         *     allowed object is
         *     {@link OffenseIDType }
         *     
         */
        public void setOffenseID(OffenseIDType value) {
            this.offenseID = value;
        }

        /**
         * Gets the value of the offenseCite property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOffenseCite() {
            return offenseCite;
        }

        /**
         * Sets the value of the offenseCite property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOffenseCite(String value) {
            this.offenseCite = value;
        }

        /**
         * Gets the value of the offenseDescriptionText property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOffenseDescriptionText() {
            return offenseDescriptionText;
        }

        /**
         * Sets the value of the offenseDescriptionText property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOffenseDescriptionText(String value) {
            this.offenseDescriptionText = value;
        }

        /**
         * Gets the value of the severityLevelText property.
         * 
         * @return
         *     possible object is
         *     {@link OffenseSeverityLevelTypeCodeTextType }
         *     
         */
        public OffenseSeverityLevelTypeCodeTextType getSeverityLevelText() {
            return severityLevelText;
        }

        /**
         * Sets the value of the severityLevelText property.
         * 
         * @param value
         *     allowed object is
         *     {@link OffenseSeverityLevelTypeCodeTextType }
         *     
         */
        public void setSeverityLevelText(OffenseSeverityLevelTypeCodeTextType value) {
            this.severityLevelText = value;
        }

        /**
         * Gets the value of the chargeLegalDescriptionText property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getChargeLegalDescriptionText() {
            return chargeLegalDescriptionText;
        }

        /**
         * Sets the value of the chargeLegalDescriptionText property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setChargeLegalDescriptionText(String value) {
            this.chargeLegalDescriptionText = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}ReportingAgencyORI" minOccurs="0"/>
     *         &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}ReportingAgencyControlNumber" minOccurs="0"/>
     *         &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}ReportingOfficial" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "reportingAgencyORI",
        "reportingAgencyControlNumber",
        "reportingOfficial"
    })
    public static class Report {

        @XmlElement(name = "ReportingAgencyORI")
        protected ReportingAgencyCodeType reportingAgencyORI;
        @XmlElement(name = "ReportingAgencyControlNumber")
        protected ControlNumberType reportingAgencyControlNumber;
        @XmlElement(name = "ReportingOfficial")
        protected OfficerType reportingOfficial;

        /**
         * Gets the value of the reportingAgencyORI property.
         * 
         * @return
         *     possible object is
         *     {@link ReportingAgencyCodeType }
         *     
         */
        public ReportingAgencyCodeType getReportingAgencyORI() {
            return reportingAgencyORI;
        }

        /**
         * Sets the value of the reportingAgencyORI property.
         * 
         * @param value
         *     allowed object is
         *     {@link ReportingAgencyCodeType }
         *     
         */
        public void setReportingAgencyORI(ReportingAgencyCodeType value) {
            this.reportingAgencyORI = value;
        }

        /**
         * Gets the value of the reportingAgencyControlNumber property.
         * 
         * @return
         *     possible object is
         *     {@link ControlNumberType }
         *     
         */
        public ControlNumberType getReportingAgencyControlNumber() {
            return reportingAgencyControlNumber;
        }

        /**
         * Sets the value of the reportingAgencyControlNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link ControlNumberType }
         *     
         */
        public void setReportingAgencyControlNumber(ControlNumberType value) {
            this.reportingAgencyControlNumber = value;
        }

        /**
         * Gets the value of the reportingOfficial property.
         * 
         * @return
         *     possible object is
         *     {@link OfficerType }
         *     
         */
        public OfficerType getReportingOfficial() {
            return reportingOfficial;
        }

        /**
         * Sets the value of the reportingOfficial property.
         * 
         * @param value
         *     allowed object is
         *     {@link OfficerType }
         *     
         */
        public void setReportingOfficial(OfficerType value) {
            this.reportingOfficial = value;
        }

    }

}
