//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.03 at 11:31:16 PM CDT 
//


package gov.mncourts.casetget;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for CaseGetCitationDocumentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CaseGetCitationDocumentType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Filing">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}ProsecutingAgencyORI" minOccurs="0"/>
 *                   &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}CourtJurisdictionORI"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Citation">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}CitationNumber"/>
 *                   &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}OffenseDate"/>
 *                   &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}OffenseTime" minOccurs="0"/>
 *                   &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}TicketDate"/>
 *                   &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}IssuingAgencyORI"/>
 *                   &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}IssuingMethodText" minOccurs="0"/>
 *                   &lt;element name="Incident">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}WeatherConditionText" minOccurs="0"/>
 *                             &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}PropertyDamageText" minOccurs="0"/>
 *                             &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}AccidentDamageText" minOccurs="0"/>
 *                             &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}OffenseLocationText" minOccurs="0"/>
 *                             &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}OfficerBadgeNumber" minOccurs="0"/>
 *                             &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}OfficerNameText" minOccurs="0"/>
 *                             &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}ReportingAgencyControlNumber" minOccurs="0"/>
 *                             &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}CommunityOfOffenseText" minOccurs="0"/>
 *                             &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}AppearBy" minOccurs="0"/>
 *                             &lt;element name="Vehicle" type="{http://www.courts.state.mn.us/CourtXML/3}CaseGetVehicleType" minOccurs="0"/>
 *                             &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}ParkingSpace" minOccurs="0"/>
 *                             &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}OfficerCommentText" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Citee">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="PartyKey" type="{http://www.courts.state.mn.us/CourtXML/3}IntegrationIDType" minOccurs="0"/>
 *                             &lt;element name="CiteeInvolvementText" type="{http://www.courts.state.mn.us/CourtXML/3}CiteeInvolvementTypeCodeTextType"/>
 *                             &lt;element name="PartyName" type="{http://www.courts.state.mn.us/CourtXML/3}PartyNameBaseType"/>
 *                             &lt;element name="PartyAddress" type="{http://www.courts.state.mn.us/CourtXML/3}PartyAddressBaseType" minOccurs="0"/>
 *                             &lt;element name="PersonBirthDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *                             &lt;element name="PersonAssignedIDDetails" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="PersonID" type="{http://www.courts.state.mn.us/CourtXML/3}PersonIDType" minOccurs="0"/>
 *                                       &lt;element name="PersonDriverLicenseID" maxOccurs="unbounded" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;extension base="{http://www.courts.state.mn.us/CourtXML/3}PersonDriverLicenseIDType">
 *                                             &lt;/extension>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                       &lt;element name="PersonStateID" maxOccurs="unbounded" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;extension base="{http://www.courts.state.mn.us/CourtXML/3}PersonStateIDType">
 *                                             &lt;/extension>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                       &lt;element name="PersonOtherID" type="{http://www.courts.state.mn.us/CourtXML/3}PersonOtherIDType" maxOccurs="unbounded" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="PersonPhysicalDetails" type="{http://www.courts.state.mn.us/CourtXML/3}PersonPhysicalDetailsType" minOccurs="0"/>
 *                             &lt;element name="FingerPrintedIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                             &lt;element name="InCustodyIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                             &lt;element name="IdentificationMethodText" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;enumeration value="DL"/>
 *                                   &lt;enumeration value="DVS Web"/>
 *                                   &lt;enumeration value="Photo ID"/>
 *                                   &lt;enumeration value="FP"/>
 *                                   &lt;enumeration value="Other"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Charge" type="{http://www.courts.state.mn.us/CourtXML/3}CaseGetCitationChargeType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="citationKey" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CaseGetCitationDocumentType", propOrder = {
    "filing",
    "citation",
    "charge"
})
public class CaseGetCitationDocumentType {

    @XmlElement(name = "Filing", required = true)
    protected CaseGetCitationDocumentType.Filing filing;
    @XmlElement(name = "Citation", required = true)
    protected CaseGetCitationDocumentType.Citation citation;
    @XmlElement(name = "Charge", required = true)
    protected List<CaseGetCitationChargeType> charge;
    @XmlAttribute(name = "citationKey", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger citationKey;

    /**
     * Gets the value of the filing property.
     * 
     * @return
     *     possible object is
     *     {@link CaseGetCitationDocumentType.Filing }
     *     
     */
    public CaseGetCitationDocumentType.Filing getFiling() {
        return filing;
    }

    /**
     * Sets the value of the filing property.
     * 
     * @param value
     *     allowed object is
     *     {@link CaseGetCitationDocumentType.Filing }
     *     
     */
    public void setFiling(CaseGetCitationDocumentType.Filing value) {
        this.filing = value;
    }

    /**
     * Gets the value of the citation property.
     * 
     * @return
     *     possible object is
     *     {@link CaseGetCitationDocumentType.Citation }
     *     
     */
    public CaseGetCitationDocumentType.Citation getCitation() {
        return citation;
    }

    /**
     * Sets the value of the citation property.
     * 
     * @param value
     *     allowed object is
     *     {@link CaseGetCitationDocumentType.Citation }
     *     
     */
    public void setCitation(CaseGetCitationDocumentType.Citation value) {
        this.citation = value;
    }

    /**
     * Gets the value of the charge property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the charge property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCharge().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CaseGetCitationChargeType }
     * 
     * 
     */
    public List<CaseGetCitationChargeType> getCharge() {
        if (charge == null) {
            charge = new ArrayList<CaseGetCitationChargeType>();
        }
        return this.charge;
    }

    /**
     * Gets the value of the citationKey property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCitationKey() {
        return citationKey;
    }

    /**
     * Sets the value of the citationKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCitationKey(BigInteger value) {
        this.citationKey = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}CitationNumber"/>
     *         &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}OffenseDate"/>
     *         &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}OffenseTime" minOccurs="0"/>
     *         &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}TicketDate"/>
     *         &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}IssuingAgencyORI"/>
     *         &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}IssuingMethodText" minOccurs="0"/>
     *         &lt;element name="Incident">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}WeatherConditionText" minOccurs="0"/>
     *                   &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}PropertyDamageText" minOccurs="0"/>
     *                   &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}AccidentDamageText" minOccurs="0"/>
     *                   &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}OffenseLocationText" minOccurs="0"/>
     *                   &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}OfficerBadgeNumber" minOccurs="0"/>
     *                   &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}OfficerNameText" minOccurs="0"/>
     *                   &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}ReportingAgencyControlNumber" minOccurs="0"/>
     *                   &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}CommunityOfOffenseText" minOccurs="0"/>
     *                   &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}AppearBy" minOccurs="0"/>
     *                   &lt;element name="Vehicle" type="{http://www.courts.state.mn.us/CourtXML/3}CaseGetVehicleType" minOccurs="0"/>
     *                   &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}ParkingSpace" minOccurs="0"/>
     *                   &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}OfficerCommentText" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Citee">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="PartyKey" type="{http://www.courts.state.mn.us/CourtXML/3}IntegrationIDType" minOccurs="0"/>
     *                   &lt;element name="CiteeInvolvementText" type="{http://www.courts.state.mn.us/CourtXML/3}CiteeInvolvementTypeCodeTextType"/>
     *                   &lt;element name="PartyName" type="{http://www.courts.state.mn.us/CourtXML/3}PartyNameBaseType"/>
     *                   &lt;element name="PartyAddress" type="{http://www.courts.state.mn.us/CourtXML/3}PartyAddressBaseType" minOccurs="0"/>
     *                   &lt;element name="PersonBirthDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
     *                   &lt;element name="PersonAssignedIDDetails" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="PersonID" type="{http://www.courts.state.mn.us/CourtXML/3}PersonIDType" minOccurs="0"/>
     *                             &lt;element name="PersonDriverLicenseID" maxOccurs="unbounded" minOccurs="0">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;extension base="{http://www.courts.state.mn.us/CourtXML/3}PersonDriverLicenseIDType">
     *                                   &lt;/extension>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                             &lt;element name="PersonStateID" maxOccurs="unbounded" minOccurs="0">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;extension base="{http://www.courts.state.mn.us/CourtXML/3}PersonStateIDType">
     *                                   &lt;/extension>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                             &lt;element name="PersonOtherID" type="{http://www.courts.state.mn.us/CourtXML/3}PersonOtherIDType" maxOccurs="unbounded" minOccurs="0"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="PersonPhysicalDetails" type="{http://www.courts.state.mn.us/CourtXML/3}PersonPhysicalDetailsType" minOccurs="0"/>
     *                   &lt;element name="FingerPrintedIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                   &lt;element name="InCustodyIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *                   &lt;element name="IdentificationMethodText" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;enumeration value="DL"/>
     *                         &lt;enumeration value="DVS Web"/>
     *                         &lt;enumeration value="Photo ID"/>
     *                         &lt;enumeration value="FP"/>
     *                         &lt;enumeration value="Other"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "citationNumber",
        "offenseDate",
        "offenseTime",
        "ticketDate",
        "issuingAgencyORI",
        "issuingMethodText",
        "incident",
        "citee"
    })
    public static class Citation {

        @XmlElement(name = "CitationNumber", required = true)
        protected CitationNumberType citationNumber;
        @XmlElement(name = "OffenseDate", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar offenseDate;
        @XmlElement(name = "OffenseTime")
        @XmlSchemaType(name = "time")
        protected XMLGregorianCalendar offenseTime;
        @XmlElement(name = "TicketDate", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar ticketDate;
        @XmlElement(name = "IssuingAgencyORI", required = true)
        protected IssuingAgencyORIType issuingAgencyORI;
        @XmlElement(name = "IssuingMethodText", nillable = true)
        protected IssuingMethodCodeTextType issuingMethodText;
        @XmlElement(name = "Incident", required = true)
        protected CaseGetCitationDocumentType.Citation.Incident incident;
        @XmlElement(name = "Citee", required = true)
        protected CaseGetCitationDocumentType.Citation.Citee citee;

        /**
         * Gets the value of the citationNumber property.
         * 
         * @return
         *     possible object is
         *     {@link CitationNumberType }
         *     
         */
        public CitationNumberType getCitationNumber() {
            return citationNumber;
        }

        /**
         * Sets the value of the citationNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link CitationNumberType }
         *     
         */
        public void setCitationNumber(CitationNumberType value) {
            this.citationNumber = value;
        }

        /**
         * Gets the value of the offenseDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getOffenseDate() {
            return offenseDate;
        }

        /**
         * Sets the value of the offenseDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setOffenseDate(XMLGregorianCalendar value) {
            this.offenseDate = value;
        }

        /**
         * Gets the value of the offenseTime property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getOffenseTime() {
            return offenseTime;
        }

        /**
         * Sets the value of the offenseTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setOffenseTime(XMLGregorianCalendar value) {
            this.offenseTime = value;
        }

        /**
         * Gets the value of the ticketDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getTicketDate() {
            return ticketDate;
        }

        /**
         * Sets the value of the ticketDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setTicketDate(XMLGregorianCalendar value) {
            this.ticketDate = value;
        }

        /**
         * Gets the value of the issuingAgencyORI property.
         * 
         * @return
         *     possible object is
         *     {@link IssuingAgencyORIType }
         *     
         */
        public IssuingAgencyORIType getIssuingAgencyORI() {
            return issuingAgencyORI;
        }

        /**
         * Sets the value of the issuingAgencyORI property.
         * 
         * @param value
         *     allowed object is
         *     {@link IssuingAgencyORIType }
         *     
         */
        public void setIssuingAgencyORI(IssuingAgencyORIType value) {
            this.issuingAgencyORI = value;
        }

        /**
         * Gets the value of the issuingMethodText property.
         * 
         * @return
         *     possible object is
         *     {@link IssuingMethodCodeTextType }
         *     
         */
        public IssuingMethodCodeTextType getIssuingMethodText() {
            return issuingMethodText;
        }

        /**
         * Sets the value of the issuingMethodText property.
         * 
         * @param value
         *     allowed object is
         *     {@link IssuingMethodCodeTextType }
         *     
         */
        public void setIssuingMethodText(IssuingMethodCodeTextType value) {
            this.issuingMethodText = value;
        }

        /**
         * Gets the value of the incident property.
         * 
         * @return
         *     possible object is
         *     {@link CaseGetCitationDocumentType.Citation.Incident }
         *     
         */
        public CaseGetCitationDocumentType.Citation.Incident getIncident() {
            return incident;
        }

        /**
         * Sets the value of the incident property.
         * 
         * @param value
         *     allowed object is
         *     {@link CaseGetCitationDocumentType.Citation.Incident }
         *     
         */
        public void setIncident(CaseGetCitationDocumentType.Citation.Incident value) {
            this.incident = value;
        }

        /**
         * Gets the value of the citee property.
         * 
         * @return
         *     possible object is
         *     {@link CaseGetCitationDocumentType.Citation.Citee }
         *     
         */
        public CaseGetCitationDocumentType.Citation.Citee getCitee() {
            return citee;
        }

        /**
         * Sets the value of the citee property.
         * 
         * @param value
         *     allowed object is
         *     {@link CaseGetCitationDocumentType.Citation.Citee }
         *     
         */
        public void setCitee(CaseGetCitationDocumentType.Citation.Citee value) {
            this.citee = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="PartyKey" type="{http://www.courts.state.mn.us/CourtXML/3}IntegrationIDType" minOccurs="0"/>
         *         &lt;element name="CiteeInvolvementText" type="{http://www.courts.state.mn.us/CourtXML/3}CiteeInvolvementTypeCodeTextType"/>
         *         &lt;element name="PartyName" type="{http://www.courts.state.mn.us/CourtXML/3}PartyNameBaseType"/>
         *         &lt;element name="PartyAddress" type="{http://www.courts.state.mn.us/CourtXML/3}PartyAddressBaseType" minOccurs="0"/>
         *         &lt;element name="PersonBirthDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
         *         &lt;element name="PersonAssignedIDDetails" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="PersonID" type="{http://www.courts.state.mn.us/CourtXML/3}PersonIDType" minOccurs="0"/>
         *                   &lt;element name="PersonDriverLicenseID" maxOccurs="unbounded" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;extension base="{http://www.courts.state.mn.us/CourtXML/3}PersonDriverLicenseIDType">
         *                         &lt;/extension>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                   &lt;element name="PersonStateID" maxOccurs="unbounded" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;extension base="{http://www.courts.state.mn.us/CourtXML/3}PersonStateIDType">
         *                         &lt;/extension>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                   &lt;element name="PersonOtherID" type="{http://www.courts.state.mn.us/CourtXML/3}PersonOtherIDType" maxOccurs="unbounded" minOccurs="0"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="PersonPhysicalDetails" type="{http://www.courts.state.mn.us/CourtXML/3}PersonPhysicalDetailsType" minOccurs="0"/>
         *         &lt;element name="FingerPrintedIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *         &lt;element name="InCustodyIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
         *         &lt;element name="IdentificationMethodText" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;enumeration value="DL"/>
         *               &lt;enumeration value="DVS Web"/>
         *               &lt;enumeration value="Photo ID"/>
         *               &lt;enumeration value="FP"/>
         *               &lt;enumeration value="Other"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "partyKey",
            "citeeInvolvementText",
            "partyName",
            "partyAddress",
            "personBirthDate",
            "personAssignedIDDetails",
            "personPhysicalDetails",
            "fingerPrintedIndicator",
            "inCustodyIndicator",
            "identificationMethodText"
        })
        public static class Citee {

            @XmlElement(name = "PartyKey")
            protected IntegrationIDType partyKey;
            @XmlElement(name = "CiteeInvolvementText", required = true, nillable = true)
            protected CiteeInvolvementTypeCodeTextType citeeInvolvementText;
            @XmlElement(name = "PartyName", required = true)
            protected PartyNameBaseType partyName;
            @XmlElement(name = "PartyAddress")
            protected PartyAddressBaseType partyAddress;
            @XmlElement(name = "PersonBirthDate")
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar personBirthDate;
            @XmlElement(name = "PersonAssignedIDDetails")
            protected CaseGetCitationDocumentType.Citation.Citee.PersonAssignedIDDetails personAssignedIDDetails;
            @XmlElement(name = "PersonPhysicalDetails")
            protected PersonPhysicalDetailsType personPhysicalDetails;
            @XmlElement(name = "FingerPrintedIndicator")
            protected boolean fingerPrintedIndicator;
            @XmlElement(name = "InCustodyIndicator")
            protected Boolean inCustodyIndicator;
            @XmlElement(name = "IdentificationMethodText")
            protected String identificationMethodText;

            /**
             * Gets the value of the partyKey property.
             * 
             * @return
             *     possible object is
             *     {@link IntegrationIDType }
             *     
             */
            public IntegrationIDType getPartyKey() {
                return partyKey;
            }

            /**
             * Sets the value of the partyKey property.
             * 
             * @param value
             *     allowed object is
             *     {@link IntegrationIDType }
             *     
             */
            public void setPartyKey(IntegrationIDType value) {
                this.partyKey = value;
            }

            /**
             * Gets the value of the citeeInvolvementText property.
             * 
             * @return
             *     possible object is
             *     {@link CiteeInvolvementTypeCodeTextType }
             *     
             */
            public CiteeInvolvementTypeCodeTextType getCiteeInvolvementText() {
                return citeeInvolvementText;
            }

            /**
             * Sets the value of the citeeInvolvementText property.
             * 
             * @param value
             *     allowed object is
             *     {@link CiteeInvolvementTypeCodeTextType }
             *     
             */
            public void setCiteeInvolvementText(CiteeInvolvementTypeCodeTextType value) {
                this.citeeInvolvementText = value;
            }

            /**
             * Gets the value of the partyName property.
             * 
             * @return
             *     possible object is
             *     {@link PartyNameBaseType }
             *     
             */
            public PartyNameBaseType getPartyName() {
                return partyName;
            }

            /**
             * Sets the value of the partyName property.
             * 
             * @param value
             *     allowed object is
             *     {@link PartyNameBaseType }
             *     
             */
            public void setPartyName(PartyNameBaseType value) {
                this.partyName = value;
            }

            /**
             * Gets the value of the partyAddress property.
             * 
             * @return
             *     possible object is
             *     {@link PartyAddressBaseType }
             *     
             */
            public PartyAddressBaseType getPartyAddress() {
                return partyAddress;
            }

            /**
             * Sets the value of the partyAddress property.
             * 
             * @param value
             *     allowed object is
             *     {@link PartyAddressBaseType }
             *     
             */
            public void setPartyAddress(PartyAddressBaseType value) {
                this.partyAddress = value;
            }

            /**
             * Gets the value of the personBirthDate property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getPersonBirthDate() {
                return personBirthDate;
            }

            /**
             * Sets the value of the personBirthDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setPersonBirthDate(XMLGregorianCalendar value) {
                this.personBirthDate = value;
            }

            /**
             * Gets the value of the personAssignedIDDetails property.
             * 
             * @return
             *     possible object is
             *     {@link CaseGetCitationDocumentType.Citation.Citee.PersonAssignedIDDetails }
             *     
             */
            public CaseGetCitationDocumentType.Citation.Citee.PersonAssignedIDDetails getPersonAssignedIDDetails() {
                return personAssignedIDDetails;
            }

            /**
             * Sets the value of the personAssignedIDDetails property.
             * 
             * @param value
             *     allowed object is
             *     {@link CaseGetCitationDocumentType.Citation.Citee.PersonAssignedIDDetails }
             *     
             */
            public void setPersonAssignedIDDetails(CaseGetCitationDocumentType.Citation.Citee.PersonAssignedIDDetails value) {
                this.personAssignedIDDetails = value;
            }

            /**
             * Gets the value of the personPhysicalDetails property.
             * 
             * @return
             *     possible object is
             *     {@link PersonPhysicalDetailsType }
             *     
             */
            public PersonPhysicalDetailsType getPersonPhysicalDetails() {
                return personPhysicalDetails;
            }

            /**
             * Sets the value of the personPhysicalDetails property.
             * 
             * @param value
             *     allowed object is
             *     {@link PersonPhysicalDetailsType }
             *     
             */
            public void setPersonPhysicalDetails(PersonPhysicalDetailsType value) {
                this.personPhysicalDetails = value;
            }

            /**
             * Gets the value of the fingerPrintedIndicator property.
             * 
             */
            public boolean isFingerPrintedIndicator() {
                return fingerPrintedIndicator;
            }

            /**
             * Sets the value of the fingerPrintedIndicator property.
             * 
             */
            public void setFingerPrintedIndicator(boolean value) {
                this.fingerPrintedIndicator = value;
            }

            /**
             * Gets the value of the inCustodyIndicator property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isInCustodyIndicator() {
                return inCustodyIndicator;
            }

            /**
             * Sets the value of the inCustodyIndicator property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setInCustodyIndicator(Boolean value) {
                this.inCustodyIndicator = value;
            }

            /**
             * Gets the value of the identificationMethodText property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIdentificationMethodText() {
                return identificationMethodText;
            }

            /**
             * Sets the value of the identificationMethodText property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIdentificationMethodText(String value) {
                this.identificationMethodText = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="PersonID" type="{http://www.courts.state.mn.us/CourtXML/3}PersonIDType" minOccurs="0"/>
             *         &lt;element name="PersonDriverLicenseID" maxOccurs="unbounded" minOccurs="0">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;extension base="{http://www.courts.state.mn.us/CourtXML/3}PersonDriverLicenseIDType">
             *               &lt;/extension>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *         &lt;element name="PersonStateID" maxOccurs="unbounded" minOccurs="0">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;extension base="{http://www.courts.state.mn.us/CourtXML/3}PersonStateIDType">
             *               &lt;/extension>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *         &lt;element name="PersonOtherID" type="{http://www.courts.state.mn.us/CourtXML/3}PersonOtherIDType" maxOccurs="unbounded" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "personID",
                "personDriverLicenseID",
                "personStateID",
                "personOtherID"
            })
            public static class PersonAssignedIDDetails {

                @XmlElement(name = "PersonID")
                protected PersonIDType personID;
                @XmlElement(name = "PersonDriverLicenseID")
                protected List<CaseGetCitationDocumentType.Citation.Citee.PersonAssignedIDDetails.PersonDriverLicenseID> personDriverLicenseID;
                @XmlElement(name = "PersonStateID")
                protected List<CaseGetCitationDocumentType.Citation.Citee.PersonAssignedIDDetails.PersonStateID> personStateID;
                @XmlElement(name = "PersonOtherID")
                protected List<PersonOtherIDType> personOtherID;

                /**
                 * Gets the value of the personID property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link PersonIDType }
                 *     
                 */
                public PersonIDType getPersonID() {
                    return personID;
                }

                /**
                 * Sets the value of the personID property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link PersonIDType }
                 *     
                 */
                public void setPersonID(PersonIDType value) {
                    this.personID = value;
                }

                /**
                 * Gets the value of the personDriverLicenseID property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the personDriverLicenseID property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getPersonDriverLicenseID().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link CaseGetCitationDocumentType.Citation.Citee.PersonAssignedIDDetails.PersonDriverLicenseID }
                 * 
                 * 
                 */
                public List<CaseGetCitationDocumentType.Citation.Citee.PersonAssignedIDDetails.PersonDriverLicenseID> getPersonDriverLicenseID() {
                    if (personDriverLicenseID == null) {
                        personDriverLicenseID = new ArrayList<CaseGetCitationDocumentType.Citation.Citee.PersonAssignedIDDetails.PersonDriverLicenseID>();
                    }
                    return this.personDriverLicenseID;
                }

                /**
                 * Gets the value of the personStateID property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the personStateID property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getPersonStateID().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link CaseGetCitationDocumentType.Citation.Citee.PersonAssignedIDDetails.PersonStateID }
                 * 
                 * 
                 */
                public List<CaseGetCitationDocumentType.Citation.Citee.PersonAssignedIDDetails.PersonStateID> getPersonStateID() {
                    if (personStateID == null) {
                        personStateID = new ArrayList<CaseGetCitationDocumentType.Citation.Citee.PersonAssignedIDDetails.PersonStateID>();
                    }
                    return this.personStateID;
                }

                /**
                 * Gets the value of the personOtherID property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the personOtherID property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getPersonOtherID().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link PersonOtherIDType }
                 * 
                 * 
                 */
                public List<PersonOtherIDType> getPersonOtherID() {
                    if (personOtherID == null) {
                        personOtherID = new ArrayList<PersonOtherIDType>();
                    }
                    return this.personOtherID;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;extension base="{http://www.courts.state.mn.us/CourtXML/3}PersonDriverLicenseIDType">
                 *     &lt;/extension>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "")
                public static class PersonDriverLicenseID
                    extends PersonDriverLicenseIDType
                {


                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;extension base="{http://www.courts.state.mn.us/CourtXML/3}PersonStateIDType">
                 *     &lt;/extension>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "")
                public static class PersonStateID
                    extends PersonStateIDType
                {


                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}WeatherConditionText" minOccurs="0"/>
         *         &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}PropertyDamageText" minOccurs="0"/>
         *         &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}AccidentDamageText" minOccurs="0"/>
         *         &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}OffenseLocationText" minOccurs="0"/>
         *         &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}OfficerBadgeNumber" minOccurs="0"/>
         *         &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}OfficerNameText" minOccurs="0"/>
         *         &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}ReportingAgencyControlNumber" minOccurs="0"/>
         *         &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}CommunityOfOffenseText" minOccurs="0"/>
         *         &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}AppearBy" minOccurs="0"/>
         *         &lt;element name="Vehicle" type="{http://www.courts.state.mn.us/CourtXML/3}CaseGetVehicleType" minOccurs="0"/>
         *         &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}ParkingSpace" minOccurs="0"/>
         *         &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}OfficerCommentText" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "weatherConditionText",
            "propertyDamageText",
            "accidentDamageText",
            "offenseLocationText",
            "officerBadgeNumber",
            "officerNameText",
            "reportingAgencyControlNumber",
            "communityOfOffenseText",
            "appearBy",
            "vehicle",
            "parkingSpace",
            "officerCommentText"
        })
        public static class Incident {

            @XmlElement(name = "WeatherConditionText", nillable = true)
            protected WeatherConditionCodeTextType weatherConditionText;
            @XmlElement(name = "PropertyDamageText", nillable = true)
            protected PropertyDamageTypeCodeTextType propertyDamageText;
            @XmlElement(name = "AccidentDamageText", nillable = true)
            protected CitationAccidentTypeCodeTextType accidentDamageText;
            @XmlElement(name = "OffenseLocationText")
            protected String offenseLocationText;
            @XmlElement(name = "OfficerBadgeNumber")
            protected OfficerBadgeNumberType officerBadgeNumber;
            @XmlElement(name = "OfficerNameText")
            protected String officerNameText;
            @XmlElement(name = "ReportingAgencyControlNumber")
            protected ControlNumberType reportingAgencyControlNumber;
            @XmlElement(name = "CommunityOfOffenseText", nillable = true)
            protected CommunityOfOffenseCodeTextType communityOfOffenseText;
            @XmlElement(name = "AppearBy")
            protected AppearBy appearBy;
            @XmlElement(name = "Vehicle")
            protected CaseGetVehicleType vehicle;
            @XmlElement(name = "ParkingSpace")
            protected ParkingSpace parkingSpace;
            @XmlElement(name = "OfficerCommentText")
            protected String officerCommentText;

            /**
             * Gets the value of the weatherConditionText property.
             * 
             * @return
             *     possible object is
             *     {@link WeatherConditionCodeTextType }
             *     
             */
            public WeatherConditionCodeTextType getWeatherConditionText() {
                return weatherConditionText;
            }

            /**
             * Sets the value of the weatherConditionText property.
             * 
             * @param value
             *     allowed object is
             *     {@link WeatherConditionCodeTextType }
             *     
             */
            public void setWeatherConditionText(WeatherConditionCodeTextType value) {
                this.weatherConditionText = value;
            }

            /**
             * Gets the value of the propertyDamageText property.
             * 
             * @return
             *     possible object is
             *     {@link PropertyDamageTypeCodeTextType }
             *     
             */
            public PropertyDamageTypeCodeTextType getPropertyDamageText() {
                return propertyDamageText;
            }

            /**
             * Sets the value of the propertyDamageText property.
             * 
             * @param value
             *     allowed object is
             *     {@link PropertyDamageTypeCodeTextType }
             *     
             */
            public void setPropertyDamageText(PropertyDamageTypeCodeTextType value) {
                this.propertyDamageText = value;
            }

            /**
             * Gets the value of the accidentDamageText property.
             * 
             * @return
             *     possible object is
             *     {@link CitationAccidentTypeCodeTextType }
             *     
             */
            public CitationAccidentTypeCodeTextType getAccidentDamageText() {
                return accidentDamageText;
            }

            /**
             * Sets the value of the accidentDamageText property.
             * 
             * @param value
             *     allowed object is
             *     {@link CitationAccidentTypeCodeTextType }
             *     
             */
            public void setAccidentDamageText(CitationAccidentTypeCodeTextType value) {
                this.accidentDamageText = value;
            }

            /**
             * Gets the value of the offenseLocationText property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOffenseLocationText() {
                return offenseLocationText;
            }

            /**
             * Sets the value of the offenseLocationText property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOffenseLocationText(String value) {
                this.offenseLocationText = value;
            }

            /**
             * Gets the value of the officerBadgeNumber property.
             * 
             * @return
             *     possible object is
             *     {@link OfficerBadgeNumberType }
             *     
             */
            public OfficerBadgeNumberType getOfficerBadgeNumber() {
                return officerBadgeNumber;
            }

            /**
             * Sets the value of the officerBadgeNumber property.
             * 
             * @param value
             *     allowed object is
             *     {@link OfficerBadgeNumberType }
             *     
             */
            public void setOfficerBadgeNumber(OfficerBadgeNumberType value) {
                this.officerBadgeNumber = value;
            }

            /**
             * Gets the value of the officerNameText property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOfficerNameText() {
                return officerNameText;
            }

            /**
             * Sets the value of the officerNameText property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOfficerNameText(String value) {
                this.officerNameText = value;
            }

            /**
             * Gets the value of the reportingAgencyControlNumber property.
             * 
             * @return
             *     possible object is
             *     {@link ControlNumberType }
             *     
             */
            public ControlNumberType getReportingAgencyControlNumber() {
                return reportingAgencyControlNumber;
            }

            /**
             * Sets the value of the reportingAgencyControlNumber property.
             * 
             * @param value
             *     allowed object is
             *     {@link ControlNumberType }
             *     
             */
            public void setReportingAgencyControlNumber(ControlNumberType value) {
                this.reportingAgencyControlNumber = value;
            }

            /**
             * Gets the value of the communityOfOffenseText property.
             * 
             * @return
             *     possible object is
             *     {@link CommunityOfOffenseCodeTextType }
             *     
             */
            public CommunityOfOffenseCodeTextType getCommunityOfOffenseText() {
                return communityOfOffenseText;
            }

            /**
             * Sets the value of the communityOfOffenseText property.
             * 
             * @param value
             *     allowed object is
             *     {@link CommunityOfOffenseCodeTextType }
             *     
             */
            public void setCommunityOfOffenseText(CommunityOfOffenseCodeTextType value) {
                this.communityOfOffenseText = value;
            }

            /**
             * Gets the value of the appearBy property.
             * 
             * @return
             *     possible object is
             *     {@link AppearBy }
             *     
             */
            public AppearBy getAppearBy() {
                return appearBy;
            }

            /**
             * Sets the value of the appearBy property.
             * 
             * @param value
             *     allowed object is
             *     {@link AppearBy }
             *     
             */
            public void setAppearBy(AppearBy value) {
                this.appearBy = value;
            }

            /**
             * Gets the value of the vehicle property.
             * 
             * @return
             *     possible object is
             *     {@link CaseGetVehicleType }
             *     
             */
            public CaseGetVehicleType getVehicle() {
                return vehicle;
            }

            /**
             * Sets the value of the vehicle property.
             * 
             * @param value
             *     allowed object is
             *     {@link CaseGetVehicleType }
             *     
             */
            public void setVehicle(CaseGetVehicleType value) {
                this.vehicle = value;
            }

            /**
             * Gets the value of the parkingSpace property.
             * 
             * @return
             *     possible object is
             *     {@link ParkingSpace }
             *     
             */
            public ParkingSpace getParkingSpace() {
                return parkingSpace;
            }

            /**
             * Sets the value of the parkingSpace property.
             * 
             * @param value
             *     allowed object is
             *     {@link ParkingSpace }
             *     
             */
            public void setParkingSpace(ParkingSpace value) {
                this.parkingSpace = value;
            }

            /**
             * Gets the value of the officerCommentText property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOfficerCommentText() {
                return officerCommentText;
            }

            /**
             * Sets the value of the officerCommentText property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOfficerCommentText(String value) {
                this.officerCommentText = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}ProsecutingAgencyORI" minOccurs="0"/>
     *         &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}CourtJurisdictionORI"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "prosecutingAgencyORI",
        "courtJurisdictionORI"
    })
    public static class Filing {

        @XmlElement(name = "ProsecutingAgencyORI")
        protected ProsecutingAgencyORIType prosecutingAgencyORI;
        @XmlElement(name = "CourtJurisdictionORI", required = true)
        protected CourtJurisdictionORIType courtJurisdictionORI;

        /**
         * Gets the value of the prosecutingAgencyORI property.
         * 
         * @return
         *     possible object is
         *     {@link ProsecutingAgencyORIType }
         *     
         */
        public ProsecutingAgencyORIType getProsecutingAgencyORI() {
            return prosecutingAgencyORI;
        }

        /**
         * Sets the value of the prosecutingAgencyORI property.
         * 
         * @param value
         *     allowed object is
         *     {@link ProsecutingAgencyORIType }
         *     
         */
        public void setProsecutingAgencyORI(ProsecutingAgencyORIType value) {
            this.prosecutingAgencyORI = value;
        }

        /**
         * Gets the value of the courtJurisdictionORI property.
         * 
         * @return
         *     possible object is
         *     {@link CourtJurisdictionORIType }
         *     
         */
        public CourtJurisdictionORIType getCourtJurisdictionORI() {
            return courtJurisdictionORI;
        }

        /**
         * Sets the value of the courtJurisdictionORI property.
         * 
         * @param value
         *     allowed object is
         *     {@link CourtJurisdictionORIType }
         *     
         */
        public void setCourtJurisdictionORI(CourtJurisdictionORIType value) {
            this.courtJurisdictionORI = value;
        }

    }

}
