//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.03 at 11:31:16 PM CDT 
//


package gov.mncourts.casetget;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CaseDefendantType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CaseDefendantType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.courts.state.mn.us/CourtXML/3}PartyDetailType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="PersonAssignedIDDetails" type="{http://www.courts.state.mn.us/CourtXML/3}PersonAssignedIDDetailsType" minOccurs="0"/>
 *         &lt;element name="PersonPhysicalDetails" type="{http://www.courts.state.mn.us/CourtXML/3}PersonPhysicalDetailsType" minOccurs="0"/>
 *         &lt;element name="CriminalAdditionalData" type="{http://www.courts.state.mn.us/CourtXML/3}CriminalDelinquencyAdditionalDataType" minOccurs="0"/>
 *         &lt;element name="RepresentedBy" type="{http://www.courts.state.mn.us/CourtXML/3}RepresentedByType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CaseDefendantType", propOrder = {
    "personAssignedIDDetails",
    "personPhysicalDetails",
    "criminalAdditionalData",
    "representedBy"
})
public class CaseDefendantType
    extends PartyDetailType
{

    @XmlElement(name = "PersonAssignedIDDetails")
    protected PersonAssignedIDDetailsType personAssignedIDDetails;
    @XmlElement(name = "PersonPhysicalDetails")
    protected PersonPhysicalDetailsType personPhysicalDetails;
    @XmlElement(name = "CriminalAdditionalData")
    protected CriminalDelinquencyAdditionalDataType criminalAdditionalData;
    @XmlElement(name = "RepresentedBy")
    protected RepresentedByType representedBy;

    /**
     * Gets the value of the personAssignedIDDetails property.
     * 
     * @return
     *     possible object is
     *     {@link PersonAssignedIDDetailsType }
     *     
     */
    public PersonAssignedIDDetailsType getPersonAssignedIDDetails() {
        return personAssignedIDDetails;
    }

    /**
     * Sets the value of the personAssignedIDDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonAssignedIDDetailsType }
     *     
     */
    public void setPersonAssignedIDDetails(PersonAssignedIDDetailsType value) {
        this.personAssignedIDDetails = value;
    }

    /**
     * Gets the value of the personPhysicalDetails property.
     * 
     * @return
     *     possible object is
     *     {@link PersonPhysicalDetailsType }
     *     
     */
    public PersonPhysicalDetailsType getPersonPhysicalDetails() {
        return personPhysicalDetails;
    }

    /**
     * Sets the value of the personPhysicalDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonPhysicalDetailsType }
     *     
     */
    public void setPersonPhysicalDetails(PersonPhysicalDetailsType value) {
        this.personPhysicalDetails = value;
    }

    /**
     * Gets the value of the criminalAdditionalData property.
     * 
     * @return
     *     possible object is
     *     {@link CriminalDelinquencyAdditionalDataType }
     *     
     */
    public CriminalDelinquencyAdditionalDataType getCriminalAdditionalData() {
        return criminalAdditionalData;
    }

    /**
     * Sets the value of the criminalAdditionalData property.
     * 
     * @param value
     *     allowed object is
     *     {@link CriminalDelinquencyAdditionalDataType }
     *     
     */
    public void setCriminalAdditionalData(CriminalDelinquencyAdditionalDataType value) {
        this.criminalAdditionalData = value;
    }

    /**
     * Gets the value of the representedBy property.
     * 
     * @return
     *     possible object is
     *     {@link RepresentedByType }
     *     
     */
    public RepresentedByType getRepresentedBy() {
        return representedBy;
    }

    /**
     * Sets the value of the representedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link RepresentedByType }
     *     
     */
    public void setRepresentedBy(RepresentedByType value) {
        this.representedBy = value;
    }

}
