//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.03 at 11:31:16 PM CDT 
//


package gov.mncourts.casetget;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}ChargeAmendedReasonText" maxOccurs="unbounded"/>
 *         &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}ChargeAmendedDate"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "chargeAmendedReasonText",
    "chargeAmendedDate"
})
@XmlRootElement(name = "ChargeAmended")
public class ChargeAmended {

    @XmlElement(name = "ChargeAmendedReasonText", required = true, nillable = true)
    protected List<AmendmentReasonChargeTypeCodeTextType> chargeAmendedReasonText;
    @XmlElement(name = "ChargeAmendedDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar chargeAmendedDate;

    /**
     * Gets the value of the chargeAmendedReasonText property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the chargeAmendedReasonText property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getChargeAmendedReasonText().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AmendmentReasonChargeTypeCodeTextType }
     * 
     * 
     */
    public List<AmendmentReasonChargeTypeCodeTextType> getChargeAmendedReasonText() {
        if (chargeAmendedReasonText == null) {
            chargeAmendedReasonText = new ArrayList<AmendmentReasonChargeTypeCodeTextType>();
        }
        return this.chargeAmendedReasonText;
    }

    /**
     * Gets the value of the chargeAmendedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getChargeAmendedDate() {
        return chargeAmendedDate;
    }

    /**
     * Sets the value of the chargeAmendedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setChargeAmendedDate(XMLGregorianCalendar value) {
        this.chargeAmendedDate = value;
    }

}
