//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.03 at 11:31:16 PM CDT 
//


package gov.mncourts.casetget;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HearingSessionTypeTextType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="HearingSessionTypeTextType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Building"/>
 *     &lt;enumeration value="Block Time"/>
 *     &lt;enumeration value="Brookdale A"/>
 *     &lt;enumeration value="Brookdale B"/>
 *     &lt;enumeration value="County Attorney"/>
 *     &lt;enumeration value="Community Court"/>
 *     &lt;enumeration value="Drug Court 1"/>
 *     &lt;enumeration value="Drug Court 2"/>
 *     &lt;enumeration value="Domestic Violence"/>
 *     &lt;enumeration value="Felony Arraignments"/>
 *     &lt;enumeration value="Mental Health"/>
 *     &lt;enumeration value="Minneapolis Serious Traffic"/>
 *     &lt;enumeration value="Property Crimes"/>
 *     &lt;enumeration value="Ridgedale A"/>
 *     &lt;enumeration value="Ridgedale C"/>
 *     &lt;enumeration value="Southdale A"/>
 *     &lt;enumeration value="Southdale C"/>
 *     &lt;enumeration value="Assigning Judge"/>
 *     &lt;enumeration value="Anytrax"/>
 *     &lt;enumeration value="Weekend Jail Duty"/>
 *     &lt;enumeration value="Conciliation Court"/>
 *     &lt;enumeration value="Civil Trials"/>
 *     &lt;enumeration value="Chief Judge"/>
 *     &lt;enumeration value="Criminal Block"/>
 *     &lt;enumeration value="Criminal/Civil Block"/>
 *     &lt;enumeration value="Criminal Trials GC"/>
 *     &lt;enumeration value="Court Trials"/>
 *     &lt;enumeration value="Court Trials GC"/>
 *     &lt;enumeration value="Court Trials PSF"/>
 *     &lt;enumeration value="Civil Miscellaneous"/>
 *     &lt;enumeration value="Domestic Violence - GC"/>
 *     &lt;enumeration value="Drug/DWI"/>
 *     &lt;enumeration value="Drug Court"/>
 *     &lt;enumeration value="Drug Judicial Sup"/>
 *     &lt;enumeration value="DWI Judicial Sup"/>
 *     &lt;enumeration value="DWI One day Program Return"/>
 *     &lt;enumeration value="DWI Returns GC"/>
 *     &lt;enumeration value="Expungements"/>
 *     &lt;enumeration value="Expungements-No Appearance"/>
 *     &lt;enumeration value="Family"/>
 *     &lt;enumeration value="Family Court"/>
 *     &lt;enumeration value="Felony First App"/>
 *     &lt;enumeration value="Fel A Morrissey - PSF"/>
 *     &lt;enumeration value="Fel A Revo - PSF"/>
 *     &lt;enumeration value="Felony Block"/>
 *     &lt;enumeration value="Fel B Morrissey - PSF"/>
 *     &lt;enumeration value="Fel B Revo - PSF"/>
 *     &lt;enumeration value="Felony Revocations"/>
 *     &lt;enumeration value="Felony Revo GC"/>
 *     &lt;enumeration value="Felony Omnibus"/>
 *     &lt;enumeration value="Pretrials-Community"/>
 *     &lt;enumeration value="Pretrials-Serious Traffic"/>
 *     &lt;enumeration value="Harassment"/>
 *     &lt;enumeration value="Implied Consents - Division 1"/>
 *     &lt;enumeration value="Implied Consents - Suburban"/>
 *     &lt;enumeration value="Judicial Business"/>
 *     &lt;enumeration value="Juvenile Court"/>
 *     &lt;enumeration value="Juvenile Traffic"/>
 *     &lt;enumeration value="Adoption"/>
 *     &lt;enumeration value="Juvenile Block"/>
 *     &lt;enumeration value="DD/VLP"/>
 *     &lt;enumeration value="Detentions"/>
 *     &lt;enumeration value="GC EJJ"/>
 *     &lt;enumeration value="EPC"/>
 *     &lt;enumeration value="EPC Emergency"/>
 *     &lt;enumeration value="FEL/GMD/MSD Arraignments"/>
 *     &lt;enumeration value="In Custody Pretrials"/>
 *     &lt;enumeration value="ICWA EPC"/>
 *     &lt;enumeration value="LTFC"/>
 *     &lt;enumeration value="Petty Arraignments"/>
 *     &lt;enumeration value="Pretrials"/>
 *     &lt;enumeration value="Pretrials - EHM/Shelter"/>
 *     &lt;enumeration value="Runaway ADH"/>
 *     &lt;enumeration value="Status"/>
 *     &lt;enumeration value="Private TPR"/>
 *     &lt;enumeration value="Traffic Arraignments"/>
 *     &lt;enumeration value="Trials"/>
 *     &lt;enumeration value="Truancy ADH"/>
 *     &lt;enumeration value="State Ward"/>
 *     &lt;enumeration value="Evictions and Rent Escrow"/>
 *     &lt;enumeration value="Mental Health GC"/>
 *     &lt;enumeration value="Mpls Misd Payable Traffic PSF"/>
 *     &lt;enumeration value="Mpls Petty Payable Traffic PSF"/>
 *     &lt;enumeration value="Misd Pretrials GC"/>
 *     &lt;enumeration value="Morrisseys GC"/>
 *     &lt;enumeration value="Mpls ICM PSF"/>
 *     &lt;enumeration value="Mpls OCM PSF"/>
 *     &lt;enumeration value="No Judge - No Calendar"/>
 *     &lt;enumeration value="On Assignment"/>
 *     &lt;enumeration value="Other"/>
 *     &lt;enumeration value="Prop/Drug Calendar"/>
 *     &lt;enumeration value="Prop/Drug Evidence"/>
 *     &lt;enumeration value="PDC Morrissey"/>
 *     &lt;enumeration value="PDC Revocation"/>
 *     &lt;enumeration value="Prop/Drug Omnibus"/>
 *     &lt;enumeration value="PDC-Other"/>
 *     &lt;enumeration value="PDC PSF"/>
 *     &lt;enumeration value="Person Felony Morrissey"/>
 *     &lt;enumeration value="Person Felony Omnibus"/>
 *     &lt;enumeration value="Person Felony Revocation"/>
 *     &lt;enumeration value="Probate Court"/>
 *     &lt;enumeration value="Serious Traffic Arraign"/>
 *     &lt;enumeration value="Mpls Payable Pretrials"/>
 *     &lt;enumeration value="Rasmussens Misd GC"/>
 *     &lt;enumeration value="Ridgedale B"/>
 *     &lt;enumeration value="Rent"/>
 *     &lt;enumeration value="Southdale B"/>
 *     &lt;enumeration value="Signing Judge"/>
 *     &lt;enumeration value="Source Code"/>
 *     &lt;enumeration value="Special Calendar"/>
 *     &lt;enumeration value="Special Term"/>
 *     &lt;enumeration value="St. Anthony"/>
 *     &lt;enumeration value="Suburban Domestics"/>
 *     &lt;enumeration value="Mpls Payable Traffic"/>
 *     &lt;enumeration value="Housing Court"/>
 *     &lt;enumeration value="Housing Court Backup"/>
 *     &lt;enumeration value="Unavailable"/>
 *     &lt;enumeration value="Vacation"/>
 *     &lt;enumeration value="Veterans Court"/>
 *     &lt;enumeration value="Video Hearing"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "HearingSessionTypeTextType")
@XmlEnum
public enum HearingSessionTypeTextType {

    @XmlEnumValue("Building")
    BUILDING("Building"),
    @XmlEnumValue("Block Time")
    BLOCK_TIME("Block Time"),
    @XmlEnumValue("Brookdale A")
    BROOKDALE_A("Brookdale A"),
    @XmlEnumValue("Brookdale B")
    BROOKDALE_B("Brookdale B"),
    @XmlEnumValue("County Attorney")
    COUNTY_ATTORNEY("County Attorney"),
    @XmlEnumValue("Community Court")
    COMMUNITY_COURT("Community Court"),
    @XmlEnumValue("Drug Court 1")
    DRUG_COURT_1("Drug Court 1"),
    @XmlEnumValue("Drug Court 2")
    DRUG_COURT_2("Drug Court 2"),
    @XmlEnumValue("Domestic Violence")
    DOMESTIC_VIOLENCE("Domestic Violence"),
    @XmlEnumValue("Felony Arraignments")
    FELONY_ARRAIGNMENTS("Felony Arraignments"),
    @XmlEnumValue("Mental Health")
    MENTAL_HEALTH("Mental Health"),
    @XmlEnumValue("Minneapolis Serious Traffic")
    MINNEAPOLIS_SERIOUS_TRAFFIC("Minneapolis Serious Traffic"),
    @XmlEnumValue("Property Crimes")
    PROPERTY_CRIMES("Property Crimes"),
    @XmlEnumValue("Ridgedale A")
    RIDGEDALE_A("Ridgedale A"),
    @XmlEnumValue("Ridgedale C")
    RIDGEDALE_C("Ridgedale C"),
    @XmlEnumValue("Southdale A")
    SOUTHDALE_A("Southdale A"),
    @XmlEnumValue("Southdale C")
    SOUTHDALE_C("Southdale C"),
    @XmlEnumValue("Assigning Judge")
    ASSIGNING_JUDGE("Assigning Judge"),
    @XmlEnumValue("Anytrax")
    ANYTRAX("Anytrax"),
    @XmlEnumValue("Weekend Jail Duty")
    WEEKEND_JAIL_DUTY("Weekend Jail Duty"),
    @XmlEnumValue("Conciliation Court")
    CONCILIATION_COURT("Conciliation Court"),
    @XmlEnumValue("Civil Trials")
    CIVIL_TRIALS("Civil Trials"),
    @XmlEnumValue("Chief Judge")
    CHIEF_JUDGE("Chief Judge"),
    @XmlEnumValue("Criminal Block")
    CRIMINAL_BLOCK("Criminal Block"),
    @XmlEnumValue("Criminal/Civil Block")
    CRIMINAL_CIVIL_BLOCK("Criminal/Civil Block"),
    @XmlEnumValue("Criminal Trials GC")
    CRIMINAL_TRIALS_GC("Criminal Trials GC"),
    @XmlEnumValue("Court Trials")
    COURT_TRIALS("Court Trials"),
    @XmlEnumValue("Court Trials GC")
    COURT_TRIALS_GC("Court Trials GC"),
    @XmlEnumValue("Court Trials PSF")
    COURT_TRIALS_PSF("Court Trials PSF"),
    @XmlEnumValue("Civil Miscellaneous")
    CIVIL_MISCELLANEOUS("Civil Miscellaneous"),
    @XmlEnumValue("Domestic Violence - GC")
    DOMESTIC_VIOLENCE_GC("Domestic Violence - GC"),
    @XmlEnumValue("Drug/DWI")
    DRUG_DWI("Drug/DWI"),
    @XmlEnumValue("Drug Court")
    DRUG_COURT("Drug Court"),
    @XmlEnumValue("Drug Judicial Sup")
    DRUG_JUDICIAL_SUP("Drug Judicial Sup"),
    @XmlEnumValue("DWI Judicial Sup")
    DWI_JUDICIAL_SUP("DWI Judicial Sup"),
    @XmlEnumValue("DWI One day Program Return")
    DWI_ONE_DAY_PROGRAM_RETURN("DWI One day Program Return"),
    @XmlEnumValue("DWI Returns GC")
    DWI_RETURNS_GC("DWI Returns GC"),
    @XmlEnumValue("Expungements")
    EXPUNGEMENTS("Expungements"),
    @XmlEnumValue("Expungements-No Appearance")
    EXPUNGEMENTS_NO_APPEARANCE("Expungements-No Appearance"),
    @XmlEnumValue("Family")
    FAMILY("Family"),
    @XmlEnumValue("Family Court")
    FAMILY_COURT("Family Court"),
    @XmlEnumValue("Felony First App")
    FELONY_FIRST_APP("Felony First App"),
    @XmlEnumValue("Fel A Morrissey - PSF")
    FEL_A_MORRISSEY_PSF("Fel A Morrissey - PSF"),
    @XmlEnumValue("Fel A Revo - PSF")
    FEL_A_REVO_PSF("Fel A Revo - PSF"),
    @XmlEnumValue("Felony Block")
    FELONY_BLOCK("Felony Block"),
    @XmlEnumValue("Fel B Morrissey - PSF")
    FEL_B_MORRISSEY_PSF("Fel B Morrissey - PSF"),
    @XmlEnumValue("Fel B Revo - PSF")
    FEL_B_REVO_PSF("Fel B Revo - PSF"),
    @XmlEnumValue("Felony Revocations")
    FELONY_REVOCATIONS("Felony Revocations"),
    @XmlEnumValue("Felony Revo GC")
    FELONY_REVO_GC("Felony Revo GC"),
    @XmlEnumValue("Felony Omnibus")
    FELONY_OMNIBUS("Felony Omnibus"),
    @XmlEnumValue("Pretrials-Community")
    PRETRIALS_COMMUNITY("Pretrials-Community"),
    @XmlEnumValue("Pretrials-Serious Traffic")
    PRETRIALS_SERIOUS_TRAFFIC("Pretrials-Serious Traffic"),
    @XmlEnumValue("Harassment")
    HARASSMENT("Harassment"),
    @XmlEnumValue("Implied Consents - Division 1")
    IMPLIED_CONSENTS_DIVISION_1("Implied Consents - Division 1"),
    @XmlEnumValue("Implied Consents - Suburban")
    IMPLIED_CONSENTS_SUBURBAN("Implied Consents - Suburban"),
    @XmlEnumValue("Judicial Business")
    JUDICIAL_BUSINESS("Judicial Business"),
    @XmlEnumValue("Juvenile Court")
    JUVENILE_COURT("Juvenile Court"),
    @XmlEnumValue("Juvenile Traffic")
    JUVENILE_TRAFFIC("Juvenile Traffic"),
    @XmlEnumValue("Adoption")
    ADOPTION("Adoption"),
    @XmlEnumValue("Juvenile Block")
    JUVENILE_BLOCK("Juvenile Block"),
    @XmlEnumValue("DD/VLP")
    DD_VLP("DD/VLP"),
    @XmlEnumValue("Detentions")
    DETENTIONS("Detentions"),
    @XmlEnumValue("GC EJJ")
    GC_EJJ("GC EJJ"),
    EPC("EPC"),
    @XmlEnumValue("EPC Emergency")
    EPC_EMERGENCY("EPC Emergency"),
    @XmlEnumValue("FEL/GMD/MSD Arraignments")
    FEL_GMD_MSD_ARRAIGNMENTS("FEL/GMD/MSD Arraignments"),
    @XmlEnumValue("In Custody Pretrials")
    IN_CUSTODY_PRETRIALS("In Custody Pretrials"),
    @XmlEnumValue("ICWA EPC")
    ICWA_EPC("ICWA EPC"),
    LTFC("LTFC"),
    @XmlEnumValue("Petty Arraignments")
    PETTY_ARRAIGNMENTS("Petty Arraignments"),
    @XmlEnumValue("Pretrials")
    PRETRIALS("Pretrials"),
    @XmlEnumValue("Pretrials - EHM/Shelter")
    PRETRIALS_EHM_SHELTER("Pretrials - EHM/Shelter"),
    @XmlEnumValue("Runaway ADH")
    RUNAWAY_ADH("Runaway ADH"),
    @XmlEnumValue("Status")
    STATUS("Status"),
    @XmlEnumValue("Private TPR")
    PRIVATE_TPR("Private TPR"),
    @XmlEnumValue("Traffic Arraignments")
    TRAFFIC_ARRAIGNMENTS("Traffic Arraignments"),
    @XmlEnumValue("Trials")
    TRIALS("Trials"),
    @XmlEnumValue("Truancy ADH")
    TRUANCY_ADH("Truancy ADH"),
    @XmlEnumValue("State Ward")
    STATE_WARD("State Ward"),
    @XmlEnumValue("Evictions and Rent Escrow")
    EVICTIONS_AND_RENT_ESCROW("Evictions and Rent Escrow"),
    @XmlEnumValue("Mental Health GC")
    MENTAL_HEALTH_GC("Mental Health GC"),
    @XmlEnumValue("Mpls Misd Payable Traffic PSF")
    MPLS_MISD_PAYABLE_TRAFFIC_PSF("Mpls Misd Payable Traffic PSF"),
    @XmlEnumValue("Mpls Petty Payable Traffic PSF")
    MPLS_PETTY_PAYABLE_TRAFFIC_PSF("Mpls Petty Payable Traffic PSF"),
    @XmlEnumValue("Misd Pretrials GC")
    MISD_PRETRIALS_GC("Misd Pretrials GC"),
    @XmlEnumValue("Morrisseys GC")
    MORRISSEYS_GC("Morrisseys GC"),
    @XmlEnumValue("Mpls ICM PSF")
    MPLS_ICM_PSF("Mpls ICM PSF"),
    @XmlEnumValue("Mpls OCM PSF")
    MPLS_OCM_PSF("Mpls OCM PSF"),
    @XmlEnumValue("No Judge - No Calendar")
    NO_JUDGE_NO_CALENDAR("No Judge - No Calendar"),
    @XmlEnumValue("On Assignment")
    ON_ASSIGNMENT("On Assignment"),
    @XmlEnumValue("Other")
    OTHER("Other"),
    @XmlEnumValue("Prop/Drug Calendar")
    PROP_DRUG_CALENDAR("Prop/Drug Calendar"),
    @XmlEnumValue("Prop/Drug Evidence")
    PROP_DRUG_EVIDENCE("Prop/Drug Evidence"),
    @XmlEnumValue("PDC Morrissey")
    PDC_MORRISSEY("PDC Morrissey"),
    @XmlEnumValue("PDC Revocation")
    PDC_REVOCATION("PDC Revocation"),
    @XmlEnumValue("Prop/Drug Omnibus")
    PROP_DRUG_OMNIBUS("Prop/Drug Omnibus"),
    @XmlEnumValue("PDC-Other")
    PDC_OTHER("PDC-Other"),
    @XmlEnumValue("PDC PSF")
    PDC_PSF("PDC PSF"),
    @XmlEnumValue("Person Felony Morrissey")
    PERSON_FELONY_MORRISSEY("Person Felony Morrissey"),
    @XmlEnumValue("Person Felony Omnibus")
    PERSON_FELONY_OMNIBUS("Person Felony Omnibus"),
    @XmlEnumValue("Person Felony Revocation")
    PERSON_FELONY_REVOCATION("Person Felony Revocation"),
    @XmlEnumValue("Probate Court")
    PROBATE_COURT("Probate Court"),
    @XmlEnumValue("Serious Traffic Arraign")
    SERIOUS_TRAFFIC_ARRAIGN("Serious Traffic Arraign"),
    @XmlEnumValue("Mpls Payable Pretrials")
    MPLS_PAYABLE_PRETRIALS("Mpls Payable Pretrials"),
    @XmlEnumValue("Rasmussens Misd GC")
    RASMUSSENS_MISD_GC("Rasmussens Misd GC"),
    @XmlEnumValue("Ridgedale B")
    RIDGEDALE_B("Ridgedale B"),
    @XmlEnumValue("Rent")
    RENT("Rent"),
    @XmlEnumValue("Southdale B")
    SOUTHDALE_B("Southdale B"),
    @XmlEnumValue("Signing Judge")
    SIGNING_JUDGE("Signing Judge"),
    @XmlEnumValue("Source Code")
    SOURCE_CODE("Source Code"),
    @XmlEnumValue("Special Calendar")
    SPECIAL_CALENDAR("Special Calendar"),
    @XmlEnumValue("Special Term")
    SPECIAL_TERM("Special Term"),
    @XmlEnumValue("St. Anthony")
    ST_ANTHONY("St. Anthony"),
    @XmlEnumValue("Suburban Domestics")
    SUBURBAN_DOMESTICS("Suburban Domestics"),
    @XmlEnumValue("Mpls Payable Traffic")
    MPLS_PAYABLE_TRAFFIC("Mpls Payable Traffic"),
    @XmlEnumValue("Housing Court")
    HOUSING_COURT("Housing Court"),
    @XmlEnumValue("Housing Court Backup")
    HOUSING_COURT_BACKUP("Housing Court Backup"),
    @XmlEnumValue("Unavailable")
    UNAVAILABLE("Unavailable"),
    @XmlEnumValue("Vacation")
    VACATION("Vacation"),
    @XmlEnumValue("Veterans Court")
    VETERANS_COURT("Veterans Court"),
    @XmlEnumValue("Video Hearing")
    VIDEO_HEARING("Video Hearing");
    private final String value;

    HearingSessionTypeTextType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static HearingSessionTypeTextType fromValue(String v) {
        for (HearingSessionTypeTextType c: HearingSessionTypeTextType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
