//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.03 at 11:31:16 PM CDT 
//


package gov.mncourts.casetget;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for JudgmentAwardSatisfactionCostsTypeTextType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="JudgmentAwardSatisfactionCostsTypeTextType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Billed sheriff's fees"/>
 *     &lt;enumeration value="Disclosure fee"/>
 *     &lt;enumeration value="Execution fee"/>
 *     &lt;enumeration value="Manually calculated interest"/>
 *     &lt;enumeration value="Motion Fee"/>
 *     &lt;enumeration value="Order to Show Cause"/>
 *     &lt;enumeration value="Other enforcement fees"/>
 *     &lt;enumeration value="Partial satisfaction filing fee"/>
 *     &lt;enumeration value="Test Cost Code"/>
 *     &lt;enumeration value="Transcript fees"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "JudgmentAwardSatisfactionCostsTypeTextType")
@XmlEnum
public enum JudgmentAwardSatisfactionCostsTypeTextType {

    @XmlEnumValue("Billed sheriff's fees")
    BILLED_SHERIFF_S_FEES("Billed sheriff's fees"),
    @XmlEnumValue("Disclosure fee")
    DISCLOSURE_FEE("Disclosure fee"),
    @XmlEnumValue("Execution fee")
    EXECUTION_FEE("Execution fee"),
    @XmlEnumValue("Manually calculated interest")
    MANUALLY_CALCULATED_INTEREST("Manually calculated interest"),
    @XmlEnumValue("Motion Fee")
    MOTION_FEE("Motion Fee"),
    @XmlEnumValue("Order to Show Cause")
    ORDER_TO_SHOW_CAUSE("Order to Show Cause"),
    @XmlEnumValue("Other enforcement fees")
    OTHER_ENFORCEMENT_FEES("Other enforcement fees"),
    @XmlEnumValue("Partial satisfaction filing fee")
    PARTIAL_SATISFACTION_FILING_FEE("Partial satisfaction filing fee"),
    @XmlEnumValue("Test Cost Code")
    TEST_COST_CODE("Test Cost Code"),
    @XmlEnumValue("Transcript fees")
    TRANSCRIPT_FEES("Transcript fees");
    private final String value;

    JudgmentAwardSatisfactionCostsTypeTextType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static JudgmentAwardSatisfactionCostsTypeTextType fromValue(String v) {
        for (JudgmentAwardSatisfactionCostsTypeTextType c: JudgmentAwardSatisfactionCostsTypeTextType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
