//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.03 at 11:31:16 PM CDT 
//


package gov.mncourts.casetget;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Supreme Court Order required for access. Only provided under special circumstances.
 * 
 * <p>Java class for PersonRaceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PersonRaceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PartyReportedRaceText" type="{http://www.courts.state.mn.us/CourtXML/3}RaceTypeCodeTextType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="LawEnforcementObservedRaceText" type="{http://www.courts.state.mn.us/CourtXML/3}RaceTypeCodeTextType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PersonRaceType", propOrder = {
    "partyReportedRaceText",
    "lawEnforcementObservedRaceText"
})
public class PersonRaceType {

    @XmlElement(name = "PartyReportedRaceText", nillable = true)
    protected List<RaceTypeCodeTextType> partyReportedRaceText;
    @XmlElement(name = "LawEnforcementObservedRaceText", nillable = true)
    protected List<RaceTypeCodeTextType> lawEnforcementObservedRaceText;

    /**
     * Gets the value of the partyReportedRaceText property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the partyReportedRaceText property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPartyReportedRaceText().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RaceTypeCodeTextType }
     * 
     * 
     */
    public List<RaceTypeCodeTextType> getPartyReportedRaceText() {
        if (partyReportedRaceText == null) {
            partyReportedRaceText = new ArrayList<RaceTypeCodeTextType>();
        }
        return this.partyReportedRaceText;
    }

    /**
     * Gets the value of the lawEnforcementObservedRaceText property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lawEnforcementObservedRaceText property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLawEnforcementObservedRaceText().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RaceTypeCodeTextType }
     * 
     * 
     */
    public List<RaceTypeCodeTextType> getLawEnforcementObservedRaceText() {
        if (lawEnforcementObservedRaceText == null) {
            lawEnforcementObservedRaceText = new ArrayList<RaceTypeCodeTextType>();
        }
        return this.lawEnforcementObservedRaceText;
    }

}
