//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.04 at 12:20:40 AM CDT 
//


package gov.mncourts.caseget;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CaseSubTypeCodeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CaseSubTypeCodeType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="XARW"/&gt;
 *     &lt;enumeration value="ARW"/&gt;
 *     &lt;enumeration value="XAD"/&gt;
 *     &lt;enumeration value="AD"/&gt;
 *     &lt;enumeration value="ADA"/&gt;
 *     &lt;enumeration value="XADA"/&gt;
 *     &lt;enumeration value="ASB"/&gt;
 *     &lt;enumeration value="XASB"/&gt;
 *     &lt;enumeration value="ASBCNT"/&gt;
 *     &lt;enumeration value="ASBPRD"/&gt;
 *     &lt;enumeration value="ASBPRI"/&gt;
 *     &lt;enumeration value="ASBPRL"/&gt;
 *     &lt;enumeration value="ASBWRD"/&gt;
 *     &lt;enumeration value="ASBCOT"/&gt;
 *     &lt;enumeration value="XATY"/&gt;
 *     &lt;enumeration value="ATY"/&gt;
 *     &lt;enumeration value="BI"/&gt;
 *     &lt;enumeration value="XBI"/&gt;
 *     &lt;enumeration value="CLACNA"/&gt;
 *     &lt;enumeration value="CLACND"/&gt;
 *     &lt;enumeration value="CLACNT"/&gt;
 *     &lt;enumeration value="CLACOT"/&gt;
 *     &lt;enumeration value="CLADIS"/&gt;
 *     &lt;enumeration value="CLAEDO"/&gt;
 *     &lt;enumeration value="CLAEMP"/&gt;
 *     &lt;enumeration value="CLAMCL"/&gt;
 *     &lt;enumeration value="CLAMLP"/&gt;
 *     &lt;enumeration value="CLAPRD"/&gt;
 *     &lt;enumeration value="CLAPRI"/&gt;
 *     &lt;enumeration value="CLAPRL"/&gt;
 *     &lt;enumeration value="CLAREC"/&gt;
 *     &lt;enumeration value="CLASHR"/&gt;
 *     &lt;enumeration value="CLAWRD"/&gt;
 *     &lt;enumeration value="CAACV"/&gt;
 *     &lt;enumeration value="CAEGC"/&gt;
 *     &lt;enumeration value="CAGAR"/&gt;
 *     &lt;enumeration value="CAGCV"/&gt;
 *     &lt;enumeration value="CAGDC"/&gt;
 *     &lt;enumeration value="CAGDN"/&gt;
 *     &lt;enumeration value="CAMCV"/&gt;
 *     &lt;enumeration value="CASCV"/&gt;
 *     &lt;enumeration value="CASGN"/&gt;
 *     &lt;enumeration value="CMACV"/&gt;
 *     &lt;enumeration value="CMEGC"/&gt;
 *     &lt;enumeration value="CMGAR"/&gt;
 *     &lt;enumeration value="CMGCV"/&gt;
 *     &lt;enumeration value="CMGDC"/&gt;
 *     &lt;enumeration value="CMGDN"/&gt;
 *     &lt;enumeration value="CMMCV"/&gt;
 *     &lt;enumeration value="CMSCV"/&gt;
 *     &lt;enumeration value="CMSGN"/&gt;
 *     &lt;enumeration value="DEF"/&gt;
 *     &lt;enumeration value="XDEF"/&gt;
 *     &lt;enumeration value="EGACV"/&gt;
 *     &lt;enumeration value="EGEGC"/&gt;
 *     &lt;enumeration value="EGGAR"/&gt;
 *     &lt;enumeration value="EGGCV"/&gt;
 *     &lt;enumeration value="EGGDC"/&gt;
 *     &lt;enumeration value="EGGDN"/&gt;
 *     &lt;enumeration value="EGMCV"/&gt;
 *     &lt;enumeration value="EGSCV"/&gt;
 *     &lt;enumeration value="EGSGN"/&gt;
 *     &lt;enumeration value="EC"/&gt;
 *     &lt;enumeration value="XEC"/&gt;
 *     &lt;enumeration value="XEP"/&gt;
 *     &lt;enumeration value="EP"/&gt;
 *     &lt;enumeration value="GMACV"/&gt;
 *     &lt;enumeration value="GMEGC"/&gt;
 *     &lt;enumeration value="GMGAR"/&gt;
 *     &lt;enumeration value="GMGCV"/&gt;
 *     &lt;enumeration value="GMGDC"/&gt;
 *     &lt;enumeration value="GMGDN"/&gt;
 *     &lt;enumeration value="GMMCV"/&gt;
 *     &lt;enumeration value="GMSCV"/&gt;
 *     &lt;enumeration value="GMSGN"/&gt;
 *     &lt;enumeration value="GIACV"/&gt;
 *     &lt;enumeration value="GIEGC"/&gt;
 *     &lt;enumeration value="GIGAR"/&gt;
 *     &lt;enumeration value="GIGCV"/&gt;
 *     &lt;enumeration value="GIGDC"/&gt;
 *     &lt;enumeration value="GIGDN"/&gt;
 *     &lt;enumeration value="GIMCV"/&gt;
 *     &lt;enumeration value="GISCV"/&gt;
 *     &lt;enumeration value="GISGN"/&gt;
 *     &lt;enumeration value="GCACV"/&gt;
 *     &lt;enumeration value="GCEGC"/&gt;
 *     &lt;enumeration value="GCGAR"/&gt;
 *     &lt;enumeration value="GCGCV"/&gt;
 *     &lt;enumeration value="GCGDC"/&gt;
 *     &lt;enumeration value="GCGDN"/&gt;
 *     &lt;enumeration value="GCMCV"/&gt;
 *     &lt;enumeration value="GCSCV"/&gt;
 *     &lt;enumeration value="GCSGN"/&gt;
 *     &lt;enumeration value="GCMMCV"/&gt;
 *     &lt;enumeration value="GCMACV"/&gt;
 *     &lt;enumeration value="GCMEGC"/&gt;
 *     &lt;enumeration value="GCMGAR"/&gt;
 *     &lt;enumeration value="GCMGCV"/&gt;
 *     &lt;enumeration value="GCMGDC"/&gt;
 *     &lt;enumeration value="GCMGDN"/&gt;
 *     &lt;enumeration value="GCMSCV"/&gt;
 *     &lt;enumeration value="GCMSGN"/&gt;
 *     &lt;enumeration value="XIIED"/&gt;
 *     &lt;enumeration value="IIED"/&gt;
 *     &lt;enumeration value="LD"/&gt;
 *     &lt;enumeration value="XLD"/&gt;
 *     &lt;enumeration value="XMED"/&gt;
 *     &lt;enumeration value="MED"/&gt;
 *     &lt;enumeration value="XHRA"/&gt;
 *     &lt;enumeration value="HRA"/&gt;
 *     &lt;enumeration value="WBA"/&gt;
 *     &lt;enumeration value="XWBA"/&gt;
 *     &lt;enumeration value="NHSR"/&gt;
 *     &lt;enumeration value="XNHSR"/&gt;
 *     &lt;enumeration value="XNIED"/&gt;
 *     &lt;enumeration value="NIED"/&gt;
 *     &lt;enumeration value="OTR"/&gt;
 *     &lt;enumeration value="XOTR"/&gt;
 *     &lt;enumeration value="PRI"/&gt;
 *     &lt;enumeration value="PVT"/&gt;
 *     &lt;enumeration value="PRAACV"/&gt;
 *     &lt;enumeration value="PRAEGC"/&gt;
 *     &lt;enumeration value="PRAGAR"/&gt;
 *     &lt;enumeration value="PRAGCV"/&gt;
 *     &lt;enumeration value="PRAGDC"/&gt;
 *     &lt;enumeration value="PRAGDN"/&gt;
 *     &lt;enumeration value="PRAMCV"/&gt;
 *     &lt;enumeration value="PRASCV"/&gt;
 *     &lt;enumeration value="PRASGN"/&gt;
 *     &lt;enumeration value="PBL"/&gt;
 *     &lt;enumeration value="PUB"/&gt;
 *     &lt;enumeration value="XRD"/&gt;
 *     &lt;enumeration value="RD"/&gt;
 *     &lt;enumeration value="CRA"/&gt;
 *     &lt;enumeration value="XCRA"/&gt;
 *     &lt;enumeration value="XTIE"/&gt;
 *     &lt;enumeration value="TIE"/&gt;
 *     &lt;enumeration value="VIT"/&gt;
 *     &lt;enumeration value="XVIT"/&gt;
 *     &lt;enumeration value="XWD"/&gt;
 *     &lt;enumeration value="WD"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "CaseSubTypeCodeType")
@XmlEnum
public enum CaseSubTypeCodeType {

    XARW,
    ARW,
    XAD,
    AD,
    ADA,
    XADA,
    ASB,
    XASB,
    ASBCNT,
    ASBPRD,
    ASBPRI,
    ASBPRL,
    ASBWRD,
    ASBCOT,
    XATY,
    ATY,
    BI,
    XBI,
    CLACNA,
    CLACND,
    CLACNT,
    CLACOT,
    CLADIS,
    CLAEDO,
    CLAEMP,
    CLAMCL,
    CLAMLP,
    CLAPRD,
    CLAPRI,
    CLAPRL,
    CLAREC,
    CLASHR,
    CLAWRD,
    CAACV,
    CAEGC,
    CAGAR,
    CAGCV,
    CAGDC,
    CAGDN,
    CAMCV,
    CASCV,
    CASGN,
    CMACV,
    CMEGC,
    CMGAR,
    CMGCV,
    CMGDC,
    CMGDN,
    CMMCV,
    CMSCV,
    CMSGN,
    DEF,
    XDEF,
    EGACV,
    EGEGC,
    EGGAR,
    EGGCV,
    EGGDC,
    EGGDN,
    EGMCV,
    EGSCV,
    EGSGN,
    EC,
    XEC,
    XEP,
    EP,
    GMACV,
    GMEGC,
    GMGAR,
    GMGCV,
    GMGDC,
    GMGDN,
    GMMCV,
    GMSCV,
    GMSGN,
    GIACV,
    GIEGC,
    GIGAR,
    GIGCV,
    GIGDC,
    GIGDN,
    GIMCV,
    GISCV,
    GISGN,
    GCACV,
    GCEGC,
    GCGAR,
    GCGCV,
    GCGDC,
    GCGDN,
    GCMCV,
    GCSCV,
    GCSGN,
    GCMMCV,
    GCMACV,
    GCMEGC,
    GCMGAR,
    GCMGCV,
    GCMGDC,
    GCMGDN,
    GCMSCV,
    GCMSGN,
    XIIED,
    IIED,
    LD,
    XLD,
    XMED,
    MED,
    XHRA,
    HRA,
    WBA,
    XWBA,
    NHSR,
    XNHSR,
    XNIED,
    NIED,
    OTR,
    XOTR,
    PRI,
    PVT,
    PRAACV,
    PRAEGC,
    PRAGAR,
    PRAGCV,
    PRAGDC,
    PRAGDN,
    PRAMCV,
    PRASCV,
    PRASGN,
    PBL,
    PUB,
    XRD,
    RD,
    CRA,
    XCRA,
    XTIE,
    TIE,
    VIT,
    XVIT,
    XWD,
    WD;

    public String value() {
        return name();
    }

    public static CaseSubTypeCodeType fromValue(String v) {
        return valueOf(v);
    }

}
