//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.04 at 12:20:40 AM CDT 
//


package gov.mncourts.caseget;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ChildAssignedIDDetailsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ChildAssignedIDDetailsType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="PersonID" type="{}PersonIDType" minOccurs="0"/&gt;
 *         &lt;element ref="{}PersonSSNID" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{}PersonDriverLicenseID" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="PersonOtherID" type="{}PersonOtherIDType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ChildAssignedIDDetailsType", propOrder = {
    "personID",
    "personSSNID",
    "personDriverLicenseID",
    "personOtherID"
})
public class ChildAssignedIDDetailsType {

    @XmlElement(name = "PersonID")
    protected PersonIDType personID;
    @XmlElement(name = "PersonSSNID")
    protected List<PersonSSNID> personSSNID;
    @XmlElement(name = "PersonDriverLicenseID")
    protected List<PersonDriverLicenseID> personDriverLicenseID;
    @XmlElement(name = "PersonOtherID")
    protected List<PersonOtherIDType> personOtherID;

    /**
     * Gets the value of the personID property.
     * 
     * @return
     *     possible object is
     *     {@link PersonIDType }
     *     
     */
    public PersonIDType getPersonID() {
        return personID;
    }

    /**
     * Sets the value of the personID property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonIDType }
     *     
     */
    public void setPersonID(PersonIDType value) {
        this.personID = value;
    }

    /**
     * Gets the value of the personSSNID property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the personSSNID property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPersonSSNID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PersonSSNID }
     * 
     * 
     */
    public List<PersonSSNID> getPersonSSNID() {
        if (personSSNID == null) {
            personSSNID = new ArrayList<PersonSSNID>();
        }
        return this.personSSNID;
    }

    /**
     * Gets the value of the personDriverLicenseID property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the personDriverLicenseID property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPersonDriverLicenseID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PersonDriverLicenseID }
     * 
     * 
     */
    public List<PersonDriverLicenseID> getPersonDriverLicenseID() {
        if (personDriverLicenseID == null) {
            personDriverLicenseID = new ArrayList<PersonDriverLicenseID>();
        }
        return this.personDriverLicenseID;
    }

    /**
     * Gets the value of the personOtherID property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the personOtherID property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPersonOtherID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PersonOtherIDType }
     * 
     * 
     */
    public List<PersonOtherIDType> getPersonOtherID() {
        if (personOtherID == null) {
            personOtherID = new ArrayList<PersonOtherIDType>();
        }
        return this.personOtherID;
    }

}
