//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.04 at 12:20:40 AM CDT 
//


package gov.mncourts.caseget;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CitationAccidentType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CitationAccidentType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Fatal"/&gt;
 *     &lt;enumeration value="No injury or property damage"/&gt;
 *     &lt;enumeration value="None"/&gt;
 *     &lt;enumeration value="Pedestrian"/&gt;
 *     &lt;enumeration value="Personal injury"/&gt;
 *     &lt;enumeration value="Property Damage"/&gt;
 *     &lt;enumeration value="Substantial Bodily Harm"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "CitationAccidentType")
@XmlEnum
public enum CitationAccidentType {

    @XmlEnumValue("Fatal")
    FATAL("Fatal"),
    @XmlEnumValue("No injury or property damage")
    NO_INJURY_OR_PROPERTY_DAMAGE("No injury or property damage"),
    @XmlEnumValue("None")
    NONE("None"),
    @XmlEnumValue("Pedestrian")
    PEDESTRIAN("Pedestrian"),
    @XmlEnumValue("Personal injury")
    PERSONAL_INJURY("Personal injury"),
    @XmlEnumValue("Property Damage")
    PROPERTY_DAMAGE("Property Damage"),
    @XmlEnumValue("Substantial Bodily Harm")
    SUBSTANTIAL_BODILY_HARM("Substantial Bodily Harm");
    private final String value;

    CitationAccidentType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CitationAccidentType fromValue(String v) {
        for (CitationAccidentType c: CitationAccidentType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
