//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.04 at 12:20:40 AM CDT 
//


package gov.mncourts.caseget;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CiteeInvolvementTypeCodeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CiteeInvolvementTypeCodeType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="CI"/&gt;
 *     &lt;enumeration value="CNVNIALW"/&gt;
 *     &lt;enumeration value="CNVNIOP"/&gt;
 *     &lt;enumeration value="CNVNIPRK"/&gt;
 *     &lt;enumeration value="CNVCITEE"/&gt;
 *     &lt;enumeration value="DR"/&gt;
 *     &lt;enumeration value="LE"/&gt;
 *     &lt;enumeration value="OP"/&gt;
 *     &lt;enumeration value="OT"/&gt;
 *     &lt;enumeration value="OW"/&gt;
 *     &lt;enumeration value="PASS"/&gt;
 *     &lt;enumeration value="TESTINVOL"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "CiteeInvolvementTypeCodeType")
@XmlEnum
public enum CiteeInvolvementTypeCodeType {

    CI,
    CNVNIALW,
    CNVNIOP,
    CNVNIPRK,
    CNVCITEE,
    DR,
    LE,
    OP,
    OT,
    OW,
    PASS,
    TESTINVOL;

    public String value() {
        return name();
    }

    public static CiteeInvolvementTypeCodeType fromValue(String v) {
        return valueOf(v);
    }

}
