//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.04 at 12:20:40 AM CDT 
//


package gov.mncourts.caseget;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CourtCaseHeaderType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CourtCaseHeaderType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{}CaseHeaderType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CaseAssignment" type="{}CaseAssignmentType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="CaseFlag" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="CaseFlagText" type="{}CaseIndicatorTypeCodeTextType"/&gt;
 *                   &lt;element name="CaseFlagComment" type="{}CommentType" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="RelatedCase" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element ref="{}CourtFileNumber"/&gt;
 *                   &lt;element name="RelatedCaseReasonText" type="{}RelatedCaseReasonCodeTextType"/&gt;
 *                   &lt;element name="RelatedCaseReasonComment" type="{}CommentType" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CourtCaseHeaderType", propOrder = {
    "caseAssignment",
    "caseFlag",
    "relatedCase"
})
@XmlSeeAlso({
    CourtCaseHeaderGroupType.class
})
public class CourtCaseHeaderType
    extends CaseHeaderType
{

    @XmlElement(name = "CaseAssignment")
    protected List<CaseAssignmentType> caseAssignment;
    @XmlElement(name = "CaseFlag")
    protected List<CourtCaseHeaderType.CaseFlag> caseFlag;
    @XmlElement(name = "RelatedCase")
    protected List<CourtCaseHeaderType.RelatedCase> relatedCase;

    /**
     * Gets the value of the caseAssignment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the caseAssignment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCaseAssignment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CaseAssignmentType }
     * 
     * 
     */
    public List<CaseAssignmentType> getCaseAssignment() {
        if (caseAssignment == null) {
            caseAssignment = new ArrayList<CaseAssignmentType>();
        }
        return this.caseAssignment;
    }

    /**
     * Gets the value of the caseFlag property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the caseFlag property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCaseFlag().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CourtCaseHeaderType.CaseFlag }
     * 
     * 
     */
    public List<CourtCaseHeaderType.CaseFlag> getCaseFlag() {
        if (caseFlag == null) {
            caseFlag = new ArrayList<CourtCaseHeaderType.CaseFlag>();
        }
        return this.caseFlag;
    }

    /**
     * Gets the value of the relatedCase property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relatedCase property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelatedCase().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CourtCaseHeaderType.RelatedCase }
     * 
     * 
     */
    public List<CourtCaseHeaderType.RelatedCase> getRelatedCase() {
        if (relatedCase == null) {
            relatedCase = new ArrayList<CourtCaseHeaderType.RelatedCase>();
        }
        return this.relatedCase;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="CaseFlagText" type="{}CaseIndicatorTypeCodeTextType"/&gt;
     *         &lt;element name="CaseFlagComment" type="{}CommentType" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "caseFlagText",
        "caseFlagComment"
    })
    public static class CaseFlag {

        @XmlElement(name = "CaseFlagText", required = true)
        protected CaseIndicatorTypeCodeTextType caseFlagText;
        @XmlElement(name = "CaseFlagComment")
        protected String caseFlagComment;

        /**
         * Gets the value of the caseFlagText property.
         * 
         * @return
         *     possible object is
         *     {@link CaseIndicatorTypeCodeTextType }
         *     
         */
        public CaseIndicatorTypeCodeTextType getCaseFlagText() {
            return caseFlagText;
        }

        /**
         * Sets the value of the caseFlagText property.
         * 
         * @param value
         *     allowed object is
         *     {@link CaseIndicatorTypeCodeTextType }
         *     
         */
        public void setCaseFlagText(CaseIndicatorTypeCodeTextType value) {
            this.caseFlagText = value;
        }

        /**
         * Gets the value of the caseFlagComment property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCaseFlagComment() {
            return caseFlagComment;
        }

        /**
         * Sets the value of the caseFlagComment property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCaseFlagComment(String value) {
            this.caseFlagComment = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element ref="{}CourtFileNumber"/&gt;
     *         &lt;element name="RelatedCaseReasonText" type="{}RelatedCaseReasonCodeTextType"/&gt;
     *         &lt;element name="RelatedCaseReasonComment" type="{}CommentType" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "courtFileNumber",
        "relatedCaseReasonText",
        "relatedCaseReasonComment"
    })
    public static class RelatedCase {

        @XmlElement(name = "CourtFileNumber", required = true)
        protected CourtFileNumberType courtFileNumber;
        @XmlElement(name = "RelatedCaseReasonText", required = true)
        protected RelatedCaseReasonCodeTextType relatedCaseReasonText;
        @XmlElement(name = "RelatedCaseReasonComment")
        protected String relatedCaseReasonComment;

        /**
         * Gets the value of the courtFileNumber property.
         * 
         * @return
         *     possible object is
         *     {@link CourtFileNumberType }
         *     
         */
        public CourtFileNumberType getCourtFileNumber() {
            return courtFileNumber;
        }

        /**
         * Sets the value of the courtFileNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link CourtFileNumberType }
         *     
         */
        public void setCourtFileNumber(CourtFileNumberType value) {
            this.courtFileNumber = value;
        }

        /**
         * Gets the value of the relatedCaseReasonText property.
         * 
         * @return
         *     possible object is
         *     {@link RelatedCaseReasonCodeTextType }
         *     
         */
        public RelatedCaseReasonCodeTextType getRelatedCaseReasonText() {
            return relatedCaseReasonText;
        }

        /**
         * Sets the value of the relatedCaseReasonText property.
         * 
         * @param value
         *     allowed object is
         *     {@link RelatedCaseReasonCodeTextType }
         *     
         */
        public void setRelatedCaseReasonText(RelatedCaseReasonCodeTextType value) {
            this.relatedCaseReasonText = value;
        }

        /**
         * Gets the value of the relatedCaseReasonComment property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRelatedCaseReasonComment() {
            return relatedCaseReasonComment;
        }

        /**
         * Sets the value of the relatedCaseReasonComment property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRelatedCaseReasonComment(String value) {
            this.relatedCaseReasonComment = value;
        }

    }

}
