//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.04 at 12:20:40 AM CDT 
//


package gov.mncourts.caseget;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DriverLicenseStateType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DriverLicenseStateType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="AA"/&gt;
 *     &lt;enumeration value="AE"/&gt;
 *     &lt;enumeration value="AK"/&gt;
 *     &lt;enumeration value="AL"/&gt;
 *     &lt;enumeration value="AP"/&gt;
 *     &lt;enumeration value="AR"/&gt;
 *     &lt;enumeration value="AS"/&gt;
 *     &lt;enumeration value="AZ"/&gt;
 *     &lt;enumeration value="CA"/&gt;
 *     &lt;enumeration value="CDAB"/&gt;
 *     &lt;enumeration value="CDBC"/&gt;
 *     &lt;enumeration value="CDMB"/&gt;
 *     &lt;enumeration value="CDNF"/&gt;
 *     &lt;enumeration value="CDNK"/&gt;
 *     &lt;enumeration value="CDNS"/&gt;
 *     &lt;enumeration value="CDNT"/&gt;
 *     &lt;enumeration value="CDNU"/&gt;
 *     &lt;enumeration value="CDON"/&gt;
 *     &lt;enumeration value="CDPE"/&gt;
 *     &lt;enumeration value="CDPQ"/&gt;
 *     &lt;enumeration value="CDSN"/&gt;
 *     &lt;enumeration value="CDU"/&gt;
 *     &lt;enumeration value="CDYT"/&gt;
 *     &lt;enumeration value="CO"/&gt;
 *     &lt;enumeration value="CT"/&gt;
 *     &lt;enumeration value="CZ"/&gt;
 *     &lt;enumeration value="DC"/&gt;
 *     &lt;enumeration value="DE"/&gt;
 *     &lt;enumeration value="DEN"/&gt;
 *     &lt;enumeration value="EL"/&gt;
 *     &lt;enumeration value="FL"/&gt;
 *     &lt;enumeration value="FM"/&gt;
 *     &lt;enumeration value="GA"/&gt;
 *     &lt;enumeration value="GRMY"/&gt;
 *     &lt;enumeration value="GU"/&gt;
 *     &lt;enumeration value="HI"/&gt;
 *     &lt;enumeration value="IA"/&gt;
 *     &lt;enumeration value="ID"/&gt;
 *     &lt;enumeration value="IL"/&gt;
 *     &lt;enumeration value="IN"/&gt;
 *     &lt;enumeration value="INBS"/&gt;
 *     &lt;enumeration value="INTDL"/&gt;
 *     &lt;enumeration value="IT"/&gt;
 *     &lt;enumeration value="KS"/&gt;
 *     &lt;enumeration value="KY"/&gt;
 *     &lt;enumeration value="LA"/&gt;
 *     &lt;enumeration value="MA"/&gt;
 *     &lt;enumeration value="MD"/&gt;
 *     &lt;enumeration value="ME"/&gt;
 *     &lt;enumeration value="MH"/&gt;
 *     &lt;enumeration value="MI"/&gt;
 *     &lt;enumeration value="MM"/&gt;
 *     &lt;enumeration value="MN"/&gt;
 *     &lt;enumeration value="MO"/&gt;
 *     &lt;enumeration value="MP"/&gt;
 *     &lt;enumeration value="MS"/&gt;
 *     &lt;enumeration value="MT"/&gt;
 *     &lt;enumeration value="MY"/&gt;
 *     &lt;enumeration value="NC"/&gt;
 *     &lt;enumeration value="ND"/&gt;
 *     &lt;enumeration value="NE"/&gt;
 *     &lt;enumeration value="NH"/&gt;
 *     &lt;enumeration value="NJ"/&gt;
 *     &lt;enumeration value="NM"/&gt;
 *     &lt;enumeration value="NV"/&gt;
 *     &lt;enumeration value="NY"/&gt;
 *     &lt;enumeration value="OH"/&gt;
 *     &lt;enumeration value="OK"/&gt;
 *     &lt;enumeration value="OR"/&gt;
 *     &lt;enumeration value="PA"/&gt;
 *     &lt;enumeration value="PR"/&gt;
 *     &lt;enumeration value="RI"/&gt;
 *     &lt;enumeration value="SC"/&gt;
 *     &lt;enumeration value="SD"/&gt;
 *     &lt;enumeration value="TN"/&gt;
 *     &lt;enumeration value="TX"/&gt;
 *     &lt;enumeration value="UK"/&gt;
 *     &lt;enumeration value="US"/&gt;
 *     &lt;enumeration value="UT"/&gt;
 *     &lt;enumeration value="VA"/&gt;
 *     &lt;enumeration value="VI"/&gt;
 *     &lt;enumeration value="VT"/&gt;
 *     &lt;enumeration value="WA"/&gt;
 *     &lt;enumeration value="WI"/&gt;
 *     &lt;enumeration value="WV"/&gt;
 *     &lt;enumeration value="WY"/&gt;
 *     &lt;enumeration value="YY"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "DriverLicenseStateType")
@XmlEnum
public enum DriverLicenseStateType {

    AA,
    AE,
    AK,
    AL,
    AP,
    AR,
    AS,
    AZ,
    CA,
    CDAB,
    CDBC,
    CDMB,
    CDNF,
    CDNK,
    CDNS,
    CDNT,
    CDNU,
    CDON,
    CDPE,
    CDPQ,
    CDSN,
    CDU,
    CDYT,
    CO,
    CT,
    CZ,
    DC,
    DE,
    DEN,
    EL,
    FL,
    FM,
    GA,
    GRMY,
    GU,
    HI,
    IA,
    ID,
    IL,
    IN,
    INBS,
    INTDL,
    IT,
    KS,
    KY,
    LA,
    MA,
    MD,
    ME,
    MH,
    MI,
    MM,
    MN,
    MO,
    MP,
    MS,
    MT,
    MY,
    NC,
    ND,
    NE,
    NH,
    NJ,
    NM,
    NV,
    NY,
    OH,
    OK,
    OR,
    PA,
    PR,
    RI,
    SC,
    SD,
    TN,
    TX,
    UK,
    US,
    UT,
    VA,
    VI,
    VT,
    WA,
    WI,
    WV,
    WY,
    YY;

    public String value() {
        return name();
    }

    public static DriverLicenseStateType fromValue(String v) {
        return valueOf(v);
    }

}
