//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.04 at 12:20:40 AM CDT 
//


package gov.mncourts.caseget;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for JudgmentAwardSatisfactionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="JudgmentAwardSatisfactionType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="SatisfactionTypeText" type="{}JudgmentAwardSatisfactionTypeCodeTextType"/&gt;
 *         &lt;element name="DocumentTypeText" type="{}JudgmentAwardSatisfactionDocumentTypeCodeTextType"/&gt;
 *         &lt;element name="CollectionDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="CollectedAmounts" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="TotalCollectedAmount" type="{}CurrencyType" minOccurs="0"/&gt;
 *                   &lt;element name="PrincipalCollectedAmount" type="{}CurrencyType" minOccurs="0"/&gt;
 *                   &lt;element name="CostsCollectedAmount" type="{}CurrencyType" minOccurs="0"/&gt;
 *                   &lt;element name="InterestCollectedAmount" type="{}CurrencyType" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="IncurredCosts" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="CostTypeText" type="{}JudgmentAwardSatisfactionCostsTypeCodeTextType"/&gt;
 *                   &lt;element name="CostDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *                   &lt;element name="Amount" type="{}CurrencyType"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="writOfExecutionKey" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "JudgmentAwardSatisfactionType", propOrder = {
    "satisfactionTypeText",
    "documentTypeText",
    "collectionDate",
    "collectedAmounts",
    "incurredCosts"
})
public class JudgmentAwardSatisfactionType {

    @XmlElement(name = "SatisfactionTypeText", required = true)
    protected JudgmentAwardSatisfactionTypeCodeTextType satisfactionTypeText;
    @XmlElement(name = "DocumentTypeText", required = true)
    protected JudgmentAwardSatisfactionDocumentTypeCodeTextType documentTypeText;
    @XmlElement(name = "CollectionDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar collectionDate;
    @XmlElement(name = "CollectedAmounts")
    protected JudgmentAwardSatisfactionType.CollectedAmounts collectedAmounts;
    @XmlElement(name = "IncurredCosts")
    protected List<JudgmentAwardSatisfactionType.IncurredCosts> incurredCosts;
    @XmlAttribute(name = "writOfExecutionKey")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger writOfExecutionKey;

    /**
     * Gets the value of the satisfactionTypeText property.
     * 
     * @return
     *     possible object is
     *     {@link JudgmentAwardSatisfactionTypeCodeTextType }
     *     
     */
    public JudgmentAwardSatisfactionTypeCodeTextType getSatisfactionTypeText() {
        return satisfactionTypeText;
    }

    /**
     * Sets the value of the satisfactionTypeText property.
     * 
     * @param value
     *     allowed object is
     *     {@link JudgmentAwardSatisfactionTypeCodeTextType }
     *     
     */
    public void setSatisfactionTypeText(JudgmentAwardSatisfactionTypeCodeTextType value) {
        this.satisfactionTypeText = value;
    }

    /**
     * Gets the value of the documentTypeText property.
     * 
     * @return
     *     possible object is
     *     {@link JudgmentAwardSatisfactionDocumentTypeCodeTextType }
     *     
     */
    public JudgmentAwardSatisfactionDocumentTypeCodeTextType getDocumentTypeText() {
        return documentTypeText;
    }

    /**
     * Sets the value of the documentTypeText property.
     * 
     * @param value
     *     allowed object is
     *     {@link JudgmentAwardSatisfactionDocumentTypeCodeTextType }
     *     
     */
    public void setDocumentTypeText(JudgmentAwardSatisfactionDocumentTypeCodeTextType value) {
        this.documentTypeText = value;
    }

    /**
     * Gets the value of the collectionDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCollectionDate() {
        return collectionDate;
    }

    /**
     * Sets the value of the collectionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCollectionDate(XMLGregorianCalendar value) {
        this.collectionDate = value;
    }

    /**
     * Gets the value of the collectedAmounts property.
     * 
     * @return
     *     possible object is
     *     {@link JudgmentAwardSatisfactionType.CollectedAmounts }
     *     
     */
    public JudgmentAwardSatisfactionType.CollectedAmounts getCollectedAmounts() {
        return collectedAmounts;
    }

    /**
     * Sets the value of the collectedAmounts property.
     * 
     * @param value
     *     allowed object is
     *     {@link JudgmentAwardSatisfactionType.CollectedAmounts }
     *     
     */
    public void setCollectedAmounts(JudgmentAwardSatisfactionType.CollectedAmounts value) {
        this.collectedAmounts = value;
    }

    /**
     * Gets the value of the incurredCosts property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the incurredCosts property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIncurredCosts().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JudgmentAwardSatisfactionType.IncurredCosts }
     * 
     * 
     */
    public List<JudgmentAwardSatisfactionType.IncurredCosts> getIncurredCosts() {
        if (incurredCosts == null) {
            incurredCosts = new ArrayList<JudgmentAwardSatisfactionType.IncurredCosts>();
        }
        return this.incurredCosts;
    }

    /**
     * Gets the value of the writOfExecutionKey property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getWritOfExecutionKey() {
        return writOfExecutionKey;
    }

    /**
     * Sets the value of the writOfExecutionKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setWritOfExecutionKey(BigInteger value) {
        this.writOfExecutionKey = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="TotalCollectedAmount" type="{}CurrencyType" minOccurs="0"/&gt;
     *         &lt;element name="PrincipalCollectedAmount" type="{}CurrencyType" minOccurs="0"/&gt;
     *         &lt;element name="CostsCollectedAmount" type="{}CurrencyType" minOccurs="0"/&gt;
     *         &lt;element name="InterestCollectedAmount" type="{}CurrencyType" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "totalCollectedAmount",
        "principalCollectedAmount",
        "costsCollectedAmount",
        "interestCollectedAmount"
    })
    public static class CollectedAmounts {

        @XmlElement(name = "TotalCollectedAmount")
        protected Double totalCollectedAmount;
        @XmlElement(name = "PrincipalCollectedAmount")
        protected Double principalCollectedAmount;
        @XmlElement(name = "CostsCollectedAmount")
        protected Double costsCollectedAmount;
        @XmlElement(name = "InterestCollectedAmount")
        protected Double interestCollectedAmount;

        /**
         * Gets the value of the totalCollectedAmount property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getTotalCollectedAmount() {
            return totalCollectedAmount;
        }

        /**
         * Sets the value of the totalCollectedAmount property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setTotalCollectedAmount(Double value) {
            this.totalCollectedAmount = value;
        }

        /**
         * Gets the value of the principalCollectedAmount property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getPrincipalCollectedAmount() {
            return principalCollectedAmount;
        }

        /**
         * Sets the value of the principalCollectedAmount property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setPrincipalCollectedAmount(Double value) {
            this.principalCollectedAmount = value;
        }

        /**
         * Gets the value of the costsCollectedAmount property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getCostsCollectedAmount() {
            return costsCollectedAmount;
        }

        /**
         * Sets the value of the costsCollectedAmount property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setCostsCollectedAmount(Double value) {
            this.costsCollectedAmount = value;
        }

        /**
         * Gets the value of the interestCollectedAmount property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getInterestCollectedAmount() {
            return interestCollectedAmount;
        }

        /**
         * Sets the value of the interestCollectedAmount property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setInterestCollectedAmount(Double value) {
            this.interestCollectedAmount = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="CostTypeText" type="{}JudgmentAwardSatisfactionCostsTypeCodeTextType"/&gt;
     *         &lt;element name="CostDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
     *         &lt;element name="Amount" type="{}CurrencyType"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "costTypeText",
        "costDate",
        "amount"
    })
    public static class IncurredCosts {

        @XmlElement(name = "CostTypeText", required = true)
        protected JudgmentAwardSatisfactionCostsTypeCodeTextType costTypeText;
        @XmlElement(name = "CostDate", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar costDate;
        @XmlElement(name = "Amount")
        protected double amount;

        /**
         * Gets the value of the costTypeText property.
         * 
         * @return
         *     possible object is
         *     {@link JudgmentAwardSatisfactionCostsTypeCodeTextType }
         *     
         */
        public JudgmentAwardSatisfactionCostsTypeCodeTextType getCostTypeText() {
            return costTypeText;
        }

        /**
         * Sets the value of the costTypeText property.
         * 
         * @param value
         *     allowed object is
         *     {@link JudgmentAwardSatisfactionCostsTypeCodeTextType }
         *     
         */
        public void setCostTypeText(JudgmentAwardSatisfactionCostsTypeCodeTextType value) {
            this.costTypeText = value;
        }

        /**
         * Gets the value of the costDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getCostDate() {
            return costDate;
        }

        /**
         * Sets the value of the costDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setCostDate(XMLGregorianCalendar value) {
            this.costDate = value;
        }

        /**
         * Gets the value of the amount property.
         * 
         */
        public double getAmount() {
            return amount;
        }

        /**
         * Sets the value of the amount property.
         * 
         */
        public void setAmount(double value) {
            this.amount = value;
        }

    }

}
