//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.04 at 12:20:40 AM CDT 
//


package gov.mncourts.caseget;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for JudgmentAwardSatisfactionCostsTypeCodeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="JudgmentAwardSatisfactionCostsTypeCodeType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="SHER"/&gt;
 *     &lt;enumeration value="ORDDISC"/&gt;
 *     &lt;enumeration value="EXEC"/&gt;
 *     &lt;enumeration value="MINT"/&gt;
 *     &lt;enumeration value="MOT"/&gt;
 *     &lt;enumeration value="ORDSC"/&gt;
 *     &lt;enumeration value="OTH"/&gt;
 *     &lt;enumeration value="PART"/&gt;
 *     &lt;enumeration value="TESTCOST"/&gt;
 *     &lt;enumeration value="TRANS"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "JudgmentAwardSatisfactionCostsTypeCodeType")
@XmlEnum
public enum JudgmentAwardSatisfactionCostsTypeCodeType {

    SHER,
    ORDDISC,
    EXEC,
    MINT,
    MOT,
    ORDSC,
    OTH,
    PART,
    TESTCOST,
    TRANS;

    public String value() {
        return name();
    }

    public static JudgmentAwardSatisfactionCostsTypeCodeType fromValue(String v) {
        return valueOf(v);
    }

}
