//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.04 at 12:20:40 AM CDT 
//


package gov.mncourts.caseget;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for JudgmentComponentValueType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="JudgmentComponentValueType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="ConversionCost"/&gt;
 *     &lt;enumeration value="ConversionDate"/&gt;
 *     &lt;enumeration value="ConversionInterest"/&gt;
 *     &lt;enumeration value="ConversionPrincipal"/&gt;
 *     &lt;enumeration value="TEXT"/&gt;
 *     &lt;enumeration value="cboCUSTType"/&gt;
 *     &lt;enumeration value="cboJUDawardReason"/&gt;
 *     &lt;enumeration value="cboJUDintRateType"/&gt;
 *     &lt;enumeration value="cboPLCMTLocation"/&gt;
 *     &lt;enumeration value="cboPLCMTType"/&gt;
 *     &lt;enumeration value="cboPROPType"/&gt;
 *     &lt;enumeration value="cboREIMBType"/&gt;
 *     &lt;enumeration value="cboSUPPAmtFreq"/&gt;
 *     &lt;enumeration value="cboSUPPMethod"/&gt;
 *     &lt;enumeration value="cboSUPPMethodFreq"/&gt;
 *     &lt;enumeration value="cboSUPPType"/&gt;
 *     &lt;enumeration value="cboVISITType"/&gt;
 *     &lt;enumeration value="dbCMTMTEndDate"/&gt;
 *     &lt;enumeration value="dbCMTMTReportDate"/&gt;
 *     &lt;enumeration value="dbCMTMTStartDate"/&gt;
 *     &lt;enumeration value="dbJUDdateDocketed"/&gt;
 *     &lt;enumeration value="dbJUDdateEntered"/&gt;
 *     &lt;enumeration value="dbJUDdateExpires"/&gt;
 *     &lt;enumeration value="dbJUDdateInactive"/&gt;
 *     &lt;enumeration value="dbJUDtimeDocketed"/&gt;
 *     &lt;enumeration value="dbPLCMTEndDate"/&gt;
 *     &lt;enumeration value="dbPLCMTStartDate"/&gt;
 *     &lt;enumeration value="dbPROPRecordedDate"/&gt;
 *     &lt;enumeration value="dbPROPSatisfiedDate"/&gt;
 *     &lt;enumeration value="dbPROPStartDate"/&gt;
 *     &lt;enumeration value="dbREIMBDueDate"/&gt;
 *     &lt;enumeration value="dbREIMBStartDate"/&gt;
 *     &lt;enumeration value="dbSUPPEffDate"/&gt;
 *     &lt;enumeration value="mltpCMTMTConditions"/&gt;
 *     &lt;enumeration value="mltpCMTMTFacilitys"/&gt;
 *     &lt;enumeration value="mskCMTMTDays"/&gt;
 *     &lt;enumeration value="mskCMTMTMonths"/&gt;
 *     &lt;enumeration value="mskCMTMTYears"/&gt;
 *     &lt;enumeration value="mskJUDoriginalPrincipal"/&gt;
 *     &lt;enumeration value="mskREIMBAmount"/&gt;
 *     &lt;enumeration value="mskSUPPAmount"/&gt;
 *     &lt;enumeration value="rdoCMTMTIndeterminate"/&gt;
 *     &lt;enumeration value="rdoCMTMTTerm"/&gt;
 *     &lt;enumeration value="sbxCONDFJparty"/&gt;
 *     &lt;enumeration value="sbxCONDparty"/&gt;
 *     &lt;enumeration value="sbxCUSTAward"/&gt;
 *     &lt;enumeration value="sbxCUSTChild"/&gt;
 *     &lt;enumeration value="sbxJUDpartyAsgn"/&gt;
 *     &lt;enumeration value="sbxJUDpartyCred"/&gt;
 *     &lt;enumeration value="sbxJUDpartyDebt"/&gt;
 *     &lt;enumeration value="sbxPARTParties"/&gt;
 *     &lt;enumeration value="sbxPLCMTLocation"/&gt;
 *     &lt;enumeration value="sbxPLCMTOf"/&gt;
 *     &lt;enumeration value="sbxPROPAgainst"/&gt;
 *     &lt;enumeration value="sbxPROPFavor"/&gt;
 *     &lt;enumeration value="sbxREIMBObligorPayor"/&gt;
 *     &lt;enumeration value="sbxSUPPDenBehalf"/&gt;
 *     &lt;enumeration value="sbxSUPPDenPayor"/&gt;
 *     &lt;enumeration value="sbxSUPPMedBehalf"/&gt;
 *     &lt;enumeration value="sbxSUPPMedPayor"/&gt;
 *     &lt;enumeration value="sbxSUPPSuppBehalf"/&gt;
 *     &lt;enumeration value="sbxSUPPSuppPayee"/&gt;
 *     &lt;enumeration value="sbxSUPPSuppPayor"/&gt;
 *     &lt;enumeration value="sbxVISITChild"/&gt;
 *     &lt;enumeration value="sbxVISITGranted"/&gt;
 *     &lt;enumeration value="txtCMTMTComment"/&gt;
 *     &lt;enumeration value="txtCONDFJcomment"/&gt;
 *     &lt;enumeration value="txtCONDcomment"/&gt;
 *     &lt;enumeration value="txtCUSTComment"/&gt;
 *     &lt;enumeration value="txtJUDcomment"/&gt;
 *     &lt;enumeration value="txtPARTComment"/&gt;
 *     &lt;enumeration value="txtPLCMTComment"/&gt;
 *     &lt;enumeration value="txtPLCMTLocation"/&gt;
 *     &lt;enumeration value="txtPLCMTTimeStampAdded"/&gt;
 *     &lt;enumeration value="txtPROPDescription"/&gt;
 *     &lt;enumeration value="txtPROPVin"/&gt;
 *     &lt;enumeration value="txtREIMBObligeePayee"/&gt;
 *     &lt;enumeration value="txtVISITComment"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "JudgmentComponentValueType")
@XmlEnum
public enum JudgmentComponentValueType {

    @XmlEnumValue("ConversionCost")
    CONVERSION_COST("ConversionCost"),
    @XmlEnumValue("ConversionDate")
    CONVERSION_DATE("ConversionDate"),
    @XmlEnumValue("ConversionInterest")
    CONVERSION_INTEREST("ConversionInterest"),
    @XmlEnumValue("ConversionPrincipal")
    CONVERSION_PRINCIPAL("ConversionPrincipal"),
    TEXT("TEXT"),
    @XmlEnumValue("cboCUSTType")
    CBO_CUST_TYPE("cboCUSTType"),
    @XmlEnumValue("cboJUDawardReason")
    CBO_JU_DAWARD_REASON("cboJUDawardReason"),
    @XmlEnumValue("cboJUDintRateType")
    CBO_JU_DINT_RATE_TYPE("cboJUDintRateType"),
    @XmlEnumValue("cboPLCMTLocation")
    CBO_PLCMT_LOCATION("cboPLCMTLocation"),
    @XmlEnumValue("cboPLCMTType")
    CBO_PLCMT_TYPE("cboPLCMTType"),
    @XmlEnumValue("cboPROPType")
    CBO_PROP_TYPE("cboPROPType"),
    @XmlEnumValue("cboREIMBType")
    CBO_REIMB_TYPE("cboREIMBType"),
    @XmlEnumValue("cboSUPPAmtFreq")
    CBO_SUPP_AMT_FREQ("cboSUPPAmtFreq"),
    @XmlEnumValue("cboSUPPMethod")
    CBO_SUPP_METHOD("cboSUPPMethod"),
    @XmlEnumValue("cboSUPPMethodFreq")
    CBO_SUPP_METHOD_FREQ("cboSUPPMethodFreq"),
    @XmlEnumValue("cboSUPPType")
    CBO_SUPP_TYPE("cboSUPPType"),
    @XmlEnumValue("cboVISITType")
    CBO_VISIT_TYPE("cboVISITType"),
    @XmlEnumValue("dbCMTMTEndDate")
    DB_CMTMT_END_DATE("dbCMTMTEndDate"),
    @XmlEnumValue("dbCMTMTReportDate")
    DB_CMTMT_REPORT_DATE("dbCMTMTReportDate"),
    @XmlEnumValue("dbCMTMTStartDate")
    DB_CMTMT_START_DATE("dbCMTMTStartDate"),
    @XmlEnumValue("dbJUDdateDocketed")
    DB_JU_DDATE_DOCKETED("dbJUDdateDocketed"),
    @XmlEnumValue("dbJUDdateEntered")
    DB_JU_DDATE_ENTERED("dbJUDdateEntered"),
    @XmlEnumValue("dbJUDdateExpires")
    DB_JU_DDATE_EXPIRES("dbJUDdateExpires"),
    @XmlEnumValue("dbJUDdateInactive")
    DB_JU_DDATE_INACTIVE("dbJUDdateInactive"),
    @XmlEnumValue("dbJUDtimeDocketed")
    DB_JU_DTIME_DOCKETED("dbJUDtimeDocketed"),
    @XmlEnumValue("dbPLCMTEndDate")
    DB_PLCMT_END_DATE("dbPLCMTEndDate"),
    @XmlEnumValue("dbPLCMTStartDate")
    DB_PLCMT_START_DATE("dbPLCMTStartDate"),
    @XmlEnumValue("dbPROPRecordedDate")
    DB_PROP_RECORDED_DATE("dbPROPRecordedDate"),
    @XmlEnumValue("dbPROPSatisfiedDate")
    DB_PROP_SATISFIED_DATE("dbPROPSatisfiedDate"),
    @XmlEnumValue("dbPROPStartDate")
    DB_PROP_START_DATE("dbPROPStartDate"),
    @XmlEnumValue("dbREIMBDueDate")
    DB_REIMB_DUE_DATE("dbREIMBDueDate"),
    @XmlEnumValue("dbREIMBStartDate")
    DB_REIMB_START_DATE("dbREIMBStartDate"),
    @XmlEnumValue("dbSUPPEffDate")
    DB_SUPP_EFF_DATE("dbSUPPEffDate"),
    @XmlEnumValue("mltpCMTMTConditions")
    MLTP_CMTMT_CONDITIONS("mltpCMTMTConditions"),
    @XmlEnumValue("mltpCMTMTFacilitys")
    MLTP_CMTMT_FACILITYS("mltpCMTMTFacilitys"),
    @XmlEnumValue("mskCMTMTDays")
    MSK_CMTMT_DAYS("mskCMTMTDays"),
    @XmlEnumValue("mskCMTMTMonths")
    MSK_CMTMT_MONTHS("mskCMTMTMonths"),
    @XmlEnumValue("mskCMTMTYears")
    MSK_CMTMT_YEARS("mskCMTMTYears"),
    @XmlEnumValue("mskJUDoriginalPrincipal")
    MSK_JU_DORIGINAL_PRINCIPAL("mskJUDoriginalPrincipal"),
    @XmlEnumValue("mskREIMBAmount")
    MSK_REIMB_AMOUNT("mskREIMBAmount"),
    @XmlEnumValue("mskSUPPAmount")
    MSK_SUPP_AMOUNT("mskSUPPAmount"),
    @XmlEnumValue("rdoCMTMTIndeterminate")
    RDO_CMTMT_INDETERMINATE("rdoCMTMTIndeterminate"),
    @XmlEnumValue("rdoCMTMTTerm")
    RDO_CMTMT_TERM("rdoCMTMTTerm"),
    @XmlEnumValue("sbxCONDFJparty")
    SBX_CONDF_JPARTY("sbxCONDFJparty"),
    @XmlEnumValue("sbxCONDparty")
    SBX_CON_DPARTY("sbxCONDparty"),
    @XmlEnumValue("sbxCUSTAward")
    SBX_CUST_AWARD("sbxCUSTAward"),
    @XmlEnumValue("sbxCUSTChild")
    SBX_CUST_CHILD("sbxCUSTChild"),
    @XmlEnumValue("sbxJUDpartyAsgn")
    SBX_JU_DPARTY_ASGN("sbxJUDpartyAsgn"),
    @XmlEnumValue("sbxJUDpartyCred")
    SBX_JU_DPARTY_CRED("sbxJUDpartyCred"),
    @XmlEnumValue("sbxJUDpartyDebt")
    SBX_JU_DPARTY_DEBT("sbxJUDpartyDebt"),
    @XmlEnumValue("sbxPARTParties")
    SBX_PART_PARTIES("sbxPARTParties"),
    @XmlEnumValue("sbxPLCMTLocation")
    SBX_PLCMT_LOCATION("sbxPLCMTLocation"),
    @XmlEnumValue("sbxPLCMTOf")
    SBX_PLCMT_OF("sbxPLCMTOf"),
    @XmlEnumValue("sbxPROPAgainst")
    SBX_PROP_AGAINST("sbxPROPAgainst"),
    @XmlEnumValue("sbxPROPFavor")
    SBX_PROP_FAVOR("sbxPROPFavor"),
    @XmlEnumValue("sbxREIMBObligorPayor")
    SBX_REIMB_OBLIGOR_PAYOR("sbxREIMBObligorPayor"),
    @XmlEnumValue("sbxSUPPDenBehalf")
    SBX_SUPP_DEN_BEHALF("sbxSUPPDenBehalf"),
    @XmlEnumValue("sbxSUPPDenPayor")
    SBX_SUPP_DEN_PAYOR("sbxSUPPDenPayor"),
    @XmlEnumValue("sbxSUPPMedBehalf")
    SBX_SUPP_MED_BEHALF("sbxSUPPMedBehalf"),
    @XmlEnumValue("sbxSUPPMedPayor")
    SBX_SUPP_MED_PAYOR("sbxSUPPMedPayor"),
    @XmlEnumValue("sbxSUPPSuppBehalf")
    SBX_SUPP_SUPP_BEHALF("sbxSUPPSuppBehalf"),
    @XmlEnumValue("sbxSUPPSuppPayee")
    SBX_SUPP_SUPP_PAYEE("sbxSUPPSuppPayee"),
    @XmlEnumValue("sbxSUPPSuppPayor")
    SBX_SUPP_SUPP_PAYOR("sbxSUPPSuppPayor"),
    @XmlEnumValue("sbxVISITChild")
    SBX_VISIT_CHILD("sbxVISITChild"),
    @XmlEnumValue("sbxVISITGranted")
    SBX_VISIT_GRANTED("sbxVISITGranted"),
    @XmlEnumValue("txtCMTMTComment")
    TXT_CMTMT_COMMENT("txtCMTMTComment"),
    @XmlEnumValue("txtCONDFJcomment")
    TXT_CONDF_JCOMMENT("txtCONDFJcomment"),
    @XmlEnumValue("txtCONDcomment")
    TXT_CON_DCOMMENT("txtCONDcomment"),
    @XmlEnumValue("txtCUSTComment")
    TXT_CUST_COMMENT("txtCUSTComment"),
    @XmlEnumValue("txtJUDcomment")
    TXT_JU_DCOMMENT("txtJUDcomment"),
    @XmlEnumValue("txtPARTComment")
    TXT_PART_COMMENT("txtPARTComment"),
    @XmlEnumValue("txtPLCMTComment")
    TXT_PLCMT_COMMENT("txtPLCMTComment"),
    @XmlEnumValue("txtPLCMTLocation")
    TXT_PLCMT_LOCATION("txtPLCMTLocation"),
    @XmlEnumValue("txtPLCMTTimeStampAdded")
    TXT_PLCMT_TIME_STAMP_ADDED("txtPLCMTTimeStampAdded"),
    @XmlEnumValue("txtPROPDescription")
    TXT_PROP_DESCRIPTION("txtPROPDescription"),
    @XmlEnumValue("txtPROPVin")
    TXT_PROP_VIN("txtPROPVin"),
    @XmlEnumValue("txtREIMBObligeePayee")
    TXT_REIMB_OBLIGEE_PAYEE("txtREIMBObligeePayee"),
    @XmlEnumValue("txtVISITComment")
    TXT_VISIT_COMMENT("txtVISITComment");
    private final String value;

    JudgmentComponentValueType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static JudgmentComponentValueType fromValue(String v) {
        for (JudgmentComponentValueType c: JudgmentComponentValueType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
