//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.04 at 12:20:40 AM CDT 
//


package gov.mncourts.caseget;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PartyRemovedReasonTextType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PartyRemovedReasonTextType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Ordered"/&gt;
 *     &lt;enumeration value="Party Connection Added in Error"/&gt;
 *     &lt;enumeration value="Remove party from case"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "PartyRemovedReasonTextType")
@XmlEnum
public enum PartyRemovedReasonTextType {

    @XmlEnumValue("Ordered")
    ORDERED("Ordered"),
    @XmlEnumValue("Party Connection Added in Error")
    PARTY_CONNECTION_ADDED_IN_ERROR("Party Connection Added in Error"),
    @XmlEnumValue("Remove party from case")
    REMOVE_PARTY_FROM_CASE("Remove party from case");
    private final String value;

    PartyRemovedReasonTextType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PartyRemovedReasonTextType fromValue(String v) {
        for (PartyRemovedReasonTextType c: PartyRemovedReasonTextType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
