//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.04 at 12:20:40 AM CDT 
//


package gov.mncourts.caseget;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * A structure modeled after JXDM that describes an identifier issued to a person.
 * 
 * <p>Java class for PersonOtherIDType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PersonOtherIDType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ID" type="{}ID1to30Type"/&gt;
 *         &lt;element name="IDTypeText" type="{}PersonOtherIDTypeType" minOccurs="0"/&gt;
 *         &lt;element name="IDTypeCodeText" type="{}PersonOtherIDTypeCodeType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PersonOtherIDType", propOrder = {
    "id",
    "idTypeText",
    "idTypeCodeText"
})
public class PersonOtherIDType {

    @XmlElement(name = "ID", required = true)
    protected String id;
    @XmlElement(name = "IDTypeText")
    @XmlSchemaType(name = "string")
    protected PersonOtherIDTypeType idTypeText;
    @XmlElement(name = "IDTypeCodeText", required = true)
    @XmlSchemaType(name = "string")
    protected PersonOtherIDTypeCodeType idTypeCodeText;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the idTypeText property.
     * 
     * @return
     *     possible object is
     *     {@link PersonOtherIDTypeType }
     *     
     */
    public PersonOtherIDTypeType getIDTypeText() {
        return idTypeText;
    }

    /**
     * Sets the value of the idTypeText property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonOtherIDTypeType }
     *     
     */
    public void setIDTypeText(PersonOtherIDTypeType value) {
        this.idTypeText = value;
    }

    /**
     * Gets the value of the idTypeCodeText property.
     * 
     * @return
     *     possible object is
     *     {@link PersonOtherIDTypeCodeType }
     *     
     */
    public PersonOtherIDTypeCodeType getIDTypeCodeText() {
        return idTypeCodeText;
    }

    /**
     * Sets the value of the idTypeCodeText property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonOtherIDTypeCodeType }
     *     
     */
    public void setIDTypeCodeText(PersonOtherIDTypeCodeType value) {
        this.idTypeCodeText = value;
    }

}
