//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.04 at 12:20:40 AM CDT 
//


package gov.mncourts.caseget;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ReassignmentReasonCodeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ReassignmentReasonCodeType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="AP"/&gt;
 *     &lt;enumeration value="CCSA"/&gt;
 *     &lt;enumeration value="CV"/&gt;
 *     &lt;enumeration value="CVC"/&gt;
 *     &lt;enumeration value="CVPM"/&gt;
 *     &lt;enumeration value="CVPTP"/&gt;
 *     &lt;enumeration value="WC"/&gt;
 *     &lt;enumeration value="HOC"/&gt;
 *     &lt;enumeration value="INT"/&gt;
 *     &lt;enumeration value="JC"/&gt;
 *     &lt;enumeration value="JOREC"/&gt;
 *     &lt;enumeration value="JOREM"/&gt;
 *     &lt;enumeration value="JOAL"/&gt;
 *     &lt;enumeration value="OBJREF"/&gt;
 *     &lt;enumeration value="R"/&gt;
 *     &lt;enumeration value="RBA"/&gt;
 *     &lt;enumeration value="TVD"/&gt;
 *     &lt;enumeration value="TV1"/&gt;
 *     &lt;enumeration value="TVT"/&gt;
 *     &lt;enumeration value="U"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "ReassignmentReasonCodeType")
@XmlEnum
public enum ReassignmentReasonCodeType {

    AP("AP"),
    CCSA("CCSA"),
    CV("CV"),
    CVC("CVC"),
    CVPM("CVPM"),
    CVPTP("CVPTP"),
    WC("WC"),
    HOC("HOC"),
    INT("INT"),
    JC("JC"),
    JOREC("JOREC"),
    JOREM("JOREM"),
    JOAL("JOAL"),
    OBJREF("OBJREF"),
    R("R"),
    RBA("RBA"),
    TVD("TVD"),
    @XmlEnumValue("TV1")
    TV_1("TV1"),
    TVT("TVT"),
    U("U");
    private final String value;

    ReassignmentReasonCodeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ReassignmentReasonCodeType fromValue(String v) {
        for (ReassignmentReasonCodeType c: ReassignmentReasonCodeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
