//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.04 at 12:20:40 AM CDT 
//


package gov.mncourts.caseget;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Details about the speed of the vehicle involved in the incident.  Required for speeding offenses.
 * 
 * <p>Java class for SpeedingType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SpeedingType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}PostedSpeedMeasure"/&gt;
 *         &lt;element ref="{}ObservedSpeedMeasure"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SpeedingType", propOrder = {
    "postedSpeedMeasure",
    "observedSpeedMeasure"
})
public class SpeedingType {

    @XmlElement(name = "PostedSpeedMeasure", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger postedSpeedMeasure;
    @XmlElement(name = "ObservedSpeedMeasure", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger observedSpeedMeasure;

    /**
     * Gets the value of the postedSpeedMeasure property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPostedSpeedMeasure() {
        return postedSpeedMeasure;
    }

    /**
     * Sets the value of the postedSpeedMeasure property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPostedSpeedMeasure(BigInteger value) {
        this.postedSpeedMeasure = value;
    }

    /**
     * Gets the value of the observedSpeedMeasure property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getObservedSpeedMeasure() {
        return observedSpeedMeasure;
    }

    /**
     * Sets the value of the observedSpeedMeasure property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setObservedSpeedMeasure(BigInteger value) {
        this.observedSpeedMeasure = value;
    }

}
