//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.04 at 12:20:40 AM CDT 
//


package gov.mncourts.caseget;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VehicleTypeCodeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="VehicleTypeCodeType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="PASSVEH16"/&gt;
 *     &lt;enumeration value="AERO"/&gt;
 *     &lt;enumeration value="ATV"/&gt;
 *     &lt;enumeration value="BIKE"/&gt;
 *     &lt;enumeration value="BUS"/&gt;
 *     &lt;enumeration value="CONSTEQUIP"/&gt;
 *     &lt;enumeration value="ELECBIKE"/&gt;
 *     &lt;enumeration value="EMERGVEH"/&gt;
 *     &lt;enumeration value="FARM"/&gt;
 *     &lt;enumeration value="HINO"/&gt;
 *     &lt;enumeration value="BOAT"/&gt;
 *     &lt;enumeration value="MOTORCYCLE"/&gt;
 *     &lt;enumeration value="MOTORBIKE"/&gt;
 *     &lt;enumeration value="NONMOTBOAT"/&gt;
 *     &lt;enumeration value="ORMOTORCY"/&gt;
 *     &lt;enumeration value="ORRV"/&gt;
 *     &lt;enumeration value="OTHER"/&gt;
 *     &lt;enumeration value="PASSVEH"/&gt;
 *     &lt;enumeration value="ROADTRAC"/&gt;
 *     &lt;enumeration value="SCHOOL"/&gt;
 *     &lt;enumeration value="SEMI"/&gt;
 *     &lt;enumeration value="SNOWMO"/&gt;
 *     &lt;enumeration value="TOW"/&gt;
 *     &lt;enumeration value="TRAILER"/&gt;
 *     &lt;enumeration value="TRANSIT"/&gt;
 *     &lt;enumeration value="TRUCK"/&gt;
 *     &lt;enumeration value="VENTO"/&gt;
 *     &lt;enumeration value="WSTAR"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "VehicleTypeCodeType")
@XmlEnum
public enum VehicleTypeCodeType {

    @XmlEnumValue("PASSVEH16")
    PASSVEH_16("PASSVEH16"),
    AERO("AERO"),
    ATV("ATV"),
    BIKE("BIKE"),
    BUS("BUS"),
    CONSTEQUIP("CONSTEQUIP"),
    ELECBIKE("ELECBIKE"),
    EMERGVEH("EMERGVEH"),
    FARM("FARM"),
    HINO("HINO"),
    BOAT("BOAT"),
    MOTORCYCLE("MOTORCYCLE"),
    MOTORBIKE("MOTORBIKE"),
    NONMOTBOAT("NONMOTBOAT"),
    ORMOTORCY("ORMOTORCY"),
    ORRV("ORRV"),
    OTHER("OTHER"),
    PASSVEH("PASSVEH"),
    ROADTRAC("ROADTRAC"),
    SCHOOL("SCHOOL"),
    SEMI("SEMI"),
    SNOWMO("SNOWMO"),
    TOW("TOW"),
    TRAILER("TRAILER"),
    TRANSIT("TRANSIT"),
    TRUCK("TRUCK"),
    VENTO("VENTO"),
    WSTAR("WSTAR");
    private final String value;

    VehicleTypeCodeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static VehicleTypeCodeType fromValue(String v) {
        for (VehicleTypeCodeType c: VehicleTypeCodeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
