//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.03 at 11:26:33 PM CDT 
//


package gov.mnvcourts.casetget;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BaseCaseTypeTextType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="BaseCaseTypeTextType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Adoption"/>
 *     &lt;enumeration value="Adult"/>
 *     &lt;enumeration value="Appellate Criminal"/>
 *     &lt;enumeration value="Appellate Non-Criminal"/>
 *     &lt;enumeration value="Bad Checks"/>
 *     &lt;enumeration value="Bond Forfeiture"/>
 *     &lt;enumeration value="Check"/>
 *     &lt;enumeration value="Civil Domestic Violence"/>
 *     &lt;enumeration value="Community Corrections"/>
 *     &lt;enumeration value="Contracts, Torts, Damage or Injury"/>
 *     &lt;enumeration value="Divorce"/>
 *     &lt;enumeration value="Drug Court"/>
 *     &lt;enumeration value="Drug Court Non-Criminal"/>
 *     &lt;enumeration value="Guardianship (Family)"/>
 *     &lt;enumeration value="Guardianship (Probate)"/>
 *     &lt;enumeration value="Inquest"/>
 *     &lt;enumeration value="Juvenile"/>
 *     &lt;enumeration value="Juvenile Community Corrections"/>
 *     &lt;enumeration value="Juvenile Drug Court"/>
 *     &lt;enumeration value="Juvenile Drug Court Non-Criminal"/>
 *     &lt;enumeration value="Juvenile Pre-Trial Supervision"/>
 *     &lt;enumeration value="Juvenile Probation"/>
 *     &lt;enumeration value="Juvenile Prosecutor"/>
 *     &lt;enumeration value="Juvenile Public Defender"/>
 *     &lt;enumeration value="Mental Health"/>
 *     &lt;enumeration value="Non-Criminal Prosecutor"/>
 *     &lt;enumeration value="Non-Criminal Public Defender"/>
 *     &lt;enumeration value="Other Civil"/>
 *     &lt;enumeration value="Other Family"/>
 *     &lt;enumeration value="Parent/Child Relationship"/>
 *     &lt;enumeration value="Paternity"/>
 *     &lt;enumeration value="Pre-Trial Supervision"/>
 *     &lt;enumeration value="Probate"/>
 *     &lt;enumeration value="Probation"/>
 *     &lt;enumeration value="Prosecutor"/>
 *     &lt;enumeration value="Public Defender"/>
 *     &lt;enumeration value="Related Civil"/>
 *     &lt;enumeration value="Support"/>
 *     &lt;enumeration value="Tax Suits or Condemnation"/>
 *     &lt;enumeration value="Traffic"/>
 *     &lt;enumeration value="Transfer-In"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "BaseCaseTypeTextType")
@XmlEnum
public enum BaseCaseTypeTextType {

    @XmlEnumValue("Adoption")
    ADOPTION("Adoption"),
    @XmlEnumValue("Adult")
    ADULT("Adult"),
    @XmlEnumValue("Appellate Criminal")
    APPELLATE_CRIMINAL("Appellate Criminal"),
    @XmlEnumValue("Appellate Non-Criminal")
    APPELLATE_NON_CRIMINAL("Appellate Non-Criminal"),
    @XmlEnumValue("Bad Checks")
    BAD_CHECKS("Bad Checks"),
    @XmlEnumValue("Bond Forfeiture")
    BOND_FORFEITURE("Bond Forfeiture"),
    @XmlEnumValue("Check")
    CHECK("Check"),
    @XmlEnumValue("Civil Domestic Violence")
    CIVIL_DOMESTIC_VIOLENCE("Civil Domestic Violence"),
    @XmlEnumValue("Community Corrections")
    COMMUNITY_CORRECTIONS("Community Corrections"),
    @XmlEnumValue("Contracts, Torts, Damage or Injury")
    CONTRACTS_TORTS_DAMAGE_OR_INJURY("Contracts, Torts, Damage or Injury"),
    @XmlEnumValue("Divorce")
    DIVORCE("Divorce"),
    @XmlEnumValue("Drug Court")
    DRUG_COURT("Drug Court"),
    @XmlEnumValue("Drug Court Non-Criminal")
    DRUG_COURT_NON_CRIMINAL("Drug Court Non-Criminal"),
    @XmlEnumValue("Guardianship (Family)")
    GUARDIANSHIP_FAMILY("Guardianship (Family)"),
    @XmlEnumValue("Guardianship (Probate)")
    GUARDIANSHIP_PROBATE("Guardianship (Probate)"),
    @XmlEnumValue("Inquest")
    INQUEST("Inquest"),
    @XmlEnumValue("Juvenile")
    JUVENILE("Juvenile"),
    @XmlEnumValue("Juvenile Community Corrections")
    JUVENILE_COMMUNITY_CORRECTIONS("Juvenile Community Corrections"),
    @XmlEnumValue("Juvenile Drug Court")
    JUVENILE_DRUG_COURT("Juvenile Drug Court"),
    @XmlEnumValue("Juvenile Drug Court Non-Criminal")
    JUVENILE_DRUG_COURT_NON_CRIMINAL("Juvenile Drug Court Non-Criminal"),
    @XmlEnumValue("Juvenile Pre-Trial Supervision")
    JUVENILE_PRE_TRIAL_SUPERVISION("Juvenile Pre-Trial Supervision"),
    @XmlEnumValue("Juvenile Probation")
    JUVENILE_PROBATION("Juvenile Probation"),
    @XmlEnumValue("Juvenile Prosecutor")
    JUVENILE_PROSECUTOR("Juvenile Prosecutor"),
    @XmlEnumValue("Juvenile Public Defender")
    JUVENILE_PUBLIC_DEFENDER("Juvenile Public Defender"),
    @XmlEnumValue("Mental Health")
    MENTAL_HEALTH("Mental Health"),
    @XmlEnumValue("Non-Criminal Prosecutor")
    NON_CRIMINAL_PROSECUTOR("Non-Criminal Prosecutor"),
    @XmlEnumValue("Non-Criminal Public Defender")
    NON_CRIMINAL_PUBLIC_DEFENDER("Non-Criminal Public Defender"),
    @XmlEnumValue("Other Civil")
    OTHER_CIVIL("Other Civil"),
    @XmlEnumValue("Other Family")
    OTHER_FAMILY("Other Family"),
    @XmlEnumValue("Parent/Child Relationship")
    PARENT_CHILD_RELATIONSHIP("Parent/Child Relationship"),
    @XmlEnumValue("Paternity")
    PATERNITY("Paternity"),
    @XmlEnumValue("Pre-Trial Supervision")
    PRE_TRIAL_SUPERVISION("Pre-Trial Supervision"),
    @XmlEnumValue("Probate")
    PROBATE("Probate"),
    @XmlEnumValue("Probation")
    PROBATION("Probation"),
    @XmlEnumValue("Prosecutor")
    PROSECUTOR("Prosecutor"),
    @XmlEnumValue("Public Defender")
    PUBLIC_DEFENDER("Public Defender"),
    @XmlEnumValue("Related Civil")
    RELATED_CIVIL("Related Civil"),
    @XmlEnumValue("Support")
    SUPPORT("Support"),
    @XmlEnumValue("Tax Suits or Condemnation")
    TAX_SUITS_OR_CONDEMNATION("Tax Suits or Condemnation"),
    @XmlEnumValue("Traffic")
    TRAFFIC("Traffic"),
    @XmlEnumValue("Transfer-In")
    TRANSFER_IN("Transfer-In");
    private final String value;

    BaseCaseTypeTextType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static BaseCaseTypeTextType fromValue(String v) {
        for (BaseCaseTypeTextType c: BaseCaseTypeTextType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
