//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.03 at 11:26:33 PM CDT 
//


package gov.mnvcourts.casetget;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CasePartyRelationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CasePartyRelationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PartyReference">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="partyKey" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="PartyCaseAssociationText" type="{http://www.courts.state.mn.us/CourtXML/3}ExtendedPartyConnectionTypeCodeTextType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CasePartyRelationType", propOrder = {
    "partyReference",
    "partyCaseAssociationText"
})
public class CasePartyRelationType {

    @XmlElement(name = "PartyReference", required = true)
    protected CasePartyRelationType.PartyReference partyReference;
    @XmlElement(name = "PartyCaseAssociationText", required = true)
    protected List<ExtendedPartyConnectionTypeCodeTextType> partyCaseAssociationText;

    /**
     * Gets the value of the partyReference property.
     * 
     * @return
     *     possible object is
     *     {@link CasePartyRelationType.PartyReference }
     *     
     */
    public CasePartyRelationType.PartyReference getPartyReference() {
        return partyReference;
    }

    /**
     * Sets the value of the partyReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link CasePartyRelationType.PartyReference }
     *     
     */
    public void setPartyReference(CasePartyRelationType.PartyReference value) {
        this.partyReference = value;
    }

    /**
     * Gets the value of the partyCaseAssociationText property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the partyCaseAssociationText property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPartyCaseAssociationText().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExtendedPartyConnectionTypeCodeTextType }
     * 
     * 
     */
    public List<ExtendedPartyConnectionTypeCodeTextType> getPartyCaseAssociationText() {
        if (partyCaseAssociationText == null) {
            partyCaseAssociationText = new ArrayList<ExtendedPartyConnectionTypeCodeTextType>();
        }
        return this.partyCaseAssociationText;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="partyKey" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class PartyReference {

        @XmlAttribute(name = "partyKey", required = true)
        @XmlSchemaType(name = "anySimpleType")
        protected String partyKey;

        /**
         * Gets the value of the partyKey property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPartyKey() {
            return partyKey;
        }

        /**
         * Sets the value of the partyKey property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPartyKey(String value) {
            this.partyKey = value;
        }

    }

}
