//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.03 at 11:26:33 PM CDT 
//


package gov.mnvcourts.casetget;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FinancialCategoryCodeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="FinancialCategoryCodeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="BAILBOND"/>
 *     &lt;enumeration value="CASEFEES"/>
 *     &lt;enumeration value="DDFINCAT"/>
 *     &lt;enumeration value="FINES"/>
 *     &lt;enumeration value="MISC"/>
 *     &lt;enumeration value="TRUST"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "FinancialCategoryCodeType")
@XmlEnum
public enum FinancialCategoryCodeType {

    BAILBOND,
    CASEFEES,
    DDFINCAT,
    FINES,
    MISC,
    TRUST;

    public String value() {
        return name();
    }

    public static FinancialCategoryCodeType fromValue(String v) {
        return valueOf(v);
    }

}
