//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.03 at 11:26:33 PM CDT 
//


package gov.mnvcourts.casetget;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for JuvenilePlacementAgencyTypeCodeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="JuvenilePlacementAgencyTypeCodeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ABBOTT"/>
 *     &lt;enumeration value="AGAPESHOR"/>
 *     &lt;enumeration value="AGAPESTP"/>
 *     &lt;enumeration value="ADY"/>
 *     &lt;enumeration value="AG"/>
 *     &lt;enumeration value="ANOKAJS"/>
 *     &lt;enumeration value="ALOUISBU"/>
 *     &lt;enumeration value="ALOUISS"/>
 *     &lt;enumeration value="APRILS"/>
 *     &lt;enumeration value="ARROWPLC"/>
 *     &lt;enumeration value="ATTACHMENT"/>
 *     &lt;enumeration value="BAXTERY"/>
 *     &lt;enumeration value="BELLON"/>
 *     &lt;enumeration value="FFBEMIDJ"/>
 *     &lt;enumeration value="BETHANYCS"/>
 *     &lt;enumeration value="BOYSTOWN"/>
 *     &lt;enumeration value="BRAZA"/>
 *     &lt;enumeration value="BRKFREE"/>
 *     &lt;enumeration value="BRIDGEN"/>
 *     &lt;enumeration value="BRIDGEWAYC"/>
 *     &lt;enumeration value="BROWNCEC"/>
 *     &lt;enumeration value="BRHFOYER"/>
 *     &lt;enumeration value="BURLING"/>
 *     &lt;enumeration value="BUSHCHILDP"/>
 *     &lt;enumeration value="CR"/>
 *     &lt;enumeration value="CARLTONYC"/>
 *     &lt;enumeration value="CCJDC"/>
 *     &lt;enumeration value="CCFF"/>
 *     &lt;enumeration value="CCSC"/>
 *     &lt;enumeration value="CODEAF"/>
 *     &lt;enumeration value="CMRDC"/>
 *     &lt;enumeration value="CMJC"/>
 *     &lt;enumeration value="CHAMBERAC"/>
 *     &lt;enumeration value="CHRISTEN"/>
 *     &lt;enumeration value="THECITYGH"/>
 *     &lt;enumeration value="CCDC"/>
 *     &lt;enumeration value="CONNECT"/>
 *     &lt;enumeration value="CORHOU"/>
 *     &lt;enumeration value="COUNTRYS"/>
 *     &lt;enumeration value="COVENANT"/>
 *     &lt;enumeration value="COO"/>
 *     &lt;enumeration value="DAKJSCP"/>
 *     &lt;enumeration value="DH"/>
 *     &lt;enumeration value="DRRESTRTCT"/>
 *     &lt;enumeration value="EASTCRPLC"/>
 *     &lt;enumeration value="ECAC"/>
 *     &lt;enumeration value="ELMOREP"/>
 *     &lt;enumeration value="EPISCS"/>
 *     &lt;enumeration value="EFH"/>
 *     &lt;enumeration value="EGH"/>
 *     &lt;enumeration value="FACTGH"/>
 *     &lt;enumeration value="FAIRVFL"/>
 *     &lt;enumeration value="FFRTC"/>
 *     &lt;enumeration value="FHCCHCH"/>
 *     &lt;enumeration value="FDLGH"/>
 *     &lt;enumeration value="FRSTRIDGE"/>
 *     &lt;enumeration value="FCRHR"/>
 *     &lt;enumeration value="FCAL"/>
 *     &lt;enumeration value="GALASS"/>
 *     &lt;enumeration value="GERALDTP"/>
 *     &lt;enumeration value="GERARD"/>
 *     &lt;enumeration value="GLENMILL"/>
 *     &lt;enumeration value="GFH"/>
 *     &lt;enumeration value="GLDLVNCTR"/>
 *     &lt;enumeration value="GRIFFIN"/>
 *     &lt;enumeration value="GROWHOM"/>
 *     &lt;enumeration value="GULLHBR"/>
 *     &lt;enumeration value="HFH"/>
 *     &lt;enumeration value="HALST"/>
 *     &lt;enumeration value="HHD"/>
 *     &lt;enumeration value="HSEHAST2"/>
 *     &lt;enumeration value="HSNSTILL2"/>
 *     &lt;enumeration value="HSSBURN2"/>
 *     &lt;enumeration value="HAYWARDPLC"/>
 *     &lt;enumeration value="HEARTHBC"/>
 *     &lt;enumeration value="HEARTHE"/>
 *     &lt;enumeration value="HEARTHGV"/>
 *     &lt;enumeration value="HEARTHMT"/>
 *     &lt;enumeration value="HEARTHM"/>
 *     &lt;enumeration value="HEARTHSSP"/>
 *     &lt;enumeration value="HEARTHW"/>
 *     &lt;enumeration value="HED"/>
 *     &lt;enumeration value="HCJDCPLC"/>
 *     &lt;enumeration value="HOMAWAY"/>
 *     &lt;enumeration value="HOMRNGND"/>
 *     &lt;enumeration value="ICANWASECA"/>
 *     &lt;enumeration value="ISANTIYOUP"/>
 *     &lt;enumeration value="IH"/>
 *     &lt;enumeration value="ITASKINH"/>
 *     &lt;enumeration value="JOHNSCH"/>
 *     &lt;enumeration value="KAIROS"/>
 *     &lt;enumeration value="KCBGH"/>
 *     &lt;enumeration value="KCGGH"/>
 *     &lt;enumeration value="KAPANI"/>
 *     &lt;enumeration value="KARIBU"/>
 *     &lt;enumeration value="KTCSD"/>
 *     &lt;enumeration value="KIDSPEACE2"/>
 *     &lt;enumeration value="KOHLH"/>
 *     &lt;enumeration value="LGFH"/>
 *     &lt;enumeration value="LEOAHOFF2"/>
 *     &lt;enumeration value="LIFEH"/>
 *     &lt;enumeration value="LSANDGH"/>
 *     &lt;enumeration value="LSGH"/>
 *     &lt;enumeration value="LIVINGSTON"/>
 *     &lt;enumeration value="LOSTFND"/>
 *     &lt;enumeration value="MANYRIV2"/>
 *     &lt;enumeration value="MAPLKA"/>
 *     &lt;enumeration value="MAPLET"/>
 *     &lt;enumeration value="MARSHAGH"/>
 *     &lt;enumeration value="MCCROSS"/>
 *     &lt;enumeration value="MCLEODGH"/>
 *     &lt;enumeration value="MCLEODTS"/>
 *     &lt;enumeration value="MHDR"/>
 *     &lt;enumeration value="MERITC"/>
 *     &lt;enumeration value="MERITEDC2"/>
 *     &lt;enumeration value="MERRITTH"/>
 *     &lt;enumeration value="MIDWGH"/>
 *     &lt;enumeration value="MFCC"/>
 *     &lt;enumeration value="MILLELACGH"/>
 *     &lt;enumeration value="MLNWTRL"/>
 *     &lt;enumeration value="FFMPLS"/>
 *     &lt;enumeration value="MCFLINOPLC"/>
 *     &lt;enumeration value="MCFRW"/>
 *     &lt;enumeration value="THISTLEDEW"/>
 *     &lt;enumeration value="MNRVLYJUV"/>
 *     &lt;enumeration value="NGH"/>
 *     &lt;enumeration value="NDBL"/>
 *     &lt;enumeration value="NEXTSTPPL"/>
 *     &lt;enumeration value="NEXRXEP"/>
 *     &lt;enumeration value="MN052002S"/>
 *     &lt;enumeration value="NORTHCROW"/>
 *     &lt;enumeration value="NHI"/>
 *     &lt;enumeration value="NOCRADLE"/>
 *     &lt;enumeration value="NCC"/>
 *     &lt;enumeration value="NRC"/>
 *     &lt;enumeration value="NWMC"/>
 *     &lt;enumeration value="NMJC"/>
 *     &lt;enumeration value="NOWOODCH"/>
 *     &lt;enumeration value="OKH"/>
 *     &lt;enumeration value="OCJDCPLC"/>
 *     &lt;enumeration value="PATH"/>
 *     &lt;enumeration value="PATHSC"/>
 *     &lt;enumeration value="PATHVF"/>
 *     &lt;enumeration value="PATHB"/>
 *     &lt;enumeration value="PATHFIND"/>
 *     &lt;enumeration value="PFHTRF"/>
 *     &lt;enumeration value="PERT"/>
 *     &lt;enumeration value="PHNIXB510"/>
 *     &lt;enumeration value="PHNIXMLPS"/>
 *     &lt;enumeration value="PLACEN"/>
 *     &lt;enumeration value="PLACES"/>
 *     &lt;enumeration value="PORTBOYGH"/>
 *     &lt;enumeration value="PORTGIRLGH"/>
 *     &lt;enumeration value="PLJDCP"/>
 *     &lt;enumeration value="PLYPBGH"/>
 *     &lt;enumeration value="PLYPGGH"/>
 *     &lt;enumeration value="PRAXIS"/>
 *     &lt;enumeration value="PRISM"/>
 *     &lt;enumeration value="PROCTORH"/>
 *     &lt;enumeration value="RHOME"/>
 *     &lt;enumeration value="RAMCJDC"/>
 *     &lt;enumeration value="RANGEYS"/>
 *     &lt;enumeration value="RLGH"/>
 *     &lt;enumeration value="RRSM"/>
 *     &lt;enumeration value="REDRVJC2"/>
 *     &lt;enumeration value="RFH"/>
 *     &lt;enumeration value="REMB"/>
 *     &lt;enumeration value="RITEPASS"/>
 *     &lt;enumeration value="RIVEDGE"/>
 *     &lt;enumeration value="SAFEHAV"/>
 *     &lt;enumeration value="SCOTTJAF2"/>
 *     &lt;enumeration value="SHAREH"/>
 *     &lt;enumeration value="SCGMN"/>
 *     &lt;enumeration value="SCKIDS"/>
 *     &lt;enumeration value="SYFHRICH"/>
 *     &lt;enumeration value="SYGHSC"/>
 *     &lt;enumeration value="SYPSAND"/>
 *     &lt;enumeration value="SKYRANCH"/>
 *     &lt;enumeration value="SNYD2"/>
 *     &lt;enumeration value="SWYS"/>
 *     &lt;enumeration value="SPRHILLGH"/>
 *     &lt;enumeration value="SPRINGF"/>
 *     &lt;enumeration value="STCLOUDCH2"/>
 *     &lt;enumeration value="STCLOUDGH"/>
 *     &lt;enumeration value="STJOHFC"/>
 *     &lt;enumeration value="STARTSTP"/>
 *     &lt;enumeration value="STORGE"/>
 *     &lt;enumeration value="SUMOAKSP"/>
 *     &lt;enumeration value="SYNERGY"/>
 *     &lt;enumeration value="TITNH"/>
 *     &lt;enumeration value="TEENMOVFOR"/>
 *     &lt;enumeration value="TEKTC"/>
 *     &lt;enumeration value="TSA"/>
 *     &lt;enumeration value="TSHUTCH"/>
 *     &lt;enumeration value="VLBH"/>
 *     &lt;enumeration value="VANHM"/>
 *     &lt;enumeration value="VILRANHHTR"/>
 *     &lt;enumeration value="VILRANCH"/>
 *     &lt;enumeration value="VINTGE"/>
 *     &lt;enumeration value="VOLAMMPLS"/>
 *     &lt;enumeration value="VONWALD"/>
 *     &lt;enumeration value="WAVERLYGH"/>
 *     &lt;enumeration value="WELLNCTR"/>
 *     &lt;enumeration value="WCJCM"/>
 *     &lt;enumeration value="WILLOWR"/>
 *     &lt;enumeration value="WILC"/>
 *     &lt;enumeration value="WPH"/>
 *     &lt;enumeration value="WINGS1"/>
 *     &lt;enumeration value="WINNTC"/>
 *     &lt;enumeration value="WINONAGH"/>
 *     &lt;enumeration value="WOODFIELDC"/>
 *     &lt;enumeration value="WOODLANDPL"/>
 *     &lt;enumeration value="WOODWIA"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "JuvenilePlacementAgencyTypeCodeType")
@XmlEnum
public enum JuvenilePlacementAgencyTypeCodeType {

    ABBOTT("ABBOTT"),
    AGAPESHOR("AGAPESHOR"),
    AGAPESTP("AGAPESTP"),
    ADY("ADY"),
    AG("AG"),
    ANOKAJS("ANOKAJS"),
    ALOUISBU("ALOUISBU"),
    ALOUISS("ALOUISS"),
    APRILS("APRILS"),
    ARROWPLC("ARROWPLC"),
    ATTACHMENT("ATTACHMENT"),
    BAXTERY("BAXTERY"),
    BELLON("BELLON"),
    FFBEMIDJ("FFBEMIDJ"),
    BETHANYCS("BETHANYCS"),
    BOYSTOWN("BOYSTOWN"),
    BRAZA("BRAZA"),
    BRKFREE("BRKFREE"),
    BRIDGEN("BRIDGEN"),
    BRIDGEWAYC("BRIDGEWAYC"),
    BROWNCEC("BROWNCEC"),
    BRHFOYER("BRHFOYER"),
    BURLING("BURLING"),
    BUSHCHILDP("BUSHCHILDP"),
    CR("CR"),
    CARLTONYC("CARLTONYC"),
    CCJDC("CCJDC"),
    CCFF("CCFF"),
    CCSC("CCSC"),
    CODEAF("CODEAF"),
    CMRDC("CMRDC"),
    CMJC("CMJC"),
    CHAMBERAC("CHAMBERAC"),
    CHRISTEN("CHRISTEN"),
    THECITYGH("THECITYGH"),
    CCDC("CCDC"),
    CONNECT("CONNECT"),
    CORHOU("CORHOU"),
    COUNTRYS("COUNTRYS"),
    COVENANT("COVENANT"),
    COO("COO"),
    DAKJSCP("DAKJSCP"),
    DH("DH"),
    DRRESTRTCT("DRRESTRTCT"),
    EASTCRPLC("EASTCRPLC"),
    ECAC("ECAC"),
    ELMOREP("ELMOREP"),
    EPISCS("EPISCS"),
    EFH("EFH"),
    EGH("EGH"),
    FACTGH("FACTGH"),
    FAIRVFL("FAIRVFL"),
    FFRTC("FFRTC"),
    FHCCHCH("FHCCHCH"),
    FDLGH("FDLGH"),
    FRSTRIDGE("FRSTRIDGE"),
    FCRHR("FCRHR"),
    FCAL("FCAL"),
    GALASS("GALASS"),
    GERALDTP("GERALDTP"),
    GERARD("GERARD"),
    GLENMILL("GLENMILL"),
    GFH("GFH"),
    GLDLVNCTR("GLDLVNCTR"),
    GRIFFIN("GRIFFIN"),
    GROWHOM("GROWHOM"),
    GULLHBR("GULLHBR"),
    HFH("HFH"),
    HALST("HALST"),
    HHD("HHD"),
    @XmlEnumValue("HSEHAST2")
    HSEHAST_2("HSEHAST2"),
    @XmlEnumValue("HSNSTILL2")
    HSNSTILL_2("HSNSTILL2"),
    @XmlEnumValue("HSSBURN2")
    HSSBURN_2("HSSBURN2"),
    HAYWARDPLC("HAYWARDPLC"),
    HEARTHBC("HEARTHBC"),
    HEARTHE("HEARTHE"),
    HEARTHGV("HEARTHGV"),
    HEARTHMT("HEARTHMT"),
    HEARTHM("HEARTHM"),
    HEARTHSSP("HEARTHSSP"),
    HEARTHW("HEARTHW"),
    HED("HED"),
    HCJDCPLC("HCJDCPLC"),
    HOMAWAY("HOMAWAY"),
    HOMRNGND("HOMRNGND"),
    ICANWASECA("ICANWASECA"),
    ISANTIYOUP("ISANTIYOUP"),
    IH("IH"),
    ITASKINH("ITASKINH"),
    JOHNSCH("JOHNSCH"),
    KAIROS("KAIROS"),
    KCBGH("KCBGH"),
    KCGGH("KCGGH"),
    KAPANI("KAPANI"),
    KARIBU("KARIBU"),
    KTCSD("KTCSD"),
    @XmlEnumValue("KIDSPEACE2")
    KIDSPEACE_2("KIDSPEACE2"),
    KOHLH("KOHLH"),
    LGFH("LGFH"),
    @XmlEnumValue("LEOAHOFF2")
    LEOAHOFF_2("LEOAHOFF2"),
    LIFEH("LIFEH"),
    LSANDGH("LSANDGH"),
    LSGH("LSGH"),
    LIVINGSTON("LIVINGSTON"),
    LOSTFND("LOSTFND"),
    @XmlEnumValue("MANYRIV2")
    MANYRIV_2("MANYRIV2"),
    MAPLKA("MAPLKA"),
    MAPLET("MAPLET"),
    MARSHAGH("MARSHAGH"),
    MCCROSS("MCCROSS"),
    MCLEODGH("MCLEODGH"),
    MCLEODTS("MCLEODTS"),
    MHDR("MHDR"),
    MERITC("MERITC"),
    @XmlEnumValue("MERITEDC2")
    MERITEDC_2("MERITEDC2"),
    MERRITTH("MERRITTH"),
    MIDWGH("MIDWGH"),
    MFCC("MFCC"),
    MILLELACGH("MILLELACGH"),
    MLNWTRL("MLNWTRL"),
    FFMPLS("FFMPLS"),
    MCFLINOPLC("MCFLINOPLC"),
    MCFRW("MCFRW"),
    THISTLEDEW("THISTLEDEW"),
    MNRVLYJUV("MNRVLYJUV"),
    NGH("NGH"),
    NDBL("NDBL"),
    NEXTSTPPL("NEXTSTPPL"),
    NEXRXEP("NEXRXEP"),
    @XmlEnumValue("MN052002S")
    MN_052002_S("MN052002S"),
    NORTHCROW("NORTHCROW"),
    NHI("NHI"),
    NOCRADLE("NOCRADLE"),
    NCC("NCC"),
    NRC("NRC"),
    NWMC("NWMC"),
    NMJC("NMJC"),
    NOWOODCH("NOWOODCH"),
    OKH("OKH"),
    OCJDCPLC("OCJDCPLC"),
    PATH("PATH"),
    PATHSC("PATHSC"),
    PATHVF("PATHVF"),
    PATHB("PATHB"),
    PATHFIND("PATHFIND"),
    PFHTRF("PFHTRF"),
    PERT("PERT"),
    @XmlEnumValue("PHNIXB510")
    PHNIXB_510("PHNIXB510"),
    PHNIXMLPS("PHNIXMLPS"),
    PLACEN("PLACEN"),
    PLACES("PLACES"),
    PORTBOYGH("PORTBOYGH"),
    PORTGIRLGH("PORTGIRLGH"),
    PLJDCP("PLJDCP"),
    PLYPBGH("PLYPBGH"),
    PLYPGGH("PLYPGGH"),
    PRAXIS("PRAXIS"),
    PRISM("PRISM"),
    PROCTORH("PROCTORH"),
    RHOME("RHOME"),
    RAMCJDC("RAMCJDC"),
    RANGEYS("RANGEYS"),
    RLGH("RLGH"),
    RRSM("RRSM"),
    @XmlEnumValue("REDRVJC2")
    REDRVJC_2("REDRVJC2"),
    RFH("RFH"),
    REMB("REMB"),
    RITEPASS("RITEPASS"),
    RIVEDGE("RIVEDGE"),
    SAFEHAV("SAFEHAV"),
    @XmlEnumValue("SCOTTJAF2")
    SCOTTJAF_2("SCOTTJAF2"),
    SHAREH("SHAREH"),
    SCGMN("SCGMN"),
    SCKIDS("SCKIDS"),
    SYFHRICH("SYFHRICH"),
    SYGHSC("SYGHSC"),
    SYPSAND("SYPSAND"),
    SKYRANCH("SKYRANCH"),
    @XmlEnumValue("SNYD2")
    SNYD_2("SNYD2"),
    SWYS("SWYS"),
    SPRHILLGH("SPRHILLGH"),
    SPRINGF("SPRINGF"),
    @XmlEnumValue("STCLOUDCH2")
    STCLOUDCH_2("STCLOUDCH2"),
    STCLOUDGH("STCLOUDGH"),
    STJOHFC("STJOHFC"),
    STARTSTP("STARTSTP"),
    STORGE("STORGE"),
    SUMOAKSP("SUMOAKSP"),
    SYNERGY("SYNERGY"),
    TITNH("TITNH"),
    TEENMOVFOR("TEENMOVFOR"),
    TEKTC("TEKTC"),
    TSA("TSA"),
    TSHUTCH("TSHUTCH"),
    VLBH("VLBH"),
    VANHM("VANHM"),
    VILRANHHTR("VILRANHHTR"),
    VILRANCH("VILRANCH"),
    VINTGE("VINTGE"),
    VOLAMMPLS("VOLAMMPLS"),
    VONWALD("VONWALD"),
    WAVERLYGH("WAVERLYGH"),
    WELLNCTR("WELLNCTR"),
    WCJCM("WCJCM"),
    WILLOWR("WILLOWR"),
    WILC("WILC"),
    WPH("WPH"),
    @XmlEnumValue("WINGS1")
    WINGS_1("WINGS1"),
    WINNTC("WINNTC"),
    WINONAGH("WINONAGH"),
    WOODFIELDC("WOODFIELDC"),
    WOODLANDPL("WOODLANDPL"),
    WOODWIA("WOODWIA");
    private final String value;

    JuvenilePlacementAgencyTypeCodeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static JuvenilePlacementAgencyTypeCodeType fromValue(String v) {
        for (JuvenilePlacementAgencyTypeCodeType c: JuvenilePlacementAgencyTypeCodeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
