//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.03 at 11:26:33 PM CDT 
//


package gov.mnvcourts.casetget;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for NoContactOrderType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NoContactOrderType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OrderTypeText">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="30"/>
 *               &lt;enumeration value="Interim Condition"/>
 *               &lt;enumeration value="Juvenile Sentence Condition"/>
 *               &lt;enumeration value="Sentence Condition"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="IssuingCourtLocationText" type="{http://www.courts.state.mn.us/CourtXML/3}CourtLocationCodeTextType"/>
 *         &lt;element name="OrderSubject">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://www.courts.state.mn.us/CourtXML/3}PartyBaseType">
 *                 &lt;sequence>
 *                   &lt;element name="PersonBirthDate" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>date">
 *                           &lt;attribute name="currentBirthdate" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="PersonSexText" type="{http://www.courts.state.mn.us/CourtXML/3}GenderTypeCodeTextType" minOccurs="0"/>
 *                   &lt;element name="PersonRace" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="LawEnforcementObservedRaceText" type="{http://www.courts.state.mn.us/CourtXML/3}RaceTypeCodeTextType" maxOccurs="unbounded" minOccurs="0"/>
 *                             &lt;element name="PartyReportedRaceText" type="{http://www.courts.state.mn.us/CourtXML/3}RaceTypeCodeTextType" maxOccurs="unbounded" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ProtectedParty" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://www.courts.state.mn.us/CourtXML/3}PartyNameAddressPhoneEmailType">
 *                 &lt;sequence>
 *                   &lt;element name="PersonBirthDate" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>date">
 *                           &lt;attribute name="currentBirthdate" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="PersonSexText" type="{http://www.courts.state.mn.us/CourtXML/3}GenderTypeCodeTextType" minOccurs="0"/>
 *                   &lt;element name="PersonRace" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="LawEnforcementObservedRaceText" type="{http://www.courts.state.mn.us/CourtXML/3}RaceTypeCodeTextType" maxOccurs="unbounded" minOccurs="0"/>
 *                             &lt;element name="PartyReportedRaceText" type="{http://www.courts.state.mn.us/CourtXML/3}RaceTypeCodeTextType" maxOccurs="unbounded" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="OrderStartDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="OrderEndDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="OrderedBy" type="{http://www.courts.state.mn.us/CourtXML/3}JudicialOfficialType" minOccurs="0"/>
 *         &lt;element name="OrderCommentText" type="{http://www.courts.state.mn.us/CourtXML/3}CommentType" minOccurs="0"/>
 *         &lt;element name="ConditionText" type="{http://www.courts.state.mn.us/CourtXML/3}ConditionNoContactTypeCodeTextType"/>
 *         &lt;element name="ConditionCommentText" type="{http://www.courts.state.mn.us/CourtXML/3}CommentType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="orderEventKey" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *       &lt;attribute name="sentenceEventKey" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *       &lt;attribute name="sentenceDelinquencyDispositionKey" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NoContactOrderType", propOrder = {
    "orderTypeText",
    "issuingCourtLocationText",
    "orderSubject",
    "protectedParty",
    "orderStartDate",
    "orderEndDate",
    "orderedBy",
    "orderCommentText",
    "conditionText",
    "conditionCommentText"
})
public class NoContactOrderType {

    @XmlElement(name = "OrderTypeText", required = true)
    protected String orderTypeText;
    @XmlElement(name = "IssuingCourtLocationText", required = true)
    protected CourtLocationCodeTextType issuingCourtLocationText;
    @XmlElement(name = "OrderSubject", required = true)
    protected NoContactOrderType.OrderSubject orderSubject;
    @XmlElement(name = "ProtectedParty")
    protected List<NoContactOrderType.ProtectedParty> protectedParty;
    @XmlElement(name = "OrderStartDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar orderStartDate;
    @XmlElement(name = "OrderEndDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar orderEndDate;
    @XmlElement(name = "OrderedBy")
    protected JudicialOfficialType orderedBy;
    @XmlElement(name = "OrderCommentText")
    protected String orderCommentText;
    @XmlElement(name = "ConditionText", required = true)
    protected ConditionNoContactTypeCodeTextType conditionText;
    @XmlElement(name = "ConditionCommentText")
    protected String conditionCommentText;
    @XmlAttribute(name = "orderEventKey")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger orderEventKey;
    @XmlAttribute(name = "sentenceEventKey")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger sentenceEventKey;
    @XmlAttribute(name = "sentenceDelinquencyDispositionKey")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger sentenceDelinquencyDispositionKey;

    /**
     * Gets the value of the orderTypeText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderTypeText() {
        return orderTypeText;
    }

    /**
     * Sets the value of the orderTypeText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderTypeText(String value) {
        this.orderTypeText = value;
    }

    /**
     * Gets the value of the issuingCourtLocationText property.
     * 
     * @return
     *     possible object is
     *     {@link CourtLocationCodeTextType }
     *     
     */
    public CourtLocationCodeTextType getIssuingCourtLocationText() {
        return issuingCourtLocationText;
    }

    /**
     * Sets the value of the issuingCourtLocationText property.
     * 
     * @param value
     *     allowed object is
     *     {@link CourtLocationCodeTextType }
     *     
     */
    public void setIssuingCourtLocationText(CourtLocationCodeTextType value) {
        this.issuingCourtLocationText = value;
    }

    /**
     * Gets the value of the orderSubject property.
     * 
     * @return
     *     possible object is
     *     {@link NoContactOrderType.OrderSubject }
     *     
     */
    public NoContactOrderType.OrderSubject getOrderSubject() {
        return orderSubject;
    }

    /**
     * Sets the value of the orderSubject property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoContactOrderType.OrderSubject }
     *     
     */
    public void setOrderSubject(NoContactOrderType.OrderSubject value) {
        this.orderSubject = value;
    }

    /**
     * Gets the value of the protectedParty property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the protectedParty property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProtectedParty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NoContactOrderType.ProtectedParty }
     * 
     * 
     */
    public List<NoContactOrderType.ProtectedParty> getProtectedParty() {
        if (protectedParty == null) {
            protectedParty = new ArrayList<NoContactOrderType.ProtectedParty>();
        }
        return this.protectedParty;
    }

    /**
     * Gets the value of the orderStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getOrderStartDate() {
        return orderStartDate;
    }

    /**
     * Sets the value of the orderStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setOrderStartDate(XMLGregorianCalendar value) {
        this.orderStartDate = value;
    }

    /**
     * Gets the value of the orderEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getOrderEndDate() {
        return orderEndDate;
    }

    /**
     * Sets the value of the orderEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setOrderEndDate(XMLGregorianCalendar value) {
        this.orderEndDate = value;
    }

    /**
     * Gets the value of the orderedBy property.
     * 
     * @return
     *     possible object is
     *     {@link JudicialOfficialType }
     *     
     */
    public JudicialOfficialType getOrderedBy() {
        return orderedBy;
    }

    /**
     * Sets the value of the orderedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link JudicialOfficialType }
     *     
     */
    public void setOrderedBy(JudicialOfficialType value) {
        this.orderedBy = value;
    }

    /**
     * Gets the value of the orderCommentText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderCommentText() {
        return orderCommentText;
    }

    /**
     * Sets the value of the orderCommentText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderCommentText(String value) {
        this.orderCommentText = value;
    }

    /**
     * Gets the value of the conditionText property.
     * 
     * @return
     *     possible object is
     *     {@link ConditionNoContactTypeCodeTextType }
     *     
     */
    public ConditionNoContactTypeCodeTextType getConditionText() {
        return conditionText;
    }

    /**
     * Sets the value of the conditionText property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConditionNoContactTypeCodeTextType }
     *     
     */
    public void setConditionText(ConditionNoContactTypeCodeTextType value) {
        this.conditionText = value;
    }

    /**
     * Gets the value of the conditionCommentText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConditionCommentText() {
        return conditionCommentText;
    }

    /**
     * Sets the value of the conditionCommentText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConditionCommentText(String value) {
        this.conditionCommentText = value;
    }

    /**
     * Gets the value of the orderEventKey property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOrderEventKey() {
        return orderEventKey;
    }

    /**
     * Sets the value of the orderEventKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOrderEventKey(BigInteger value) {
        this.orderEventKey = value;
    }

    /**
     * Gets the value of the sentenceEventKey property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSentenceEventKey() {
        return sentenceEventKey;
    }

    /**
     * Sets the value of the sentenceEventKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSentenceEventKey(BigInteger value) {
        this.sentenceEventKey = value;
    }

    /**
     * Gets the value of the sentenceDelinquencyDispositionKey property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSentenceDelinquencyDispositionKey() {
        return sentenceDelinquencyDispositionKey;
    }

    /**
     * Sets the value of the sentenceDelinquencyDispositionKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSentenceDelinquencyDispositionKey(BigInteger value) {
        this.sentenceDelinquencyDispositionKey = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://www.courts.state.mn.us/CourtXML/3}PartyBaseType">
     *       &lt;sequence>
     *         &lt;element name="PersonBirthDate" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>date">
     *                 &lt;attribute name="currentBirthdate" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="PersonSexText" type="{http://www.courts.state.mn.us/CourtXML/3}GenderTypeCodeTextType" minOccurs="0"/>
     *         &lt;element name="PersonRace" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="LawEnforcementObservedRaceText" type="{http://www.courts.state.mn.us/CourtXML/3}RaceTypeCodeTextType" maxOccurs="unbounded" minOccurs="0"/>
     *                   &lt;element name="PartyReportedRaceText" type="{http://www.courts.state.mn.us/CourtXML/3}RaceTypeCodeTextType" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "personBirthDate",
        "personSexText",
        "personRace"
    })
    public static class OrderSubject
        extends PartyBaseType
    {

        @XmlElement(name = "PersonBirthDate")
        protected List<NoContactOrderType.OrderSubject.PersonBirthDate> personBirthDate;
        @XmlElement(name = "PersonSexText")
        protected GenderTypeCodeTextType personSexText;
        @XmlElementRef(name = "PersonRace", namespace = "http://www.courts.state.mn.us/CourtXML/3", type = JAXBElement.class)
        protected JAXBElement<NoContactOrderType.OrderSubject.PersonRace> personRace;

        /**
         * Gets the value of the personBirthDate property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the personBirthDate property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPersonBirthDate().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link NoContactOrderType.OrderSubject.PersonBirthDate }
         * 
         * 
         */
        public List<NoContactOrderType.OrderSubject.PersonBirthDate> getPersonBirthDate() {
            if (personBirthDate == null) {
                personBirthDate = new ArrayList<NoContactOrderType.OrderSubject.PersonBirthDate>();
            }
            return this.personBirthDate;
        }

        /**
         * Gets the value of the personSexText property.
         * 
         * @return
         *     possible object is
         *     {@link GenderTypeCodeTextType }
         *     
         */
        public GenderTypeCodeTextType getPersonSexText() {
            return personSexText;
        }

        /**
         * Sets the value of the personSexText property.
         * 
         * @param value
         *     allowed object is
         *     {@link GenderTypeCodeTextType }
         *     
         */
        public void setPersonSexText(GenderTypeCodeTextType value) {
            this.personSexText = value;
        }

        /**
         * Gets the value of the personRace property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link NoContactOrderType.OrderSubject.PersonRace }{@code >}
         *     
         */
        public JAXBElement<NoContactOrderType.OrderSubject.PersonRace> getPersonRace() {
            return personRace;
        }

        /**
         * Sets the value of the personRace property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link NoContactOrderType.OrderSubject.PersonRace }{@code >}
         *     
         */
        public void setPersonRace(JAXBElement<NoContactOrderType.OrderSubject.PersonRace> value) {
            this.personRace = ((JAXBElement<NoContactOrderType.OrderSubject.PersonRace> ) value);
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>date">
         *       &lt;attribute name="currentBirthdate" type="{http://www.w3.org/2001/XMLSchema}boolean" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class PersonBirthDate {

            @XmlValue
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar value;
            @XmlAttribute(name = "currentBirthdate")
            protected Boolean currentBirthdate;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setValue(XMLGregorianCalendar value) {
                this.value = value;
            }

            /**
             * Gets the value of the currentBirthdate property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isCurrentBirthdate() {
                return currentBirthdate;
            }

            /**
             * Sets the value of the currentBirthdate property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setCurrentBirthdate(Boolean value) {
                this.currentBirthdate = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="LawEnforcementObservedRaceText" type="{http://www.courts.state.mn.us/CourtXML/3}RaceTypeCodeTextType" maxOccurs="unbounded" minOccurs="0"/>
         *         &lt;element name="PartyReportedRaceText" type="{http://www.courts.state.mn.us/CourtXML/3}RaceTypeCodeTextType" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "lawEnforcementObservedRaceText",
            "partyReportedRaceText"
        })
        public static class PersonRace {

            @XmlElement(name = "LawEnforcementObservedRaceText", nillable = true)
            protected List<RaceTypeCodeTextType> lawEnforcementObservedRaceText;
            @XmlElement(name = "PartyReportedRaceText", nillable = true)
            protected List<RaceTypeCodeTextType> partyReportedRaceText;

            /**
             * Gets the value of the lawEnforcementObservedRaceText property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the lawEnforcementObservedRaceText property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getLawEnforcementObservedRaceText().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link RaceTypeCodeTextType }
             * 
             * 
             */
            public List<RaceTypeCodeTextType> getLawEnforcementObservedRaceText() {
                if (lawEnforcementObservedRaceText == null) {
                    lawEnforcementObservedRaceText = new ArrayList<RaceTypeCodeTextType>();
                }
                return this.lawEnforcementObservedRaceText;
            }

            /**
             * Gets the value of the partyReportedRaceText property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the partyReportedRaceText property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getPartyReportedRaceText().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link RaceTypeCodeTextType }
             * 
             * 
             */
            public List<RaceTypeCodeTextType> getPartyReportedRaceText() {
                if (partyReportedRaceText == null) {
                    partyReportedRaceText = new ArrayList<RaceTypeCodeTextType>();
                }
                return this.partyReportedRaceText;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://www.courts.state.mn.us/CourtXML/3}PartyNameAddressPhoneEmailType">
     *       &lt;sequence>
     *         &lt;element name="PersonBirthDate" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>date">
     *                 &lt;attribute name="currentBirthdate" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="PersonSexText" type="{http://www.courts.state.mn.us/CourtXML/3}GenderTypeCodeTextType" minOccurs="0"/>
     *         &lt;element name="PersonRace" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="LawEnforcementObservedRaceText" type="{http://www.courts.state.mn.us/CourtXML/3}RaceTypeCodeTextType" maxOccurs="unbounded" minOccurs="0"/>
     *                   &lt;element name="PartyReportedRaceText" type="{http://www.courts.state.mn.us/CourtXML/3}RaceTypeCodeTextType" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "personBirthDate",
        "personSexText",
        "personRace"
    })
    public static class ProtectedParty
        extends PartyNameAddressPhoneEmailType
    {

        @XmlElement(name = "PersonBirthDate")
        protected List<NoContactOrderType.ProtectedParty.PersonBirthDate> personBirthDate;
        @XmlElement(name = "PersonSexText")
        protected GenderTypeCodeTextType personSexText;
        @XmlElementRef(name = "PersonRace", namespace = "http://www.courts.state.mn.us/CourtXML/3", type = JAXBElement.class)
        protected JAXBElement<NoContactOrderType.ProtectedParty.PersonRace> personRace;

        /**
         * Gets the value of the personBirthDate property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the personBirthDate property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPersonBirthDate().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link NoContactOrderType.ProtectedParty.PersonBirthDate }
         * 
         * 
         */
        public List<NoContactOrderType.ProtectedParty.PersonBirthDate> getPersonBirthDate() {
            if (personBirthDate == null) {
                personBirthDate = new ArrayList<NoContactOrderType.ProtectedParty.PersonBirthDate>();
            }
            return this.personBirthDate;
        }

        /**
         * Gets the value of the personSexText property.
         * 
         * @return
         *     possible object is
         *     {@link GenderTypeCodeTextType }
         *     
         */
        public GenderTypeCodeTextType getPersonSexText() {
            return personSexText;
        }

        /**
         * Sets the value of the personSexText property.
         * 
         * @param value
         *     allowed object is
         *     {@link GenderTypeCodeTextType }
         *     
         */
        public void setPersonSexText(GenderTypeCodeTextType value) {
            this.personSexText = value;
        }

        /**
         * Gets the value of the personRace property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link NoContactOrderType.ProtectedParty.PersonRace }{@code >}
         *     
         */
        public JAXBElement<NoContactOrderType.ProtectedParty.PersonRace> getPersonRace() {
            return personRace;
        }

        /**
         * Sets the value of the personRace property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link NoContactOrderType.ProtectedParty.PersonRace }{@code >}
         *     
         */
        public void setPersonRace(JAXBElement<NoContactOrderType.ProtectedParty.PersonRace> value) {
            this.personRace = ((JAXBElement<NoContactOrderType.ProtectedParty.PersonRace> ) value);
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>date">
         *       &lt;attribute name="currentBirthdate" type="{http://www.w3.org/2001/XMLSchema}boolean" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class PersonBirthDate {

            @XmlValue
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar value;
            @XmlAttribute(name = "currentBirthdate")
            protected Boolean currentBirthdate;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setValue(XMLGregorianCalendar value) {
                this.value = value;
            }

            /**
             * Gets the value of the currentBirthdate property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isCurrentBirthdate() {
                return currentBirthdate;
            }

            /**
             * Sets the value of the currentBirthdate property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setCurrentBirthdate(Boolean value) {
                this.currentBirthdate = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="LawEnforcementObservedRaceText" type="{http://www.courts.state.mn.us/CourtXML/3}RaceTypeCodeTextType" maxOccurs="unbounded" minOccurs="0"/>
         *         &lt;element name="PartyReportedRaceText" type="{http://www.courts.state.mn.us/CourtXML/3}RaceTypeCodeTextType" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "lawEnforcementObservedRaceText",
            "partyReportedRaceText"
        })
        public static class PersonRace {

            @XmlElement(name = "LawEnforcementObservedRaceText", nillable = true)
            protected List<RaceTypeCodeTextType> lawEnforcementObservedRaceText;
            @XmlElement(name = "PartyReportedRaceText", nillable = true)
            protected List<RaceTypeCodeTextType> partyReportedRaceText;

            /**
             * Gets the value of the lawEnforcementObservedRaceText property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the lawEnforcementObservedRaceText property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getLawEnforcementObservedRaceText().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link RaceTypeCodeTextType }
             * 
             * 
             */
            public List<RaceTypeCodeTextType> getLawEnforcementObservedRaceText() {
                if (lawEnforcementObservedRaceText == null) {
                    lawEnforcementObservedRaceText = new ArrayList<RaceTypeCodeTextType>();
                }
                return this.lawEnforcementObservedRaceText;
            }

            /**
             * Gets the value of the partyReportedRaceText property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the partyReportedRaceText property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getPartyReportedRaceText().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link RaceTypeCodeTextType }
             * 
             * 
             */
            public List<RaceTypeCodeTextType> getPartyReportedRaceText() {
                if (partyReportedRaceText == null) {
                    partyReportedRaceText = new ArrayList<RaceTypeCodeTextType>();
                }
                return this.partyReportedRaceText;
            }

        }

    }

}
