//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.03 at 11:26:33 PM CDT 
//


package gov.mnvcourts.casetget;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}ParkingSpaceType"/>
 *         &lt;element ref="{http://www.courts.state.mn.us/CourtXML/3}ParkingSpaceIdentifier"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "parkingSpaceType",
    "parkingSpaceIdentifier"
})
@XmlRootElement(name = "ParkingSpace")
public class ParkingSpace {

    @XmlElement(name = "ParkingSpaceType", required = true)
    protected String parkingSpaceType;
    @XmlElement(name = "ParkingSpaceIdentifier", required = true)
    protected ParkingSpaceIdentifier parkingSpaceIdentifier;

    /**
     * Gets the value of the parkingSpaceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParkingSpaceType() {
        return parkingSpaceType;
    }

    /**
     * Sets the value of the parkingSpaceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParkingSpaceType(String value) {
        this.parkingSpaceType = value;
    }

    /**
     * Gets the value of the parkingSpaceIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link ParkingSpaceIdentifier }
     *     
     */
    public ParkingSpaceIdentifier getParkingSpaceIdentifier() {
        return parkingSpaceIdentifier;
    }

    /**
     * Sets the value of the parkingSpaceIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParkingSpaceIdentifier }
     *     
     */
    public void setParkingSpaceIdentifier(ParkingSpaceIdentifier value) {
        this.parkingSpaceIdentifier = value;
    }

}
