//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.03 at 11:26:33 PM CDT 
//


package gov.mnvcourts.casetget;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PartyNameType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PartyNameType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.courts.state.mn.us/CourtXML/3}PartyNameBaseType">
 *       &lt;attribute name="currentNameIndicator" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="nameTypeText" type="{http://www.courts.state.mn.us/CourtXML/3}CaseNameTypeCodeType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PartyNameType")
@XmlSeeAlso({
    gov.mnvcourts.casetget.JudgmentSupportType.ObligorPayor.class,
    gov.mnvcourts.casetget.JudgmentSupportType.ObligeePayee.class,
    gov.mnvcourts.casetget.JudgmentSupportType.MedicalInsurance.ObligorPayor.class,
    gov.mnvcourts.casetget.JudgmentSupportType.DentalInsurance.ObligorPayor.class,
    gov.mnvcourts.casetget.FamilyJudgmentType.Reimbursement.ObligorPayor.class
})
public class PartyNameType
    extends PartyNameBaseType
{

    @XmlAttribute(name = "currentNameIndicator", required = true)
    protected boolean currentNameIndicator;
    @XmlAttribute(name = "nameTypeText")
    protected CaseNameTypeCodeType nameTypeText;

    /**
     * Gets the value of the currentNameIndicator property.
     * 
     */
    public boolean isCurrentNameIndicator() {
        return currentNameIndicator;
    }

    /**
     * Sets the value of the currentNameIndicator property.
     * 
     */
    public void setCurrentNameIndicator(boolean value) {
        this.currentNameIndicator = value;
    }

    /**
     * Gets the value of the nameTypeText property.
     * 
     * @return
     *     possible object is
     *     {@link CaseNameTypeCodeType }
     *     
     */
    public CaseNameTypeCodeType getNameTypeText() {
        return nameTypeText;
    }

    /**
     * Sets the value of the nameTypeText property.
     * 
     * @param value
     *     allowed object is
     *     {@link CaseNameTypeCodeType }
     *     
     */
    public void setNameTypeText(CaseNameTypeCodeType value) {
        this.nameTypeText = value;
    }

}
