//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.03 at 11:26:33 PM CDT 
//


package gov.mnvcourts.casetget;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * A number issued by a state Automated Fingerprint Identification System (AFIS) based on submitted fingerprints. Sometimes referred to as a State ID number or a SID.
 * 
 * <p>Java class for PersonStateIDType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PersonStateIDType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ID" type="{http://www.courts.state.mn.us/CourtXML/3}ID1to30Type"/>
 *         &lt;element name="IDJurisdictionCode" type="{http://www.courts.state.mn.us/CourtXML/3}StateCodeType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PersonStateIDType", propOrder = {
    "id",
    "idJurisdictionCode"
})
@XmlSeeAlso({
    gov.mnvcourts.casetget.CaseGetCitationDocumentType.Citation.Citee.PersonAssignedIDDetails.PersonStateID.class,
    gov.mnvcourts.casetget.PersonAssignedIDDetailsType.PersonStateID.class
})
public class PersonStateIDType {

    @XmlElement(name = "ID", required = true)
    protected String id;
    @XmlElement(name = "IDJurisdictionCode", required = true)
    protected StateCodeType idJurisdictionCode;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the idJurisdictionCode property.
     * 
     * @return
     *     possible object is
     *     {@link StateCodeType }
     *     
     */
    public StateCodeType getIDJurisdictionCode() {
        return idJurisdictionCode;
    }

    /**
     * Sets the value of the idJurisdictionCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link StateCodeType }
     *     
     */
    public void setIDJurisdictionCode(StateCodeType value) {
        this.idJurisdictionCode = value;
    }

}
