//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.03 at 11:26:33 PM CDT 
//


package gov.mnvcourts.casetget;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PropertyAwardType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PropertyAwardType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PropertyTypeText" type="{http://www.courts.state.mn.us/CourtXML/3}PropertyCodeTextType"/>
 *         &lt;element name="PropertyDescriptionText" type="{http://www.courts.state.mn.us/CourtXML/3}CommentType" minOccurs="0"/>
 *         &lt;element name="VehicleIdentificationNumber" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PropertyAwardType", propOrder = {
    "propertyTypeText",
    "propertyDescriptionText",
    "vehicleIdentificationNumber"
})
public class PropertyAwardType {

    @XmlElement(name = "PropertyTypeText", required = true)
    protected PropertyCodeTextType propertyTypeText;
    @XmlElement(name = "PropertyDescriptionText")
    protected String propertyDescriptionText;
    @XmlElement(name = "VehicleIdentificationNumber")
    protected String vehicleIdentificationNumber;

    /**
     * Gets the value of the propertyTypeText property.
     * 
     * @return
     *     possible object is
     *     {@link PropertyCodeTextType }
     *     
     */
    public PropertyCodeTextType getPropertyTypeText() {
        return propertyTypeText;
    }

    /**
     * Sets the value of the propertyTypeText property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertyCodeTextType }
     *     
     */
    public void setPropertyTypeText(PropertyCodeTextType value) {
        this.propertyTypeText = value;
    }

    /**
     * Gets the value of the propertyDescriptionText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPropertyDescriptionText() {
        return propertyDescriptionText;
    }

    /**
     * Sets the value of the propertyDescriptionText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPropertyDescriptionText(String value) {
        this.propertyDescriptionText = value;
    }

    /**
     * Gets the value of the vehicleIdentificationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVehicleIdentificationNumber() {
        return vehicleIdentificationNumber;
    }

    /**
     * Sets the value of the vehicleIdentificationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVehicleIdentificationNumber(String value) {
        this.vehicleIdentificationNumber = value;
    }

}
